### ISSUE TITLE
Counting object descendants sometimes causes a ConcurrentModificationException

### ISSUE THREAD

**Issue by petebankhead** [qupath/qupath#1182]
## Bug report

**Describe the bug**
Concurrent modification exception has been spotted with the stack trace:

```
ERROR: QuPath exception
java.util.ConcurrentModificationException: null
    at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(Unknown Source)
    at java.base/java.util.LinkedHashMap$LinkedKeyIterator.next(Unknown Source)
    at qupath.lib.objects.PathObject.nDescendants(PathObject.java:528)
    at qupath.lib.objects.PathObjectTools.countDescendants(PathObjectTools.java:204)
    at qupath.lib.objects.PathObject.objectCountPostfix(PathObject.java:238)
    at qupath.lib.objects.PathObject.toString(PathObject.java:276)
    at qupath.lib.gui.tools.PathObjectLabels$PathObjectMiniPane.setPathObject(PathObjectLabels.java:247)
    at qupath.lib.gui.tools.PathObjectLabels$PathObjectListCell.updateItem(PathObjectLabels.java:151)
    at qupath.lib.gui.tools.PathObjectLabels$PathObjectListCell.updateItem(PathObjectLabels.java:138)
    at javafx.scene.control.ListCell.updateItem(ListCell.java:485)
    at javafx.scene.control.ListCell.lambda$new$2(ListCell.java:168)
    at javafx.collections.WeakListChangeListener.onChanged(WeakListChangeListener.java:88)
    at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
    at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
    at javafx.collections.ObservableListBase.fireChange(ObservableListBase.java:239)
    at javafx.collections.ListChangeBuilder.commit(ListChangeBuilder.java:482)
    at javafx.collections.ListChangeBuilder.endChange(ListChangeBuilder.java:541)
    at javafx.collections.ObservableListBase.endChange(ObservableListBase.java:211)
    at javafx.collections.ModifiableObservableListBase.setAll(ModifiableObservableListBase.java:98)
    at qupath.lib.gui.panes.AnnotationPane.hierarchyChanged(AnnotationPane.java:436)
    at qupath.lib.gui.panes.AnnotationPane.lambda$hierarchyChanged$9(AnnotationPane.java:404)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
    at java.base/java.security.AccessController.doPrivileged(Unknown Source)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
    at java.base/java.lang.Thread.run(Unknown Source)
```

**To Reproduce**
See https://forum.image.sc/t/error-from-roitools-subtract-in-qupath-v0-4-0/74837

**Expected behavior**
Updating the list cell shouldn't throw any exception.

**Desktop (please complete the following information):**
 - OS: All (presumably)
 - QuPath Version: 0.4.0

**Additional context**
I haven't replicated the problem yet.

**Comment by lacan** [comment]
Hi Pete!
Reopening this as it's very similar and still happening in QuPath 0.5.0
A user had an annotation inside which there was another annotation filled with detections (over 5000)
When runing "Delaunay cluster features 2D" we ran into
```
Error running plugin: java.util.ConcurrentModificationException
java.util.concurrent.ExecutionException: java.util.ConcurrentModificationException
at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
at qupath.lib.plugins.AbstractTaskRunner.awaitCompletion(AbstractTaskRunner.java:147)
at qupath.lib.plugins.AbstractTaskRunner.runTasks(AbstractTaskRunner.java:117)
at qupath.lib.gui.TaskRunnerFX.runTasks(TaskRunnerFX.java:106)
at qupath.lib.plugins.AbstractPlugin.runPlugin(AbstractPlugin.java:147)
at qupath.lib.gui.ParameterDialogWrapper$1.run(ParameterDialogWrapper.java:177)
at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.util.ConcurrentModificationException
at java.base/java.util.ArrayList.checkForComodification(Unknown Source)
at java.base/java.util.ArrayList.equals(Unknown Source)
at java.base/java.util.WeakHashMap.matchesKey(Unknown Source)
at java.base/java.util.WeakHashMap.get(Unknown Source)
at java.base/java.util.Collections$SynchronizedMap.get(Unknown Source)
at qupath.lib.measurements.NumericMeasurementList$AbstractNumericMeasurementList.getNameMap(NumericMeasurementList.java:142)
at qupath.lib.measurements.NumericMeasurementList$AbstractNumericMeasurementList.close(NumericMeasurementList.java:133)
at qupath.lib.measurements.NumericMeasurementList$FloatList.close(NumericMeasurementList.java:352)
at qupath.opencv.features.DelaunayTriangulation.addClusterMeasurements(DelaunayTriangulation.java:466)
at qupath.opencv.features.DelaunayClusteringPlugin$DelaunayRunnable.run(DelaunayClusteringPlugin.java:215)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
```
I can ask them to share a QuPath project if it's useful to you. 

The issue appeared on a built from source linux QuPath if that's of any use.

All the best and happy new year
