### ISSUE TITLE
mergeSelectedAnnotations();  blocks further processing in QuPath from selecting Objects or Annotations by script

### ISSUE THREAD

**Issue by DavidMHaumann** [qupath/qupath#129]
Dear all, hi Pete, 

I observed, that the selection of Annotations or Objects in scripting does not work anymore after the line: 

mergeSelectedAnnotations(); 

If this line is followed by selection of annotations or objects with: 

selectObjects {
    return it.isAnnotation() && it.getPathClass() == getPathClass('CLASSNAME')
}; 

Or 

selectObjects {it.isAnnotation() && it.getPathClass() == null};

Or 

selectObjects { p -> p.getPathClass() == getPathClass("CLASSNAME") };

The Objects/Annotations will just not be selected in the running script. 

A second run of the missed script part will work after restart from the place of interruption. 

No clue why this happens. 

Does anyone have an idea?

**Comment by Svidro** [comment]
Hypothesis: I don't think the program clears what is "selected" after the merge, so trying to create a new selection fails.  Note that if you only have one object selected, and choose to merge, the selectObjects command will work, maybe because no changes have been made to the hierarchy.

Fix: Add resetSelection()  after the merge to clear the currently selected object set.

**Comment by petebankhead** [comment]
I'm not able to replicate this... if I open an image and draw a few rectangles and few ellipses, this works fine:
```groovy
selectObjects {it.isAnnotation() && it.getROI().getROIType() == 'Rectangle'}
mergeSelectedAnnotations()
selectObjects {it.isAnnotation() && it.getROI().getROIType() == 'Ellipse'}
```
At the end, the rectangles are merged and the ellipses are selected.

Does it work for you?  If so, then maybe it some other part of the script; if not, then I could try running it on another computer (are you using Windows?).

**Comment by DavidMHaumann** [comment]
Hi Pete, 

I have annotations that are created by the tiles to annotations plugin. So I have 3 different classes and a lot of annotations of the same class. 
Then i select annotations by class 1 first, merge them and then i want to go on by selecting all annotations with class 2. 
That is the point when it fails. Running all steps within one run does not work. 

Yes, I use windows. 
And no, the above script with rectangles and ellipse does not work on my laptop. It has Windows 10. 

Svidros recommendation (thank you Svidro) did also not help. 

I get a script error: Line 27 is my second "mergeSelectedAnnotations();" after 
resetSelection();
selectObjects { p -> p.getPathClass() == getPathClass("NAMEofCLASS") };

ERROR: Error at line 27: null

ERROR: Script error
    at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
    at java.util.LinkedHashMap$LinkedKeyIterator.next(LinkedHashMap.java:742)
    at java.util.Collections$UnmodifiableCollection$1.next(Collections.java:1042)
    at qupath.lib.scripting.QPEx.mergeAnnotations(QPEx.java:320)
    at qupath.lib.scripting.QPEx.mergeSelectedAnnotations(QPEx.java:353)
    at qupath.lib.scripting.QPEx.mergeSelectedAnnotations(QPEx.java:309)
    at qupath.lib.scripting.QPEx$mergeSelectedAnnotations$0.callStatic(Unknown Source)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:56)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:194)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:198)
    at Script132.run(Script132.groovy:28)
    at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:343)
    at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:152)
    at qupath.lib.scripting.DefaultScriptEditor.executeScript(DefaultScriptEditor.java:765)
    at qupath.lib.scripting.DefaultScriptEditor.executeScript(DefaultScriptEditor.java:695)
    at qupath.lib.scripting.DefaultScriptEditor.executeScript(DefaultScriptEditor.java:677)
    at qupath.lib.scripting.DefaultScriptEditor.access$400(DefaultScriptEditor.java:136)
    at qupath.lib.scripting.DefaultScriptEditor$2.run(DefaultScriptEditor.java:1029)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by Svidro** [comment]
Ok, that does work for me.  It seems to vary depending on a few more factors!  And Windows for me.

It looks like the problem may be with the it.getPathClass() == null after merging the previous annotations.
Running just the line:
`selectObjects {it.isAnnotation() && it.getPathClass() == null};
`
Always seems to work on its own.
While after a merge, it returns a warning:
```
selectObjects {it.isAnnotation() && it.getROI().getROIType() == 'Rectangle'};
mergeSelectedAnnotations()
//resetSelection()
selectObjects {it.isAnnotation() && it.getPathClass() == null};
```

> WARN: Cannot assign class unambiguously - 0 classes represented in selection

**Comment by Svidro** [comment]
The null error makes sense if the selectObjects is empty.
Trying the following script with two of my non rectangle annotations set to Tumor:
```
selectObjects {it.isAnnotation() && it.getROI().getROIType() == 'Rectangle'}
mergeSelectedAnnotations()
selectObjects {it.isAnnotation() && it.getPathClass() == getPathClass("Tumor")}
```

Nets me the following error, provided there are two or more rectangles to merge (if no merge is performed, there is no error and the selection happens successfully):

> INFO: Image data set to ImageData: Not set, 375424
ERROR: QuPath exception
    at com.sun.javafx.scene.control.ReadOnlyUnbackedObservableList.subList(ReadOnlyUnbackedObservableList.java:136)
    at javafx.collections.ListChangeListener$Change.getAddedSubList(ListChangeListener.java:242)
    at com.sun.javafx.scene.control.behavior.ListViewBehavior.lambda$new$177(ListViewBehavior.java:269)
    at javafx.collections.WeakListChangeListener.onChanged(WeakListChangeListener.java:88)
    at com.sun.javafx.collections.ListListenerHelper$Generic.fireValueChangedEvent(ListListenerHelper.java:329)
    at com.sun.javafx.collections.ListListenerHelper.fireValueChangedEvent(ListListenerHelper.java:73)
    at com.sun.javafx.scene.control.ReadOnlyUnbackedObservableList.callObservers(ReadOnlyUnbackedObservableList.java:75)
    at javafx.scene.control.MultipleSelectionModelBase.selectIndices(MultipleSelectionModelBase.java:529)
    at qupath.lib.gui.panels.PathAnnotationPanel.selectedPathObjectChanged(PathAnnotationPanel.java:762)
    at qupath.lib.gui.panels.PathAnnotationPanel.lambda$selectedPathObjectChanged$15(PathAnnotationPanel.java:704)
    at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
    at java.lang.Thread.run(Thread.java:745)
WARN: Cannot assign class unambiguously - 0 classes represented in selection
INFO: Adding Area (AWT) to hierarchy

**Comment by petebankhead** [comment]
The warning
```
WARN: Cannot assign class unambiguously - 0 classes represented in selection
```
should be ok - QuPath is checking if there is one and only one classification that it can use to assign to the merged annotation.  Unfortunately it's not smart enough to recognize that no classifications is fine as well, and doesn't really require a warning.

But the latest script from @Svidro lets me experience the trouble described in the original question (albeit not an error message).

I'm not entirely sure where it is going wrong, but I assume that it is somehow connected to multithreading, and things not being done in quite the right order.  I suspect it's also connected to the selection changing while other processing is happening.  This will be triggering some activity in the thread responsible for the user interface.

Here are three ways to try to work around this - hopefully at least one of them will work.

### Method 1 - Do everything in the application thread
As the *very* first line of your script (with no spaces above it), add
```
guiscript=true
```
to force the script to run in the same thread as the user interface.  This can often help work around troublesome multithreading issues for scripts that run very quickly.  It's probably not a good idea here because the processing is likely to take a while, and the GUI will be totally blocked.

### Method 2 - Pause briefly
Adding `Thread.sleep(time)` pauses the script for a specified number of milliseconds, which can be enough to get things on track.
```groovy
selectObjects {it.isAnnotation() && it.getROI().getROIType() == 'Rectangle'}
mergeSelectedAnnotations()
Thread.sleep(100)
selectObjects {it.isAnnotation() && it.getPathClass() == getPathClass("Tumor")}
```

### Method 3 - Avoid depending on selections
If possible, it's usually good to avoid depending on objects being selected if you don't have to.  Sometimes it's necessary (e.g. if you're running a command like cell detection, the annotations/TMA cores need to be selected for the command to work), but in this case there's an alternative:
```groovy
annotations = getAnnotationObjects().findAll {it.isAnnotation() && it.getROI().getROIType() == 'Rectangle'}
mergeAnnotations(annotations)
selectObjects {it.isAnnotation() && it.getPathClass() == getPathClass("Tumor")}
```
For me all three of these methods seem to work, at least in my simple example.

**Comment by Svidro** [comment]
Oooh, mergeAnnotations looks great.  I was going to say that I have been trying to avoid selecting, but didn't realize there was an easy workaround for the merge in this case!

**Comment by DavidMHaumann** [comment]
Hi Pete, 

Method 2 works for me on windows. 
Method 3 works as well. 
I changed it into: 

annotations = getAnnotationObjects().findAll {it.isAnnotation() && it.getPathClass() == getPathClass("NameOfClass")}
mergeAnnotations(annotations)
selectObjects {it.isAnnotation() && it.getPathClass() == getPathClass("NameOfClass")}
mergeSelectedAnnotations();

I guess I will use method 2, since it is only one line of code. 

Thanks a lot. It is fantastic!  This will save us hours of manual work!

Best
David
