### ISSUE TITLE
Full image annotation for Sparse training image throws errors for detections

### ISSUE THREAD

**Issue by Ross-AC** [qupath/qupath#1443]
## Bug report

**Describe the bug**
When optimising perameters for a project by creating a sparse composite image from different image entries. When running cell detection using script editor, errors are generated for the final tiles **IF** the entire shape is not a perfect rectangle. If using stardist script for cell detection, errors are generated before any detections.

**Can avoid both by manual annotation** with a polygon tool to follow image boundaries -> so not sure if a crucial bug. Carried over from last release to v5.

**To Reproduce**
1. Ctl+Shift+A
2. Run cell detection as a script:
```
setImageType('FLUORESCENCE');
selectAnnotations();
runPlugin('qupath.imagej.detect.cells.WatershedCellDetection', '{"detectionImage":"DAPI","requestedPixelSizeMicrons":0.1,"backgroundRadiusMicrons":4.0,"backgroundByReconstruction":true,"medianRadiusMicrons":1.0,"sigmaMicrons":2.5,"minAreaMicrons":11.0,"maxAreaMicrons":400.0,"threshold":1000.0,"watershedPostProcess":true,"cellExpansionMicrons":5.0,"includeNuclei":true,"smoothBoundaries":true,"makeMeasurements":true}')
```
4. Error:
```
ERROR: Error running plugin: java.lang.NullPointerException: Cannot invoke "java.awt.image.BufferedImage.getSampleModel()" because "img" is null
java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "java.awt.image.BufferedImage.getSampleModel()" because "img" is null
    at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
    at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
    at qupath.lib.plugins.AbstractTaskRunner.awaitCompletion(AbstractTaskRunner.java:147)
    at qupath.lib.plugins.AbstractTaskRunner.runTasks(AbstractTaskRunner.java:117)
    at qupath.lib.gui.TaskRunnerFX.runTasks(TaskRunnerFX.java:106)
    at qupath.lib.plugins.AbstractPlugin.runPlugin(AbstractPlugin.java:147)
    at qupath.lib.gui.QuPathGUI.runPlugin(QuPathGUI.java:2245)
    at qupath.lib.gui.scripting.QPEx.runPlugin(QPEx.java:248)
    at qupath.lib.gui.scripting.QPEx.runPlugin(QPEx.java:270)
    at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
    at QuPathScript.run(QuPathScript:4)
    at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:331)
    at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:161)
    at qupath.lib.gui.scripting.languages.DefaultScriptLanguage.execute(DefaultScriptLanguage.java:234)
    at qupath.lib.gui.scripting.DefaultScriptEditor.executeScript(DefaultScriptEditor.java:1166)
    at qupath.lib.gui.scripting.DefaultScriptEditor$3.run(DefaultScriptEditor.java:1534)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.base/java.lang.Thread.run(Unknown Source)
  Caused by Cannot invoke "java.awt.image.BufferedImage.getSampleModel()" because "img" is null        at qupath.imagej.tools.IJTools.convertToUncalibratedImagePlus(IJTools.java:791)
        at qupath.imagej.tools.IJTools.convertToImagePlus(IJTools.java:864)
        at qupath.imagej.tools.IJTools.convertToImagePlus(IJTools.java:902)
        at qupath.imagej.detect.cells.WatershedCellDetection$CellDetector.runDetection(WatershedCellDetection.java:216)
        at qupath.lib.plugins.DetectionPluginTools$DetectionRunnable.run(DetectionPluginTools.java:112)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```
6. Error repeats per tile

**Expected behavior**
To recognise bounds or the image in "create full image annotation" command, excluding what the error is calling "null" regions

**Screenshots**
![image](https://github.com/qupath/qupath/assets/154437026/e0daa716-19b8-47f9-b337-aa02cb1e44e9)

![image](https://github.com/qupath/qupath/assets/154437026/990ad117-5649-4e15-b376-8bce56d722bb)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - QuPath Version: 0.5.0

**Additional context**
Same issue was present in previous version (0.4.4)

**Comment by Ross-AC** [comment]
Quick addition. Defining an area using a polygon no longer works for the in-built detection, just when running a stardist script:

![image](https://github.com/qupath/qupath/assets/154437026/9e4ba23a-f54a-4742-8a5c-ec10b063f7f2)

```
ERROR: Error processing Polygon (7616, 10604, 2099, 1863)
java.io.IOException: java.lang.InterruptedException
    at qupath.lib.images.servers.bioformats.BioFormatsImageServer.readTile(BioFormatsImageServer.java:911)
    at qupath.lib.images.servers.AbstractTileableImageServer.lambda$prerequestTiles$2(AbstractTileableImageServer.java:462)
    at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
    at qupath.lib.images.servers.AbstractTileableImageServer.prerequestTiles(AbstractTileableImageServer.java:464)
    at qupath.lib.images.servers.AbstractTileableImageServer.readRegion(AbstractTileableImageServer.java:295)
    at qupath.lib.images.servers.AbstractTileableImageServer.readRegion(AbstractTileableImageServer.java:60)
    at qupath.lib.images.servers.CroppedImageServer.readRegion(CroppedImageServer.java:90)
    at qupath.lib.images.servers.CroppedImageServer.readRegion(CroppedImageServer.java:39)
    at qupath.lib.images.servers.SparseImageServer.readTile(SparseImageServer.java:265)
    at qupath.lib.images.servers.AbstractTileableImageServer.lambda$prerequestTiles$2(AbstractTileableImageServer.java:462)
    at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
    at qupath.lib.images.servers.AbstractTileableImageServer.prerequestTiles(AbstractTileableImageServer.java:464)
    at qupath.lib.images.servers.AbstractTileableImageServer.readRegion(AbstractTileableImageServer.java:295)
    at qupath.lib.images.servers.AbstractTileableImageServer.readRegion(AbstractTileableImageServer.java:60)
    at qupath.imagej.tools.IJTools.convertToImagePlus(IJTools.java:863)
    at qupath.imagej.tools.IJTools.convertToImagePlus(IJTools.java:902)
    at qupath.imagej.detect.cells.WatershedCellDetection$CellDetector.runDetection(WatershedCellDetection.java:216)
    at qupath.lib.plugins.DetectionPluginTools$DetectionRunnable.run(DetectionPluginTools.java:112)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.base/java.lang.Thread.run(Unknown Source)
  Caused by null        at java.base/java.util.concurrent.locks.ReentrantLock$Sync.lockInterruptibly(Unknown Source)
        at java.base/java.util.concurrent.locks.ReentrantLock.lockInterruptibly(Unknown Source)
        at java.base/java.util.concurrent.ArrayBlockingQueue.put(Unknown Source)
        at qupath.lib.images.servers.bioformats.BioFormatsImageServer$ReaderPool.openImage(BioFormatsImageServer.java:1411)
        at qupath.lib.images.servers.bioformats.BioFormatsImageServer.readTile(BioFormatsImageServer.java:909)
        at qupath.lib.images.servers.AbstractTileableImageServer.lambda$prerequestTiles$2(AbstractTileableImageServer.java:462)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at qupath.lib.images.servers.AbstractTileableImageServer.prerequestTiles(AbstractTileableImageServer.java:464)
        at qupath.lib.images.servers.AbstractTileableImageServer.readRegion(AbstractTileableImageServer.java:295)
        at qupath.lib.images.servers.AbstractTileableImageServer.readRegion(AbstractTileableImageServer.java:60)
        at qupath.lib.images.servers.CroppedImageServer.readRegion(CroppedImageServer.java:90)
        at qupath.lib.images.servers.CroppedImageServer.readRegion(CroppedImageServer.java:39)
        at qupath.lib.images.servers.SparseImageServer.readTile(SparseImageServer.java:265)
        at qupath.lib.images.servers.AbstractTileableImageServer.lambda$prerequestTiles$2(AbstractTileableImageServer.java:462)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at qupath.lib.images.servers.AbstractTileableImageServer.prerequestTiles(AbstractTileableImageServer.java:464)
        at qupath.lib.images.servers.AbstractTileableImageServer.readRegion(AbstractTileableImageServer.java:295)
        at qupath.lib.images.servers.AbstractTileableImageServer.readRegion(AbstractTileableImageServer.java:60)
        at qupath.imagej.tools.IJTools.convertToImagePlus(IJTools.java:863)
        at qupath.imagej.tools.IJTools.convertToImagePlus(IJTools.java:902)
        at qupath.imagej.detect.cells.WatershedCellDetection$CellDetector.runDetection(WatershedCellDetection.java:216)
        at qupath.lib.plugins.DetectionPluginTools$DetectionRunnable.run(DetectionPluginTools.java:112)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by Rylern** [comment]
#1465 should fix the first issue.

About:

> Quick addition. Defining an area using a polygon no longer works for the in-built detection, just when running a stardist script:

I wasn't able to reproduce the error. Does it happens on every run? Is it possible to share the project throwing the error?
