### ISSUE TITLE
Exception in thread "main" java.lang.UnsupportedOperationException: Unable to open DISPLAY

### ISSUE THREAD

**Issue by Rafael-Silva-Oliveira** [qupath/qupath#1547]
Hi, I'm getting the following bug when launching QuPath from a ssh server:

WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @62379589'
Exception in thread "main" java.lang.UnsupportedOperationException: Unable to open DISPLAY
        at com.sun.glass.ui.gtk.GtkApplication.lambda$new$5(GtkApplication.java:165)
        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
        at com.sun.glass.ui.gtk.GtkApplication.<init>(GtkApplication.java:163)
        at com.sun.glass.ui.gtk.GtkPlatformFactory.createApplication(GtkPlatformFactory.java:40)
        at com.sun.glass.ui.Application.run(Application.java:145)
        at com.sun.javafx.tk.quantum.QuantumToolkit.startup(QuantumToolkit.java:290)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:292)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:162)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:651)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:671)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
        at java.base/java.lang.Thread.run(Unknown Source)

Anyone knows why this is happening?

Using latest version QuPath and JDK 17, but nothing seems to work

**Comment by alanocallaghan** [comment]
How are you connecting to the SSH server, and how are you launching QuPath? It sounds like you've connected without X11 forwarding, and are trying to launch the QuPath GUI.

In this case, either modify the entry in your `~/.ssh/config` to set `ForwardX11 true`, eg

```
Host myhost
    HostName hostname.subdomain.domain
    ForwardX11 yes
```

or if specifying on the command line, `ssh -X myhost`

Then launch QuPath as normal, eg `QuPath --image=/path/to/my/image`
