### ISSUE TITLE
support tif with more than 1GB?

### ISSUE THREAD

**Issue by dzfowen** [qupath/qupath#156]
Could qupath support a tif with large size?

I tried a tif 1.49G but failed.

**Comment by petebankhead** [comment]
QuPath can handle TIFF files much bigger than 1.49 GB.  But it is important that they are stored in a pyramidal format, with the image data stored at different resolutions - as it typical if the images are from a whole slide scanner.

Is that the case for your image?  Or can you say more about how it was created?

If your image is pyramidal, and you haven't already installed the QuPath Bio-Formats extension, you could try this to see if it helps by increasing the range of supported images: https://github.com/qupath/qupath-bioformats-extension

> Note the installation instructions at the bottom of the page; if it does not work immediately, consider adding `.tif` to the *Always use Bio-Formats for the specified image extensions* preference option, to make sure that no other image reader tries to handle the TIFF instead.  But if you do this and encounter problems with other TIFFs, remember to reset this option to let QuPath decide which reader is most appropriate - which is the default behavior.

Otherwise, this link may help: https://github.com/openslide/openslide/wiki/CreatingPyramidalTIFFs

**Comment by dzfowen** [comment]
Thanks a lot. I downloaded tif from camelyon16 datasets. A single one is over 1GB. I have installed bioformats extension, but it seems cannot help. Should I need some format transformed?  Thank you!

**Comment by petebankhead** [comment]
Ah ok, it should be a pyramidal TIFF then.

Are you running QuPath on Linux, by any chance?  Or what platform?  To you see any error message when you try, either popping up or under *View &rarr; Show log*?

**Comment by petebankhead** [comment]
I can open Camelyon16 images with QuPath on macOS 10.13, Ubuntu 16.04 and Windows 10 (the last two through VirtualBox).  So it definitely *should* work.  I'd certainly like to find a way to resolve it since it doesn't.

I didn't have any luck with Bio-Formats though - so that suggestion can be discarded.

My best guess is that you're using Linux and the solution involves building/installing OpenSlide separately.  You can then remove/replace any OpenSlide-related files from within the *qupath/app* directory.

If you copy your own OpenSlide files into that directory then it should be ok; otherwise, you probably need to set the Java library path within *QuPath.cfg* (which is also in the same directory).

**Comment by dzfowen** [comment]
Hi, I test in Mac OS 10.13.3, I find log with errors:

ERROR: Unable to open /Users/dzf/camelyon16-grand-challenge/data/TrainingData/Train_Tumor/Tumor_005.tif
    at loci.formats.in.TiffJAIReader.initFile(TiffJAIReader.java:111)
    at loci.formats.FormatReader.setId(FormatReader.java:1397)
    at loci.formats.DelegateReader.setId(DelegateReader.java:300)
    at loci.formats.ImageReader.setId(ImageReader.java:839)
    at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:650)
    at loci.formats.Memoizer.setId(Memoizer.java:677)
    at qupath.lib.images.servers.BioFormatsImageServer$BioFormatsReaderManager.createReader(BioFormatsImageServer.java:1156)
    at qupath.lib.images.servers.BioFormatsImageServer$BioFormatsReaderManager.createReader(BioFormatsImageServer.java:1111)
    at qupath.lib.images.servers.BioFormatsImageServer$BioFormatsReaderManager.getPrimaryReader(BioFormatsImageServer.java:1025)
    at qupath.lib.images.servers.BioFormatsImageServer.<init>(BioFormatsImageServer.java:234)
    at qupath.lib.images.servers.BioFormatsImageServer.<init>(BioFormatsImageServer.java:198)
    at qupath.lib.images.servers.BioFormatsServerBuilder.buildServer(BioFormatsServerBuilder.java:46)
    at qupath.lib.images.servers.ImageServerProvider.buildServer(ImageServerProvider.java:115)
    at qupath.lib.gui.QuPathGUI.openImage(QuPathGUI.java:2228)
    at qupath.lib.gui.viewer.DragDropFileImportListener.handleFileDrop(DragDropFileImportListener.java:253)
    at qupath.lib.gui.viewer.DragDropFileImportListener.handle(DragDropFileImportListener.java:115)
    at qupath.lib.gui.viewer.DragDropFileImportListener.handle(DragDropFileImportListener.java:59)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene$DnDGesture.fireEvent(Scene.java:2933)
    at javafx.scene.Scene$DnDGesture.processTargetDrop(Scene.java:3159)
    at javafx.scene.Scene$DnDGesture.access$6400(Scene.java:2909)
    at javafx.scene.Scene$DropTargetListener.drop(Scene.java:2873)
    at com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.lambda$handleDragDrop$309(GlassSceneDnDEventHandler.java:95)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.handleDragDrop(GlassSceneDnDEventHandler.java:92)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleDragDrop$363(GlassViewEventHandler.java:700)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleDragDrop(GlassViewEventHandler.java:699)
    at com.sun.glass.ui.View.handleDragDrop(View.java:712)
    at com.sun.glass.ui.View.notifyDragDrop(View.java:1037)
  Caused by No such class: javax.media.jai.NullOpImage        at loci.common.ReflectedUniverse.exec(ReflectedUniverse.java:161)
        at loci.formats.in.TiffJAIReader.initFile(TiffJAIReader.java:104)
        at loci.formats.FormatReader.setId(FormatReader.java:1397)
        at loci.formats.DelegateReader.setId(DelegateReader.java:300)
        at loci.formats.ImageReader.setId(ImageReader.java:839)
        at loci.formats.ReaderWrapper.setId(ReaderWrapper.java:650)
        at loci.formats.Memoizer.setId(Memoizer.java:677)
        at qupath.lib.images.servers.BioFormatsImageServer$BioFormatsReaderManager.createReader(BioFormatsImageServer.java:1156)
        at qupath.lib.images.servers.BioFormatsImageServer$BioFormatsReaderManager.createReader(BioFormatsImageServer.java:1111)
        at qupath.lib.images.servers.BioFormatsImageServer$BioFormatsReaderManager.getPrimaryReader(BioFormatsImageServer.java:1025)
        at qupath.lib.images.servers.BioFormatsImageServer.<init>(BioFormatsImageServer.java:234)
        at qupath.lib.images.servers.BioFormatsImageServer.<init>(BioFormatsImageServer.java:198)
        at qupath.lib.images.servers.BioFormatsServerBuilder.buildServer(BioFormatsServerBuilder.java:46)
        at qupath.lib.images.servers.ImageServerProvider.buildServer(ImageServerProvider.java:115)
        at qupath.lib.gui.QuPathGUI.openImage(QuPathGUI.java:2228)
        at qupath.lib.gui.viewer.DragDropFileImportListener.handleFileDrop(DragDropFileImportListener.java:253)
        at qupath.lib.gui.viewer.DragDropFileImportListener.handle(DragDropFileImportListener.java:115)
        at qupath.lib.gui.viewer.DragDropFileImportListener.handle(DragDropFileImportListener.java:59)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
        at javafx.event.Event.fireEvent(Event.java:198)
        at javafx.scene.Scene$DnDGesture.fireEvent(Scene.java:2933)
        at javafx.scene.Scene$DnDGesture.processTargetDrop(Scene.java:3159)
        at javafx.scene.Scene$DnDGesture.access$6400(Scene.java:2909)
        at javafx.scene.Scene$DropTargetListener.drop(Scene.java:2873)
        at com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.lambda$handleDragDrop$309(GlassSceneDnDEventHandler.java:95)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.handleDragDrop(GlassSceneDnDEventHandler.java:92)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleDragDrop$363(GlassViewEventHandler.java:700)
        at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleDragDrop(GlassViewEventHandler.java:699)
        at com.sun.glass.ui.View.handleDragDrop(View.java:712)
        at com.sun.glass.ui.View.notifyDragDrop(View.java:1037)
WARN: Error opening /Users/dzf/camelyon16-grand-challenge/data/TrainingData/Train_Tumor/Tumor_005.tif with ImageJ: Could not open /Users/dzf/camelyon16-grand-challenge/data/TrainingData/Train_Tumor/Tumor_005.tif with ImageJ
WARN: Unable to open /Users/dzf/camelyon16-grand-challenge/data/TrainingData/Train_Tumor/Tumor_005.tif with OpenSlide: /Users/dzf/camelyon16-grand-challenge/data/TrainingData/Train_Tumor/Tumor_005.tif: Not a file that OpenSlide can recognize
ERROR: Unable to build whole slide server - check your classpath for a suitable library (e.g. OpenSlide, BioFormats)
	
ERROR: /Applications/QuPath.app/Contents/Java/QuPathApp.jar:qupath/qupath-core-0.1.2.jar:qupath/qupath-core-awt-0.1.2.jar:qupath/qupath-core-processing-0.1.2.jar:qupath/qupath-core-processing-awt-0.1.2.jar:qupath/qupath-extension-ij-0.1.2.jar:qupath/qupath-extension-input-0.1.2.jar:qupath/qupath-extension-opencv-0.1.2.jar:qupath/qupath-extension-openslide-0.1.2.jar:qupath/qupath-extension-pen-0.1.2.jar:qupath/qupath-extension-script-editor-0.1.2.jar:qupath/qupath-gui-fx-0.1.2.jar:qupath/qupath-processing-ij-0.1.2.jar:qupath/qupath-processing-opencv-0.1.2.jar:jars/commons-math3-3.6.1.jar:jars/controlsfx-8.40.12.jar:jars/flowless-0.4.5.jar:jars/groovy-2.4.7.jar:jars/groovy-jsr223-2.4.7.jar:jars/gson-2.8.0.jar:jars/ij-1.51g.jar:jars/jfxtras-common-8.0-r5.jar:jars/jfxtras-menu-8.0-r5.jar:jars/jinput-2.0.6.jar:jars/jpen-2-150301.jar:jars/jutils-1.0.0.jar:jars/logback-classic-1.1.7.jar:jars/logback-core-1.1.7.jar:jars/opencv-3.1.0.jar:jars/openslide-3.4.1_2.jar:jars/packager.jar:jars/reactfx-2.0-M4u1.jar:jars/richtextfx-0.6.10.jar:jars/slf4j-api-1.7.20.jar:jars/undofx-1.2.jar:jars/wellbehavedfx-0.1.1.jar:QuPathApp.jar
ERROR: Open image: Sorry, I can't open /Users/dzf/camelyon16-grand-challenge/data/TrainingData/Train_Tumor/Tumor_005.tif

Thank you for your help!

**Comment by petebankhead** [comment]
Ah, my best guess was wrong.  But now that I know the image, I have tried it out... and it opens for me on my Mac, also 10.3.3, without problems (using OpenSlide).

Do all .tif whole slide images fail for you in QuPath?  Do any other formats work (e.g. SVS or NDPI - there are freely available test images on the OpenSlide website)?

A lot of that error message comes from the failed Bio-Formats attempt - you might want to remove or disable it since it didn't solve the problem.  But the log shows that OpenSlide was also tried without success.

**Comment by dzfowen** [comment]
I have tried .svs with 1.85M  and it works

**Comment by dzfowen** [comment]
<img width="706" alt="default" src="https://user-images.githubusercontent.com/3804756/37204061-c24f1e3e-23ca-11e8-92ed-3b5005c2e443.png">

this is my plugins

**Comment by petebankhead** [comment]
Under the *Image* tab does it say *OpenSlide* beside the entry *Server type*?  It might be using Bio-Formats or something else.  I'm curious as to whether OpenSlide is working for you at all.

Also, if you have OpenSlide installed some other way (e.g. with Python), can it read the file?

I know there can also be trouble if there are any non-English characters in the path to the file, but it doesn't look like the case from the log.

**Comment by dzfowen** [comment]
OK  when QuPath failed, I try to install Openslide independently, becauses my project needs.

I have installed openslide in \usr\local\Celluar

and openslide python interface by Anaconda in /anaconda/lib/python36


Thanks!

**Comment by dzfowen** [comment]
supplement :  it seems the size problem,  i can open tif with 120MB  but 1.4G can not.  Problem of plugin?

**Comment by petebankhead** [comment]
It shouldn't be file size.  Under *Help &rarr; Show setup options* I can restrict the RAM available to QUPath to 1GB and can still open the image without problems.  You can also try the memory monitor from https://petebankhead.github.io/qupath/scripting/2018/03/06/script-memory-monitor.html

The log says `Not a file that OpenSlide can recognize`.  It's not clear to me if *any* images are working for you using OpenSlide.

I asked above: under the *Image* tab does it say *OpenSlide* beside the entry *Server type*?  If you see that for any images, then we can conclude that OpenSlide is (at least partially) working.  But if you always see *ImageJ server* or *Bio-Formats server*, then it probably isn't and that's the problem that needs to be solved.

In that case, it would help to know if a separate installation of OpenSlide on your machine can read the image at all through any means.

**Comment by dzfowen** [comment]
But with a test.svs  1.8M  it works   strange!!!
OpenSlide('/Users/dzf/camelyon16-grand-challenge/data/TrainingData/Train_Tumor/test.svs')
OpenSlide('/Users/dzf/camelyon16-grand-challenge/data/TrainingData/Train_Tumor/test.svs')

**Comment by dzfowen** [comment]
I found  some data is broken  sorry
