### ISSUE TITLE
Questionable behavior with Delaunay cluster features

### ISSUE THREAD

**Issue by petebankhead** [qupath/qupath#1590]
## Bug report

**Describe the bug**
The behavior of *Analyze → Spatial analysis → Delaunay cluster features 2D* is not well-defined when applying the command to annotations that are nested (in the hierarchy) or overlapping.

For 'flat' annotation arrangements the behavior is *mostly ok*, except that it does rely on *hierarchy relationships* rather than *spatial relationships*.
Which is to say, it hasn't really changed since v0.1.2.

**To Reproduce**
Create an arrangement of objects similar to that shown below:

![0-orig](https://github.com/user-attachments/assets/cf1a87fc-c73a-4ac6-be24-d830f0014604)

1. If I run *Delaunay cluster features 2D* with **_all_ annotations selected**, I see triangulation lines which *do not cross the boundary between the annotations containing cells*.

![1-all selected](https://github.com/user-attachments/assets/3309e1e3-76ca-4ec7-bf5c-e0c76b8f2d96)

But I **also** get a `ConcurrentModificationException`:
```
15:47:01.829	[Plugin thread]	ERROR	qupath.lib.plugins.AbstractTaskRunner	Error running plugin: java.util.ConcurrentModificationException	java.util.concurrent.ExecutionException: java.util.ConcurrentModificationException
	at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
	at qupath.lib.plugins.AbstractTaskRunner.awaitCompletion(AbstractTaskRunner.java:147)
	at qupath.lib.plugins.AbstractTaskRunner.runTasks(AbstractTaskRunner.java:117)
	at qupath.lib.gui.TaskRunnerFX.runTasks(TaskRunnerFX.java:106)
	at qupath.lib.plugins.AbstractPlugin.runPlugin(AbstractPlugin.java:147)
	at qupath.lib.gui.ParameterDialogWrapper$1.run(ParameterDialogWrapper.java:177)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.util.ConcurrentModificationException
	at java.base/java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.base/java.util.ArrayList$Itr.next(Unknown Source)
	at java.base/java.util.Collections$UnmodifiableCollection$1.next(Unknown Source)
	at java.base/java.util.AbstractCollection.addAll(Unknown Source)
	at qupath.lib.objects.PathObjectTools.getAvailableFeatures(PathObjectTools.java:2026)
	at qupath.opencv.features.DelaunayTriangulation.<init>(DelaunayTriangulation.java:86)
	at qupath.opencv.features.DelaunayClusteringPlugin$DelaunayRunnable.run(DelaunayClusteringPlugin.java:208)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	... 1 more
```

2. If I repeat with **the outer rectangle selected**, then I *do* see connections.
This is because the triangulation uses *all descendant detections below the rectangle, based on the object hierarchy*.

![2-rectangle](https://github.com/user-attachments/assets/21b82d18-ce97-45c3-9644-7abdf85ab007)

3. If I repeat with **the outer ellipse selected**, I get *no connections at all*.
This is because the ellipse isn't set to be a parent of any of the other objects - this would change if I called *Resolve hierarchy* first.

![3-ellipse](https://github.com/user-attachments/assets/3c39bea5-9a9c-4ae3-bcc9-7ece1e8bae9c)

4. If I repeat with **the inner rectangles selected**, I get connections that don't cross *and I don't get any exception*.
This is because each cell is only handled once, so I don't get the concurrency trouble.

![4-inner rectangles](https://github.com/user-attachments/assets/74edf4a3-05c0-49ea-bd38-f82d327d9564)

5. If I repeat with **only 1 inner rectangle selected**, I get connections within that rectangle only.

![5-single rectangle](https://github.com/user-attachments/assets/492cf523-c58d-4b48-b417-ac44662a7a5a)

**Expected behavior**
This isn't obvious... Nevertheless:
1. The `ConcurrentModificationException` is clearly bad. But it's also kind of helpful here, because 2. and 4. give different results... and when that's the case, if we select all the annotations in 2. and 4. in one go, it's not obvious what *should* happen.
2. The reliance on hierarchical relationships may not be very intuitive to a user, since measurements like 'Positive %' are dynamically computed using spatial location relative to any selected annotation - not hierarchical relationships.

**Desktop (please complete the following information):**
 - OS: All
 - QuPath Version: v0.5.1 (and earlier)

**Additional context**
This relates to:
* #1444
* #1466

The behavior of *Delaunay cluster features 2D* is *in general* not very good for more reasons than these.

For example, the display of the connection lines is already a bit of a hack (smuggled into `ImageData` properties) - and showing/hiding these can be unreliable.

But fixing #1466 risks swallowing the `ConcurrentModificationException`, meaning we get unexpected results rather than an exception - which is potentially worse.

**Comment by alanocallaghan** [comment]
1 is clearly wrong to me; should probably be equivalent to selecting the outer rectangle, and definitely not throw a concurrent exception (whether or not it throws another exception, or a warning about undefined behaviour is another question).

I think as much as it may not be intuitive, using the object hierarchy here is more flexible (ie, there may be situations where this is what people want to do, and as long as it's possible to toggle between, I tend to prefer flexibility).

I can't decide if I should expect connections between disjoint annotations when both are selected. I think.... no...?

**Comment by petebankhead** [comment]
Thanks for this, what do think of https://github.com/qupath/qupath/pull/1597 ?

I think it's a better starting point for any kind of Delaunay command, and I'd like to deprecate this one - but the PR doesn't bother with any actual measurements yet, and I'm not sure if it's too soon to introduce it with an easy toolbar button.

**Comment by alanocallaghan** [comment]
I had a look over that (how I found this issue), can't really comment on implementation of either at the moment as it's a bit over my head, but it does seem a bit more idiomatic and should have the flexibility to support all of the use cases here with sufficient pre-/post-processing (albeith, this could get quite labourious for some applications)
