### ISSUE TITLE
MeasurementList is not fully thread-safe

### ISSUE THREAD

**Issue by petebankhead** [qupath/qupath#1591]
## Bug report

**Describe the bug**
In some circumstances, a `ConcurrentModificationException` can be thrown when working with measurement lists in parallel threads.

A related issue is reported at https://github.com/qupath/qupath/pull/1466 but the proposed fix does not solve the problem here.

**To Reproduce**
Try running the script below:
```groovy
// A growing list of objects
def pathObjects = Collections.synchronizedList([])

// Number of iterations
int n = 1000

// Create a thread to continually request all measurement names
def t = new Thread( {
    while (pathObjects.size() < n) {
        def list = PathObjectTools.getAvailableFeatures(new ArrayList<>(pathObjects))
    }
})
t.start()

// Create a parallel stream to add new objects
java.util.stream.IntStream.range(0, n)
    .parallel()
    .forEach(i -> {
        // This happens only with detections!
        def pathObject = PathObjects.createDetectionObject(ROIs.createEmptyROI())
        pathObjects << pathObject
        for (int k = 0; k <= i; k++)
            pathObject.measurementList.put("M_$k", i)
})
t.join()
    
println "Done!"
```

I see an exception
```
ERROR: null
java.util.ConcurrentModificationException: null
    at java.base/java.util.ArrayList$Itr.checkForComodification(Unknown Source)
    at java.base/java.util.ArrayList$Itr.next(Unknown Source)
    at java.base/java.util.Collections$UnmodifiableCollection$1.next(Unknown Source)
    at java.base/java.util.AbstractCollection.addAll(Unknown Source)
    at qupath.lib.objects.PathObjectTools.getAvailableFeatures(PathObjectTools.java:2026)
    at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
    at QuPathScript$_run_closure1.doCall(QuPathScript:11)
    at QuPathScript$_run_closure1.doCall(QuPathScript)
    at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
    at java.base/java.lang.reflect.Method.invoke(Unknown Source)
    at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:343)
    at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:328)
    at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:279)
    at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1008)
    at groovy.lang.Closure.call(Closure.java:433)
    at groovy.lang.Closure.call(Closure.java:412)
    at groovy.lang.Closure.run(Closure.java:505)
    at java.base/java.lang.Thread.run(Unknown Source)
```

**Expected behavior**
The code runs without any exception.

**Desktop (please complete the following information):**
 - OS: macOS (but probably all)
 - QuPath Version: v0.5.1

**Additional context**
This seems to only occur with detections.

The underlying issue in this specific case seems to be that these can return an unmodifiable list of measurement names, but when this is used by `PathObjectTools.getAvailableFeatures(Collection)` the underlying list is being modified.

A fix may require revising `MeasurementList` more thoroughly to improve its robustness.

> Edit: The original 'failing' script I posted here was failing because `pathObjects` was being modified... the version after I ended the issue fails in the 'right' place to show the issue I was trying to report.

**Comment by petebankhead** [comment]
Should be fixed by #1592
