### ISSUE TITLE
loading classifier error

### ISSUE THREAD

**Issue by camlcg** [qupath/qupath#160]
Hi,

I'm getting an error when loading my classifier, which has previously been working absolutely fine. I am able to bypass the issue on closing and reopening the file. This has been happening for 2 days. I have copied and pasted the classifier for my colleague to use, however she's now getting the same error but it won't resolve for her on reopening the file. Is there something we're doing wrong or is this a software problem? Can you let me know how I can fix it/when the issue will be resolved?

Thanks,

Cam

The error message is as follows:
INFO: Selected style: Modena Light
INFO: Performing update check...
INFO: Starting QuPath with parameters: [N:\Faculty-of-Medicine-and-Health\LICAP\DATA\PTHY\Pathology\Breast Group\BCCTB Samples\Audits\BCN QA 2017\Frozen samples QuPath tumourstromaratio\Batch_2\Tumour\402428.svs]
INFO: Test reading thumbnail with openslide: passed (BufferedImage@5d207157: type = 1 DirectColorModel: rmask=ff0000 gmask=ff00 bmask=ff amask=0 IntegerInterleavedRaster: width = 193 height = 200 #Bands = 3 xOff = 0 yOff = 0 dataOffset[0] 0)
INFO: Returning server: OpenSlide for N:\Faculty-of-Medicine-and-Health\LICAP\DATA\PTHY\Pathology\Breast Group\BCCTB Samples\Audits\BCN QA 2017\Frozen samples QuPath tumourstromaratio\Batch_2\Tumour\402428.svs
INFO: Estimating H & E staining
INFO: Image data set to ImageData: Brightfield (H&E), 402428
INFO: 1 region detected (processing time: 215.44 seconds)
INFO: Processing complete in 215.63 seconds
INFO: Completed!
INFO: 
qupath.imagej.detect.tissue.SimpleTissueDetection2  {"threshold": 219,  "requestedPixelSizeMicrons": 2.0,  "minAreaMicrons": 20.0,  "maxHoleAreaMicrons": 200.0,  "darkBackground": false,  "smoothImage": true,  "medianCleanup": true,  "dilateBoundaries": false,  "smoothCoordinates": true,  "excludeOnBoundary": false,  "singleAnnotation": true}
INFO: Adding Area (AWT) to hierarchy
INFO: Adding Area (AWT) to hierarchy
INFO: Adding Area (AWT) to hierarchy
INFO: Adding Area (AWT) to hierarchy
INFO: Adding Area (AWT) to hierarchy
INFO: Adding Area (AWT) to hierarchy
INFO: Adding Area (AWT) to hierarchy
INFO: Adding Area (AWT) to hierarchy
INFO: Adding Area (AWT) to hierarchy
INFO: Adding Area (AWT) to hierarchy
INFO: 271 nuclei detected (processing time: 5.71 seconds)
INFO: 233 nuclei detected (processing time: 5.78 seconds)
INFO: 0 nuclei detected (processing time: 0.23 seconds)
INFO: 872 nuclei detected (processing time: 6.63 seconds)
INFO: 1695 nuclei detected (processing time: 9.49 seconds)
INFO: 1145 nuclei detected (processing time: 10.39 seconds)
INFO: 3294 nuclei detected (processing time: 11.72 seconds)
INFO: 1267 nuclei detected (processing time: 12.33 seconds)
INFO: 470 nuclei detected (processing time: 6.69 seconds)
INFO: 4076 nuclei detected (processing time: 13.59 seconds)
INFO: 0 nuclei detected (processing time: 1.42 seconds)
INFO: 394 nuclei detected (processing time: 3.38 seconds)
INFO: 510 nuclei detected (processing time: 8.89 seconds)
INFO: 2086 nuclei detected (processing time: 8.28 seconds)
INFO: 1500 nuclei detected (processing time: 14.11 seconds)
INFO: 0 nuclei detected (processing time: 0.17 seconds)
INFO: 2245 nuclei detected (processing time: 12.13 seconds)
INFO: 3727 nuclei detected (processing time: 15.92 seconds)
INFO: 490 nuclei detected (processing time: 5.58 seconds)
INFO: 125 nuclei detected (processing time: 1.06 seconds)
INFO: 509 nuclei detected (processing time: 12.45 seconds)
INFO: 2235 nuclei detected (processing time: 12.80 seconds)
INFO: 681 nuclei detected (processing time: 6.41 seconds)
INFO: 2 nuclei detected (processing time: 0.47 seconds)
INFO: 1697 nuclei detected (processing time: 11.44 seconds)
INFO: 379 nuclei detected (processing time: 5.13 seconds)
INFO: 721 nuclei detected (processing time: 8.30 seconds)
INFO: 364 nuclei detected (processing time: 6.80 seconds)
INFO: 157 nuclei detected (processing time: 4.19 seconds)
INFO: 521 nuclei detected (processing time: 5.53 seconds)
INFO: Processing complete in 34.91 seconds
INFO: Completed!
INFO: 
qupath.imagej.detect.nuclei.WatershedCellDetection  {"detectionImageBrightfield": "Hematoxylin OD",  "requestedPixelSizeMicrons": 0.5,  "backgroundRadiusMicrons": 8.0,  "medianRadiusMicrons": 0.0,  "sigmaMicrons": 1.5,  "minAreaMicrons": 10.0,  "maxAreaMicrons": 400.0,  "threshold": 0.1,  "maxBackground": 2.0,  "watershedPostProcess": true,  "cellExpansionMicrons": 5.0,  "includeNuclei": true,  "smoothBoundaries": true,  "makeMeasurements": true}
INFO: Writing object hierarchy with 29994 object(s)...
INFO: Image data written to N:\Faculty-of-Medicine-and-Health\LICAP\DATA\PTHY\Pathology\Breast Group\BCCTB Samples\Audits\BCN QA 2017\Frozen samples QuPath tumourstromaratio\Batch_2\Tumour\402428.qpdata in 2.08 seconds
INFO: Training size: 33x5031
INFO: Responses size: 1x5031
INFO: RTrees classifier termination criteria: { type: 1, maxCount: 50, epsilon: 0.0}
ERROR: QuPath exception
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:416)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:415)
    at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
    at com.sun.glass.ui.View.notifyMouse(View.java:937)
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
    at java.lang.Thread.run(Thread.java:745)
  Caused by std::exception: bad allocation        at org.opencv.ml.StatModel.train_0(Native Method)
        at org.opencv.ml.StatModel.train(StatModel.java:74)
        at qupath.opencv.classify.OpenCvClassifier.createAndTrainClassifier(OpenCvClassifier.java:250)
        at qupath.opencv.classify.ParameterizableOpenCvClassifier.createAndTrainClassifier(ParameterizableOpenCvClassifier.java:84)
        at qupath.opencv.classify.OpenCvClassifier.readExternal(OpenCvClassifier.java:506)
        at qupath.opencv.classify.ParameterizableOpenCvClassifier.readExternal(ParameterizableOpenCvClassifier.java:102)
        at java.io.ObjectInputStream.readExternalData(ObjectInputStream.java:1849)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1806)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
        at qupath.lib.classifiers.PathClassifierTools.loadClassifier(PathClassifierTools.java:86)
        at qupath.lib.gui.panels.classify.PathClassifierPanel.lambda$new$0(PathClassifierPanel.java:80)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
        at javafx.event.Event.fireEvent(Event.java:198)
        at javafx.scene.Node.fireEvent(Node.java:8413)
        at javafx.scene.control.Button.fire(Button.java:185)
        at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:182)
        at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:96)
        at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:89)
        at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
        at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
        at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
        at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
        at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
        at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
        at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
        at javafx.event.Event.fireEvent(Event.java:198)
        at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
        at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
        at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
        at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:380)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:294)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:416)
        at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
        at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:415)
        at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
        at com.sun.glass.ui.View.notifyMouse(View.java:937)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
        at java.lang.Thread.run(Thread.java:745)

**Comment by Svidro** [comment]
I know there are some updates to how OpenCV operates with the newest version of QuPath.  Are you running that one or the older 1.2? (I don't know that it is entirely official yet, but you can find it here https://petebankhead.github.io/qupath/2018/03/19/qupath-updates.html)

I don't have anything immediately useful, just wanting to check which version the error is happening in!

**Comment by camlcg** [comment]
We are both running version 0.1.2

**Comment by petebankhead** [comment]
I don't know, I haven't seen this problem before - and if nothing has changed in the meantime, I see no reason why the classifier wouldn't work.  The updates mentioned above shouldn't affect this (more accurately, the updates that *might* affect it aren't available there yet).

When you say you copied and pasted the classifier, I guess you mean the whole file through Windows Explorer?

Do you have any more luck if you try running it from a different location, e.g. copy it to the Desktop and try from there?

If you are able to send me the `.qpclassifier` file then I can investigate some more.  If there isn't a way for you to upload it here and you haven't already got my email address from somewhere, then if you sign up to the [QuPath user forum on Google Groups](https://groups.google.com/forum/#!forum/qupath-users) I can contact you directly.

**Comment by camlcg** [comment]
I originally saved the classifier in a shared folder on our work network.. my colleague and I both copied and pasted the file from there onto our desktops (to make it faster to locate when loading it through QuPath). I've had no problems with it at all prior to this week! My colleague has now left but I'll ask her to try it from the shared folder tomorrow and see if that fixes the issue. I've just tried loading it from the original folder but having the same issue fixable by closing and reopening. 

The error message that pops up says: 'QuPath has encountered a problem, sorry. If you can replicate it, please notify a developer.

java.security.PrivelegedActionException: java.lang.Exception: std::exception: bad allocation'

Thanks both for your help! Pete I will email you the qpclassifier file now.

**Comment by camlcg** [comment]
Hi Pete,

I’ve attached the classifier file.

Thanks very much for your help,

Cam

**Comment by petebankhead** [comment]
I understand this has now been resolved, and it seems to have been an issue of file permissions outside of QuPath.  I'll close the issue - please reopen if anything new emerges.
