### ISSUE TITLE
Cannot make DJL pytorch work for instanseg

### ISSUE THREAD

**Issue by GXcells** [qupath/qupath#1636]
I cannot make pytorch work.

I tried also with a conda env but nothing works. Even if I just select CPU in Instantseg, it tries to load the cuda version. Problem is that it detects cuda 12.1 so maybe it does not even want to try to load the CPU version?

`Failed to load PyTorch native library
ai.djl.engine.EngineException: Failed to load PyTorch native library
	at ai.djl.pytorch.engine.PtEngine.newInstance(PtEngine.java:90)
	at ai.djl.pytorch.engine.PtEngineProvider.getEngine(PtEngineProvider.java:41)
	at ai.djl.engine.Engine.getEngine(Engine.java:190)
	at qupath.ext.instanseg.core.PytorchManager.lambda$getEngineOnline$0(PytorchManager.java:28)
	at qupath.ext.instanseg.core.PytorchManager.callWithTempProperty(PytorchManager.java:114)
	at qupath.ext.instanseg.core.PytorchManager.callOnline(PytorchManager.java:106)
	at qupath.ext.instanseg.core.PytorchManager.getEngineOnline(PytorchManager.java:28)
	at qupath.ext.instanseg.ui.InstanSegController.downloadPyTorch(InstanSegController.java:826)
	at qupath.ext.instanseg.ui.InstanSegController.ensurePyTorchAvailable(InstanSegController.java:815)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\username\.djl.ai\pytorch\2.3.1-cu121-win-x86_64\cudnn_cnn_infer64_8.dll: The specified procedure could not be found
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(Unknown Source)
	at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
	at java.base/java.lang.Runtime.load0(Unknown Source)
	at java.base/java.lang.System.load(Unknown Source)
	at ai.djl.pytorch.jni.LibUtils.loadNativeLibrary(LibUtils.java:379)
	at ai.djl.pytorch.jni.LibUtils.loadLibTorch(LibUtils.java:176)
	at ai.djl.pytorch.jni.LibUtils.loadLibrary(LibUtils.java:82)
	at ai.djl.pytorch.engine.PtEngine.newInstance(PtEngine.java:53)
	... 15 more`

**Comment by petebankhead** [comment]
This relates to https://github.com/qupath/qupath/issues/1634

Because CUDA detection and PyTorch downloading is all performed by DeepJavaLibrary, we are very limited in what we can do on the QuPath side.

Then there is the issue of how Java loads native library dependencies - and especially the platform-specific fun of how *sub*-dependencies are handled. And the potential interference of environment variables or other things that could be installed. It is, in short, hard.

The page on the docs is currently our best 'general' approach to help with this, based on many hours trying to find something workable across computers: https://qupath.readthedocs.io/en/stable/docs/deep/gpu.html#gpu-support

We will continue to try to improve this, but I'll close the issue because I don't think there is any clearly-defined QuPath bug here that we can address.

To try to avoid fragmenting the discussion in multiple places, I suggest posting on the forum. There are more users active on the forum who might potentially be able to help from their own experience, and there are already some related discussions, e.g. https://forum.image.sc/search?q=qupath%20gpu%20order%3Alatest
