### ISSUE TITLE
.scn files error 

### ISSUE THREAD

**Issue by KPink2016** [qupath/qupath#184]
Hi! I keep trying to open .scn files on the QuPath but I keep getting these two error messages...

ERROR: Checking Big TIFF images currently not supported!!!
WARN: Error opening /Users/katherinepinkerton/Desktop/SheLab/Purohit IL1RA Mouse Pancreas/5751 Pancreas.SCN with ImageJ: Could not open /Users/katherinepinkerton/Desktop/SheLab/Purohit IL1RA Mouse Pancreas/5751 Pancreas.SCN with ImageJ
WARN: Unable to open /Users/katherinepinkerton/Desktop/SheLab/Purohit IL1RA Mouse Pancreas/5751 Pancreas.SCN with OpenSlide: Slides with dissimilar main images are not supported
ERROR: No image server provider found for /Users/katherinepinkerton/Desktop/SheLab/Purohit IL1RA Mouse Pancreas/5751 Pancreas.SCN
ERROR: Project: Import images: TextArea@40ec1c06[styleClass=text-input text-area]
INFO: Unable to import 1 paths:
	/Users/katherinepinkerton/Desktop/SheLab/Purohit IL1RA Mouse Pancreas/5751 Pancreas.SCN

ERROR: QuPath exception
    at javafx.scene.Scene$ScenePeerListener.scrollEvent(Scene.java:2556)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$null$369(GlassViewEventHandler.java:899)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleScrollGestureEvent$370(GlassViewEventHandler.java:881)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleScrollGestureEvent(GlassViewEventHandler.java:880)
    at com.sun.glass.ui.View.handleScrollGestureEvent(View.java:597)
    at com.sun.glass.ui.View.notifyScrollGestureEvent(View.java:1064)
    at com.sun.glass.ui.GestureSupport.handleScrollingEnd(GestureSupport.java:140)
    at com.sun.glass.ui.GestureSupport.lambda$createTouchCountListener$41(GestureSupport.java:379)
    at com.sun.glass.ui.TouchInputSupport.notifyEndTouchEvent(TouchInputSupport.java:115)
    at com.sun.glass.ui.mac.MacTouchInputSupport.notifyEndTouchEvent(MacTouchInputSupport.java:93)
    at com.sun.glass.ui.mac.MacGestureSupport.notifyEndTouchEvent(MacGestureSupport.java:81)

I have no idea what to do please help :-(

**Comment by petebankhead** [comment]
The main part of the error message is from OpenSlide, saying
```
Slides with dissimilar main images are not supported
```

You could try installing the [Bio-Formats extension](https://github.com/qupath/qupath-bioformats-extension) to see if that works for your images.

There is more information on the [Supported image formats](https://github.com/qupath/qupath/wiki/Supported-image-formats) page of the wiki.
