### ISSUE TITLE
Java Heap Space

### ISSUE THREAD

**Issue by HaisenWang** [qupath/qupath#195]
When i try to open a .tif file exported from a .mds file by a software, the error "Java Heap Space" occurs. Here is the log.
`
WARN: Unable to open C:\Users\QQ\Desktop\1.mds.tif with OpenSlide: C:\Users\QQ\Desktop\1.mds.tif: Not a file that OpenSlide can recognize
WARN: QuPath Bio-Formats extension is in beta!  Be watchful for bugs...
INFO: Generating memoization file C:\Users\QQ\Desktop\.1.mds.tif.bfmemo (0.24 MB)
WARN: Cannot open C:\Users\QQ\Desktop\1.mds.tif with qupath.lib.images.servers.BioFormatsServerBuilder@6bb485b6 - image size too large (2453.678853034973 MB)
ERROR: QuPath exception
    at ij.io.ImageReader.readCompressedChunkyRGB(ImageReader.java:443)
    at ij.io.ImageReader.readChunkyRGB(ImageReader.java:368)
    at ij.io.ImageReader.readPixels(ImageReader.java:808)
    at ij.io.FileOpener.readPixels(FileOpener.java:511)
    at ij.io.FileOpener.open(FileOpener.java:104)
    at ij.io.FileOpener.openImage(FileOpener.java:51)
    at ij.plugin.FileInfoVirtualStack.open(FileInfoVirtualStack.java:105)
    at ij.plugin.FileInfoVirtualStack.openVirtual(FileInfoVirtualStack.java:50)
    at ij.IJ.openVirtual(IJ.java:1672)
    at qupath.imagej.images.servers.ImageJServer.<init>(ImageJServer.java:90)
    at qupath.imagej.images.servers.ImageJServerBuilder.buildServer(ImageJServerBuilder.java:49)
    at qupath.lib.images.servers.ImageServerProvider.buildServer(ImageServerProvider.java:115)
    at qupath.lib.gui.QuPathGUI.openImage(QuPathGUI.java:2228)
    at qupath.lib.gui.QuPathGUI.openImage(QuPathGUI.java:2152)
    at qupath.lib.gui.commands.OpenCommand.run(OpenCommand.java:51)
    at qupath.lib.gui.QuPathGUI.lambda$createCommandAction$46(QuPathGUI.java:3122)
    at qupath.lib.gui.QuPathGUI$$Lambda$89/1768947243.accept(Unknown Source)
    at org.controlsfx.control.action.Action.handle(Action.java:419)
    at org.controlsfx.control.action.Action.handle(Action.java:64)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.control.MenuItem.fire(MenuItem.java:462)
    at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1405)
    at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.lambda$createChildren$343(ContextMenuContent.java:1358)
    at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer$$Lambda$633/980982656.handle(Unknown Source)
    at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
`

**Comment by petebankhead** [comment]
The error includes `image size too large (2453.678853034973 MB)`

My guess is that the exported TIFF isn't a pyramidal TIFF, and this may be why QuPath + Bio-Formats needs to resort to reading it in one go - and too much memory is required for that to be possible.

I'm not familiar with `.mds` - I don't suppose it works directly, or do you have any alternative options to export the image?

**Comment by petebankhead** [comment]
You could try converting your existing TIFF into a pyramidal one - there are some suggestions at https://github.com/openslide/openslide/wiki/CreatingPyramidalTIFFs

Please let me know if you find this works - I haven't tried it myself yet.

There are also tips for adjusting the memory settings [here](https://github.com/qupath/qupath/wiki/Troubleshooting#setting-memory-limits), but QuPath is really only optimized for large 2D images if they are in a pyramidal format. Assuming this one isn't, even if the image _could_ be opened the performance is likely to be bad.

**Comment by HaisenWang** [comment]
Thanks a lot ! It really works! I download the VIPS , use it convert my TIFF to pyramidal TIFF, and then the Qupath can open it with no problems. Thanks again for your help!

**Comment by petebankhead** [comment]
Great, thanks for letting me know!
