### ISSUE TITLE
export snapshot 

### ISSUE THREAD

**Issue by situbimo** [qupath/qupath#216]
hi!
How do I export an analyzed image ("export snapshot ->Viewer snapshot") via a groovy script?
How can I do this? Sorry to bother you and thank you if you can help.

**Comment by petebankhead** [comment]
There are lots of possible export options and discussions, but I'm not sure if they match exactly what you want.  Here are some:
* https://groups.google.com/d/msg/qupath-users/Anci7FBEHQg/XcGFJcfGAQAJ
* https://petebankhead.github.io/qupath/scripting/2018/03/13/script-export-import-binary-masks.html
* https://petebankhead.github.io/qupath/scripting/2018/03/14/script-export-labelled-images.html
* https://groups.google.com/forum/#!topic/qupath-users/ub6TC9IMmZ8

None of them are quite the same as the _Viewer snapshot_, but then the output of this would depend on the current magnification, window size etc. and so you would lose some control in the script concerning what is actually exported (unless you also programmatically modify the viewer...).  Therefore in scripts I tend to export overview images using a different approach from the viewer snapshot directly.

If the above links don't help, could you describe more what exactly you want to export, and how it should look?

**Comment by situbimo** [comment]
![358](https://user-images.githubusercontent.com/20010640/45362141-96270a00-b606-11e8-9d6f-c5318ebbcae7.JPG)
![snapshot](https://user-images.githubusercontent.com/20010640/45362149-9de6ae80-b606-11e8-8305-1570a3297ab9.png)


 image：358.JPG
Analyzed image:snapshot.png
I want to export the analyzed image through a script.

**Comment by situbimo** [comment]
There are many problems with groovy script processing, so I read the source code of the qupath software. And call the java interface to process the image. I want to save the analyzed image, but I failed, I don't know how to deal with this problem, so I hope to get your help.
-------------------------------
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.util.Hashtable;
import java.util.SortedMap;

import javax.imageio.spi.ImageWriterSpi;

import org.controlsfx.control.SnapshotView;

import ij.plugin.JpegWriter;
import javafx.scene.SnapshotResult;
import qupath.lib.gui.ImageWriterTools;
import qupath.lib.gui.QuPathGUI;
import qupath.lib.gui.commands.SaveViewCommand;
import qupath.lib.gui.prefs.PathPrefs;
import qupath.lib.images.ImageData;
import qupath.lib.images.servers.ImageServer;
import qupath.lib.images.servers.ImageServerProvider;
import qupath.lib.io.ImageWriter;
import qupath.lib.regions.RegionRequest;
import qupath.lib.roi.interfaces.ROI;
import qupath.lib.scripting.QP;
import qupath.lib.scripting.QPEx;

public class test01 {
	private static QuPathGUI qupath;
	private static boolean wholeWindow;
	
	public void mydetection() throws InterruptedException {
		// TODO Auto-generated method stub
		String imagePath="D:\\Overview\\9624CE91-1DA8-40AE-89AC-41412BE756DB.jpg";
		ImageServer<BufferedImage> server = ImageServerProvider.buildServer(imagePath, BufferedImage.class);
		ImageData imageData = new ImageData<>(server);
		String bind = "{\"threshold\": 162,  \"requestedDownsample\": 1.0,  \"minAreaPixels\": 100000.0,  \"maxHoleAreaPixels\": 500.0,  \"darkBackground\": false,  \"smoothImage\": true,  \"medianCleanup\": true,  \"dilateBoundaries\": false, \r\n" + 
				" \"smoothCoordinates\": true,  \"excludeOnBoundary\": false,  \"singleAnnotation\": true}');";
		boolean detection = false;
		try {
			detection = QP.runPlugin("qupath.imagej.detect.tissue.SimpleTissueDetection2",bind);
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		int x = 0,y = 0;
		int width=server.getWidth(),height = server.getHeight();
		RegionRequest request = RegionRequest.createInstance(imageData.getServerPath(),1, x, y, width, height);
		System.out.println(imageData.getServerPath());
		ImageWriterTools.writeImageRegion(server, request,"d:/out-detection01.png");
	}
	
	
	public static void main(String[] args) throws InterruptedException, IOException {
		test01 t = new test01();
		t.mydetection();
	}

}

**Comment by situbimo** [comment]
I am running the groovy script in qupath as follows, but the saved image is the original image instead of the analyzed image.

import qupath.lib.gui.ImageWriterTools
import qupath.lib.regions.RegionRequest
import qupath.lib.scripting.QPEx

def imageData = QPEx.getCurrentImageData()
def server = imageData.getServer()
def filename = server.getShortServerName()

setImageType('BRIGHTFIELD_H_DAB');
setColorDeconvolutionStains('{"Name" : "H-DAB default", "Stain 1" : "Hematoxylin", "Values 1" : "0.65111 0.70119 0.29049 ", "Stain 2" : "DAB", "Values 2" : "0.26917 0.56824 0.77759 ", "Background" : " 255 255 255 "}');
runPlugin('qupath.imagej.detect.tissue.SimpleTissueDetection2', '{"threshold": 162,  "requestedDownsample": 1.0,  "minAreaPixels": 100000.0,  "maxHoleAreaPixels": 500.0,  "darkBackground": false,  "smoothImage": true,  "medianCleanup": true,  "dilateBoundaries": false, "smoothCoordinates": true,  "excludeOnBoundary": false,  "singleAnnotation": true}');
int x = 0,y = 0;
int width=server.getWidth(),height = server.getHeight();
def request = RegionRequest.createInstance(imageData.getServerPath(),1, x, y, width, height);
ImageWriterTools.writeImageRegion(server, request,"d:/snapshot.png");

**Comment by petebankhead** [comment]
Yes, that is correct.  Assuming you want to see what was detected, you'll need to use `writeImageRegionWithOverlay`.  There's an example at https://gist.github.com/petebankhead/66e70e5deaa9c6e6a009ad027b135a0d

**Comment by situbimo** [comment]
Thank you for your reference, but I have some problems when I run it.
----------------------------------------------------------------------
import qupath.lib.gui.ImageWriterTools
import qupath.lib.gui.QuPathGUI
import qupath.lib.gui.viewer.OverlayOptions
import qupath.lib.regions.RegionRequest
import qupath.lib.scripting.QPEx

// Aim for an output resolution of approx 20 µm/pixel
double requestedPixelSize = 20

// Create the output directory, if required
def path = QPEx.buildFilePath(QPEx.PROJECT_BASE_DIR, "export")
QPEx.mkdirs(path)

// Get the imageData & server
def imageData = QPEx.getCurrentImageData()
def server = imageData.getServer()
setImageType('BRIGHTFIELD_H_DAB');
setColorDeconvolutionStains('{"Name" : "H-DAB default", "Stain 1" : "Hematoxylin", "Values 1" : "0.65111 0.70119 0.29049 ", "Stain 2" : "DAB", "Values 2" : "0.26917 0.56824 0.77759 ", "Background" : " 255 255 255 "}');
runPlugin('qupath.imagej.detect.tissue.SimpleTissueDetection2', '{"threshold": 162,  "requestedDownsample": 1.0,  "minAreaPixels": 100000.0,  "maxHoleAreaPixels": 500.0,  "darkBackground": false,  "smoothImage": true,  "medianCleanup": true,  "dilateBoundaries": false, "smoothCoordinates": true,  "excludeOnBoundary": false,  "singleAnnotation": true}');

// Get the file name from the current server
def name = server.getShortServerName()

// We need to get the display settings (colors, line thicknesses, opacity etc.) from the current viewer, if available
def overlayOptions = QuPathGUI.getInstance() == null ? new OverlayOptions() : QuPathGUI.getInstance().getViewer().getOverlayOptions()

// Calculate downsample factor depending on the requested pixel size
double downsample = requestedPixelSize / server.getAveragedPixelSizeMicrons()
def request = RegionRequest.createInstance(imageData.getServerPath(), downsample, 0, 0, server.getWidth(), server.getHeight())

// Write output image, with and without overlay
def dir = new File(path)
def fileImage = new File(dir, name + ".jpg")
def img = ImageWriterTools.writeImageRegion(server, request, fileImage.getAbsolutePath())
def fileImageWithOverlay = new File(dir, name + "-overlay.jpg")
ImageWriterTools.writeImageRegionWithOverlay(img, imageData, overlayOptions, request, fileImageWithOverlay.getAbsolutePath())
----------------------------------------------------------------------
WARN: Invalid requested downsample 1.0 - will use 1.057 instead
INFO: 1 region detected (processing time: 2.97 seconds)
INFO: Processing complete in 3.06 seconds
INFO: Completed!
INFO: 
qupath.imagej.detect.tissue.SimpleTissueDetection2  {"threshold": 162,  "requestedDownsample": 1.0,  "minAreaPixels": 100000.0,  "maxHoleAreaPixels": 500.0,  "darkBackground": false,  "smoothImage": true,  "medianCleanup": true,  "dilateBoundaries": false, "smoothCoordinates": true,  "excludeOnBoundary": false,  "singleAnnotation": true}
ERROR: Error writing D:\image-project\export\358.jpg with JPEG
ERROR: Unable to write D:\image-project\export\358.jpg!  No compatible writer found.

**Comment by petebankhead** [comment]
It works for me, but perhaps the image you are trying to export is too large / lacks pixel size information, resulting in the image not being downsampled enough?

You could try replacing the line
```groovy
double downsample = requestedPixelSize / server.getAveragedPixelSizeMicrons()
```
with
```groovy
double downsample = 10
```
or a higher value to specify that the image should be downsampled.  Or try using one of the whole slide images from the early stages of the Wiki, where there are step-by-step guides.

Otherwise, if you are able to attach your original image then I can try replicating your issue exactly - but for the images I've tried it works.

> It's also quite hard to read your code with the different font size/bold formatting - you can format code by enclosing it as follows:
> ```groovy
>        ```groovy
>        // Code here
>        ```
> ```
> See https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by situbimo** [comment]
Thank you very much for your help, the problem has been solved.

**Comment by situbimo** [comment]
hi,
I can run groovy scripts in qupath, but I will run an exception when running groovy scripts in linux.
----------------------------------------------------------
java -cp /oamp/bio/QuPath/0.1.2/qupath-0.1.2/deploy/qupath/qupath-core-0.1.2.jar:/oamp/bio/QuPath/0.1.2/qupath-0.1.2/deploy/qupath/qupath-core-awt-0.1.2.jar:/oamp/bio/QuPath/0.1.2/qupath-0.1.2/deploy/qupath/qupath-core-processing-0.1.2.jar:/oamp/bio/QuPath/0.1.2/qupath-0.1.2/deploy/qupath/qupath-core-processing-awt-0.1.2.jar:/oamp/bio/QuPath/0.1.2/qupath-0.1.2/deploy/qupath/qupath-extension-ij-0.1.2.jar:/oamp/bio/QuPath/0.1.2/qupath-0.1.2/deploy/qupath/qupath-extension-input-0.1.2.jar:/oamp/bio/QuPath/0.1.2/qupath-0.1.2/deploy/qupath/qupath-extension-opencv-0.1.2.jar:/oamp/bio/QuPath/0.1.2/qupath-0.1.2/deploy/qupath/qupath-extension-openslide-0.1.2.jar:/oamp/bio/QuPath/0.1.2/qupath-0.1.2/deploy/qupath/qupath-extension-pen-0.1.2.jar:/oamp/bio/QuPath/0.1.2/qupath-0.1.2/deploy/qupath/qupath-extension-script-editor-0.1.2.jar:/oamp/bio/QuPath/0.1.2/qupath-0.1.2/deploy/qupath/qupath-gui-fx-0.1.2.jar:/oamp/bio/QuPath/0.1.2/qupath-0.1.2/deploy/qupath/qupath-processing-ij-0.1.2.jar:/oamp/bio/QuPath/0.1.2/qupath-0.1.2/deploy/qupath/qupath-processing-opencv-0.1.2.jar:/oamp/bio/QuPath/0.1.2/qupath-0.1.2/deploy/jars/commons-math3-3.6.1.jar:/oamp/bio/QuPath/0.1.2/qupath-0.1.2/deploy/jars/controlsfx-8.40.12.jar:/oamp/bio/QuPath/0.1.2/qupath-0.1.2/deploy/jars/flowless-0.4.5.jar:/oamp/bio/QuPath/0.1.2/qupath-0.1.2/deploy/jars/groovy-2.4.7.jar:/oamp/bio/QuPath/0.1.2/qupath-0.1.2/deploy/jars/groovy-jsr223-2.4.7.jar:/oamp/bio/QuPath/0.1.2/qupath-0.1.2/deploy/jars/gson-2.8.0.jar:/oamp/bio/QuPath/0.1.2/qupath-0.1.2/deploy/jars/ij-1.51g.jar:/oamp/bio/QuPath/0.1.2/qupath-0.1.2/deploy/jars/jfxtras-common-8.0-r5.jar:/oamp/bio/QuPath/0.1.2/qupath-0.1.2/deploy/jars/jfxtras-menu-8.0-r5.jar:/oamp/bio/QuPath/0.1.2/qupath-0.1.2/deploy/jars/jinput-2.0.6.jar:/oamp/bio/QuPath/0.1.2/qupath-0.1.2/deploy/jars/jinput-platform-2.0.6-natives-linux.jar:/oamp/bio/QuPath/0.1.2/qupath-0.1.2/deploy/jars/jinput-platform-2.0.6-natives-osx.jar:/oamp/bio/QuPath/0.1.2/qupath-0.1.2/deploy/jars/jinput-platform-2.0.6-natives-windows.jar:/oamp/bio/QuPath/0.1.2/qupath-0.1.2/deploy/jars/jpen-2-150301.jar:/oamp/bio/QuPath/0.1.2/qupath-0.1.2/deploy/jars/jpen-2-150301-natives-linux.jar:/oamp/bio/QuPath/0.1.2/qupath-0.1.2/deploy/jars/jpen-2-150301-natives-osx.jar:/oamp/bio/QuPath/0.1.2/qupath-0.1.2/deploy/jars/jpen-2-150301-natives-windows.jar:/oamp/bio/QuPath/0.1.2/qupath-0.1.2/deploy/jars/jutils-1.0.0.jar:/oamp/bio/QuPath/0.1.2/qupath-0.1.2/deploy/jars/logback-classic-1.1.7.jar:/oamp/bio/QuPath/0.1.2/qupath-0.1.2/deploy/jars/logback-core-1.1.7.jar:/oamp/bio/QuPath/0.1.2/qupath-0.1.2/deploy/jars/opencv-3.1.0.jar:/oamp/bio/QuPath/0.1.2/qupath-0.1.2/deploy/jars/opencv-3.1.0-natives-linux.jar:/oamp/bio/QuPath/0.1.2/qupath-0.1.2/deploy/jars/opencv-3.1.0-natives-osx.jar:/oamp/bio/QuPath/0.1.2/qupath-0.1.2/deploy/jars/opencv-3.1.0-natives-windows.jar:/oamp/bio/QuPath/0.1.2/qupath-0.1.2/deploy/jars/openslide-3.4.1_2.jar:/oamp/bio/QuPath/0.1.2/qupath-0.1.2/deploy/jars/openslide-3.4.1_2-natives-linux.jar:/oamp/bio/QuPath/0.1.2/qupath-0.1.2/deploy/jars/openslide-3.4.1_2-natives-osx.jar:/oamp/bio/QuPath/0.1.2/qupath-0.1.2/deploy/jars/openslide-3.4.1_2-natives-windows.jar:/oamp/bio/QuPath/0.1.2/qupath-0.1.2/deploy/jars/reactfx-2.0-M4u1.jar:/oamp/bio/QuPath/0.1.2/qupath-0.1.2/deploy/jars/richtextfx-0.6.10.jar:/oamp/bio/QuPath/0.1.2/qupath-0.1.2/deploy/jars/slf4j-api-1.7.20.jar:/oamp/bio/QuPath/0.1.2/qupath-0.1.2/deploy/jars/undofx-1.2.jar:/oamp/bio/QuPath/0.1.2/qupath-0.1.2/deploy/jars/wellbehavedfx-0.1.1.jar:./ QuPath 358.JPG -script t6.groovy

21:54:22.653 [main] [INFO ] QuPath - Launching QuPath with args: 358.JPG, -script, t6.groovy
21:54:23.003 [main] [INFO ] qupath.lib.gui.prefs.PathPrefs - Locale FORMAT set to en_US
21:54:23.005 [main] [INFO ] qupath.lib.gui.prefs.PathPrefs - Locale DISPLAY set to en_US
21:54:23.022 [main] [ERROR] QuPath - Error running script!
javax.script.ScriptException: javax.script.ScriptException: java.lang.NullPointerException: Cannot invoke method getServer() on null object
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:155)
	at QuPath.main(QuPath.java:162)
Caused by: javax.script.ScriptException: java.lang.NullPointerException: Cannot invoke method getServer() on null object
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:346)
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:152)
	... 1 common frames omitted
Caused by: java.lang.NullPointerException: Cannot invoke method getServer() on null object
	at org.codehaus.groovy.runtime.NullObject.invokeMethod(NullObject.java:91)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:48)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.NullCallSite.call(NullCallSite.java:35)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	at Script1.run(Script1.groovy:16)
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:343)
	... 2 common frames omitted


---------------------------------------------------------
t6.groovy:
import qupath.lib.gui.ImageWriterTools
import qupath.lib.gui.QuPathGUI
import qupath.lib.gui.viewer.OverlayOptions
import qupath.lib.regions.RegionRequest
import qupath.lib.scripting.QPEx

// Aim for an output resolution of approx 20 µm/pixel
double requestedPixelSize = 20

// Create the output directory, if required
def path = "./out/t6result" //QPEx.buildFilePath(QPEx.PROJECT_BASE_DIR, "export")
QPEx.mkdirs(path)

// Get the imageData & server
def imageData = QPEx.getCurrentImageData()
def server = imageData.getServer()
setImageType('BRIGHTFIELD_H_DAB');
setColorDeconvolutionStains('{"Name" : "H-DAB default", "Stain 1" : "Hematoxylin", "Values 1" : "0.65111 0.70119 0.29049 ", "Stain 2" : "DAB", "Values 2" : "0.26917 0.56824 0.77759 ", "Background" : " 255 255 255 "}');
runPlugin('qupath.imagej.detect.tissue.SimpleTissueDetection2', '{"threshold": 127,  "requestedDownsample": 1.0,  "minAreaPixels": 100000.0,  "maxHoleAreaPixels": 500.0,  "darkBackground": false,  "smoothImage": true,  "medianCleanup": true,  "dilateBoundaries": false, "smoothCoordinates": true,  "excludeOnBoundary": false,  "singleAnnotation": true}');

// Get the file name from the current server
def name = server.getShortServerName()

// We need to get the display settings (colors, line thicknesses, opacity etc.) from the current viewer, if available
def overlayOptions = QuPathGUI.getInstance() == null ? new OverlayOptions() : QuPathGUI.getInstance().getViewer().getOverlayOptions()

// Calculate downsample factor depending on the requested pixel size
double downsample = 5 //requestedPixelSize / server.getAveragedPixelSizeMicrons()
def request = RegionRequest.createInstance(imageData.getServerPath(), downsample, 0, 0, server.getWidth(), server.getHeight())

// Write output image, with and without overlay
def dir = new File(path)
def fileImage = new File(dir, name + ".jpg")
def img = ImageWriterTools.writeImageRegion(server, request, fileImage.getAbsolutePath())
def fileImageWithOverlay = new File(dir, name + "-overlay.jpg")
println(overlayOptions)
ImageWriterTools.writeImageRegionWithOverlay(img, imageData, overlayOptions, request, fileImageWithOverlay.getAbsolutePath())

**Comment by petebankhead** [comment]
This is now a duplicate of https://github.com/qupath/qupath/issues/217 and it would be better to continue there.

On Linux, it appears that image hasn't been opened and therefore there is no `imageData` (both here and in the other discussion).  I don't know why this is the case; it could be a bug in QuPath, or it could be an error in the way you call it from the command line (I don't know what you type at the command line or where your image is located).

Can you say what exactly solved the problem above? https://github.com/qupath/qupath/issues/216#issuecomment-420296209
This would be helpful in case a similar question comes up in the future.
