### ISSUE TITLE
Cannot import class XmlSlurper error at Windows

### ISSUE THREAD

**Issue by Kangyeol-Kim** [qupath/qupath#238]
I'm currently working on importing imageScope annotations to Qupath using groovy script. When I was working with Mac OS, the script worked pretty well without any error. However, after changing to Windos. I had a trouble at below part. (Even though I copied 'groovy-xml-2.5.2.jar'  into C:\Program Files\QuPath\app\jars)

==================================================================
[ERROR PART]
def text = new File(xml_file).getText()
def list = new XmlSlurper().parseText(text)

[ERROR]
ERROR: Script error
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:53)
    at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:52)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:307)
    at Script4.run(Script4.groovy:33)
    at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:343)
    at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:152)
    at qupath.lib.scripting.DefaultScriptEditor.executeScript(DefaultScriptEditor.java:765)
    at qupath.lib.scripting.DefaultScriptEditor.executeScript(DefaultScriptEditor.java:695)
    at qupath.lib.scripting.DefaultScriptEditor.executeScript(DefaultScriptEditor.java:677)
    at qupath.lib.scripting.DefaultScriptEditor.access$400(DefaultScriptEditor.java:136)
    at qupath.lib.scripting.DefaultScriptEditor$2.run(DefaultScriptEditor.java:1029)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
ERROR: Error: startup failed:
Script5.groovy: 30: unable to resolve class XmlSlurper 
 @ line 30, column 12.
   def list = new XmlSlurper().parseText(text)
              ^

1 error
==================================================================

My question is how can I use that class in Windows.. At Mac, It worked fine after I copied 'groovy-xml-2.5.2.jar' into extensions folder. However, the structure of Qupath at windows is quite different from Mac. And I have no idea where to put 'groovy-xml-2.5.2.jar'

Thanks!!!

**Comment by Svidro** [comment]
There should be a folder for Extensions, which is where you would put that, I believe.
![image](https://user-images.githubusercontent.com/23145209/47734611-daf31880-dc27-11e8-9ea2-e2d555116cc8.png)
You can choose the folder.

In case it helps, someone else wrote the reverse method: https://github.com/qupath/qupath/issues/61#issuecomment-359990015

**Comment by petebankhead** [comment]
It's the same process to install extensions on Windows: drag the jar onto QuPath when it's running and (generally) accept the default extensions directory.  You might need to restart QuPath, but maybe not.

Files inside `QuPath\app\jars` aren't automatically picked up, rather they need to be added to the classpath explicitly.  There's a file `QuPath.cfg` that defines this for the built-in jars.

**Comment by Kangyeol-Kim** [comment]
I fixed it !!! Thank you for your kind comments !
