### ISSUE TITLE
BUG: Opening large TIFFs (tiled, pyramid) stopped working when using 0.2.0-m1

### ISSUE THREAD

**Issue by JoelRV** [qupath/qupath#279]
Greetings,

I started palying around with the new 0.2.0-m1 build and wanted to report a bug that wasn't there before:
Using version 0.1.3 and before that 0.1.2, I was able to open my generated TIFF without a problem and in a rapid fashion.

Yet, when using the newest build, the window freezes and pushes my 12 threads without changing for minutes making me force quit.

Here is a command line dump:
```
./QuPath-0.2.0-m1 
12:07:40.563 [main] [INFO ] qupath.QuPath - Launching QuPath with args: 
12:07:41.084 [JavaFX Application Thread] [INFO ] qupath.lib.gui.prefs.PathPrefs - Locale FORMAT set to en_US
12:07:41.086 [JavaFX Application Thread] [INFO ] qupath.lib.gui.prefs.PathPrefs - Locale DISPLAY set to en_US
12:07:41.115 [JavaFX Application Thread] [INFO ] qupath.lib.gui.prefs.PathPrefs - Tile cache size: 4096.00 MB
12:07:41.218 [JavaFX Application Thread] [WARN ] qupath.lib.gui.QuPathGUI - No directory set for log files! None will be written.
12:07:41.225 [JavaFX Application Thread] [INFO ] qupath.lib.gui.QuPathGUI - QuPath build: Version: 0.2.0-m1
Build time: 2019-03-08, 17:51
Latest commit tag: v0.0.1-beta-561-gfb062c1

(QuPath-0.2.0-m1:8210): Gdk-WARNING **: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.
12:07:42.748 [JavaFX Application Thread] [INFO ] q.l.i.s.b.BioFormatsOptionsExtension - Bio-Formats version 6.0.0
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/home/joelrv/software/opt/QuPath/qupath_0.2.0-m1/app/groovy-2.5.6.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
12:07:43.276 [JavaFX Application Thread] [INFO ] q.l.i.s.o.OpenslideServerBuilder - OpenSlide version 3.4.1
12:07:43.360 [JavaFX Application Thread] [INFO ] qupath.lib.gui.QuPathGUI - Selected style: null
12:07:43.360 [JavaFX Application Thread] [INFO ] qupath.lib.gui.QuPathGUI - Performing update check...
12:07:43.365 [JavaFX Application Thread] [INFO ] qupath.lib.gui.QuPathApp - Starting QuPath with parameters: []
12:08:18.669 [JavaFX Application Thread] [WARN ] q.l.i.s.o.OpenslideImageServer - Openslide: Property 'openslide.mpp-x' not available, will return default value NaN
12:08:18.670 [JavaFX Application Thread] [WARN ] q.l.i.s.o.OpenslideImageServer - Openslide: Property 'openslide.mpp-y' not available, will return default value NaN
12:08:18.670 [JavaFX Application Thread] [WARN ] q.l.i.s.o.OpenslideImageServer - Openslide: Property 'openslide.objective-power' not available, will return default value NaN
12:08:18.677 [JavaFX Application Thread] [WARN ] q.l.i.s.o.OpenslideServerBuilder - Unable to open file:/media/joelrv/SDB/Dropbox/PhD/ST_Thyroid/r_plotting/input_data/new_sample/ndpi_and_tifs/st1_d1_HE_final.tif with OpenSlide: Pixel width must be a finite number > 0, not NaN
12:08:19.076 [JavaFX Application Thread] [INFO ] loci.formats.ImageReader - TiffDelegateReader initializing /media/joelrv/SDB/Dropbox/PhD/ST_Thyroid/r_plotting/input_data/new_sample/ndpi_and_tifs/st1_d1_HE_final.tif
12:08:19.078 [JavaFX Application Thread] [INFO ] loci.formats.in.MinimalTiffReader - Reading IFDs
12:08:19.172 [JavaFX Application Thread] [INFO ] loci.formats.in.MinimalTiffReader - Populating metadata
12:08:19.182 [JavaFX Application Thread] [INFO ] loci.formats.in.TiffReader - Checking comment style
12:08:19.182 [JavaFX Application Thread] [INFO ] loci.formats.in.BaseTiffReader - Populating OME metadata
12:08:19.194 [JavaFX Application Thread] [INFO ] q.l.i.s.b.BioFormatsImageServer - No memoization file generated for /media/joelrv/SDB/Dropbox/PhD/ST_Thyroid/r_plotting/input_data/new_sample/ndpi_and_tifs/st1_d1_HE_final.tif
12:08:19.197 [JavaFX Application Thread] [INFO ] q.l.i.servers.ImageServerProvider - Returning server: Bio-Formats for /media/joelrv/SDB/Dropbox/PhD/ST_Thyroid/r_plotting/input_data/new_sample/ndpi_and_tifs/st1_d1_HE_final.tif
12:08:20.622 [JavaFX Application Thread] [INFO ] loci.formats.ImageReader - TiffDelegateReader initializing /media/joelrv/SDB/Dropbox/PhD/ST_Thyroid/r_plotting/input_data/new_sample/ndpi_and_tifs/st1_d1_HE_final.tif
12:08:20.623 [JavaFX Application Thread] [INFO ] loci.formats.in.MinimalTiffReader - Reading IFDs
12:08:20.670 [JavaFX Application Thread] [INFO ] loci.formats.in.MinimalTiffReader - Populating metadata
12:08:20.671 [JavaFX Application Thread] [INFO ] loci.formats.in.TiffReader - Checking comment style
12:08:20.671 [JavaFX Application Thread] [INFO ] loci.formats.in.BaseTiffReader - Populating OME metadata
12:08:20.672 [JavaFX Application Thread] [INFO ] q.l.i.s.b.BioFormatsImageServer - No memoization file generated for /media/joelrv/SDB/Dropbox/PhD/ST_Thyroid/r_plotting/input_data/new_sample/ndpi_and_tifs/st1_d1_HE_final.tif
```
Something seems to have change in the underlying way Qupath opens those TIFFs, so if you need anything else to pinpoint the issue, feel free to specify it.

Best regards,
JRV

**Comment by petebankhead** [comment]
Are you able to share an example file that doesn't work? It sounds like the problem is in either QuPath or Bio-Formats, and much has changed in both.

Either way, since the log isn't recording anything very obviously wrong I'd need to test it with a failing file to identify where it is going wrong.

If it's not possible to share a file, then I'd be trying to fix it through guesswork... to have a chance, I'd need to know more about how it works in v0.1.2, e.g.
* under the 'Image' tab, what is the 'Server type' when the image is correctly opened?
* if the type is 'Bio-Formats', which version of Bio-Formats is installed?  v0.2.0 is using Bio-Formats v6.0.0.

**Comment by JoelRV** [comment]
Hi again,

In v0.1.2. the servertype is set as Openslide.
Installed Bio-Formats is 5.9.2.

I could share a one-time link with you for an example file (due to privacy concerns).
Do you have a preference?

**Comment by petebankhead** [comment]
Ah thanks, I _think_ this commit will fix things: https://github.com/petebankhead/qupath/commit/a86355f479017f18c9cc36ea6a0b2f4dbe30cdee

If you can share a file I'll check or you can build QuPath from that branch you can also check... or else you could wait until the next milestone (shouldn't take 2 years this time...) and we can revisit if it's not fixed after all.

**Comment by NHPatterson** [comment]
I encountered the same error using generic tiled pyramidal tifs generated with ImageMagick or libvips. 
Here is an example file:
[Image](https://vanderbilt.box.com/s/s833k4t61ntwmrxu37p4edxpimqzzndm)

**Comment by JoelRV** [comment]
Hi again,

I compiled the pete-java11 branch (after some ubuntu debugging). Sadly I had to compile it on a local laptop with low memory (until I get back to the lab). So take this into account (the log suggest that RAM is the problem on this machine).

Here are my file links:

cropped : https://owncloud.ulb.ac.be/index.php/s/ReltLIepwxOZ2RK
fullsize : https://owncloud.ulb.ac.be/index.php/s/VhuHZheRNHgdUqk
PASSWORD: qupathBug 
Expires: march 17 2019

On my main machine I noticed that when opening the cropped version, qupath opens it after some minutes of intensive cpu calculations. This seems to suggest that qupath is precomputing something instead of directly opening the file.

I tried opening my files and those from NHPatterson. As of yet it seems to still not be working.

LOG DUMP
```
INFO: Bio-Formats version 6.0.0
ERROR: Could not load OpenSlide native libraries
    at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2660)
    at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:829)
    at java.base/java.lang.System.loadLibrary(System.java:1867)
    at org.openslide.OpenSlideJNI.<clinit>(OpenSlideJNI.java:55)
    at org.openslide.OpenSlide.<clinit>(OpenSlide.java:53)
    at qupath.lib.images.servers.openslide.OpenslideServerBuilder.<clinit>(OpenslideServerBuilder.java:87)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
    at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:779)
    at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:721)
    at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1394)
    at qupath.lib.images.servers.ImageServerProvider.getInstalledImageServerBuilders(ImageServerProvider.java:84)
    at qupath.lib.gui.QuPathGUI.refreshExtensions(QuPathGUI.java:1198)
    at qupath.lib.gui.QuPathGUI.<init>(QuPathGUI.java:723)
    at qupath.lib.gui.QuPathGUI.<init>(QuPathGUI.java:473)
    at qupath.lib.gui.QuPathApp.start(QuPathApp.java:63)
    at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:846)
    at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:455)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
    at java.base/java.lang.Thread.run(Thread.java:834)
INFO: If you want to use OpenSlide, you'll need to get the native libraries (either building from source or with a packager manager)
and add them to your system PATH, including openslide-jni.
INFO: Selected style: null
INFO: Performing update check...
INFO: Starting QuPath with parameters: []
INFO: TiffDelegateReader initializing /home/joelrv/Downloads/RK_HE.ptif
INFO: Reading IFDs
INFO: Populating metadata
INFO: Checking comment style
INFO: Populating OME metadata
INFO: No memoization file generated for /home/joelrv/Downloads/RK_HE.ptif
INFO: Returning server: Bio-Formats for /home/joelrv/Downloads/RK_HE.ptif
INFO: TiffDelegateReader initializing /home/joelrv/Downloads/RK_HE.ptif
INFO: Reading IFDs
INFO: Populating metadata
INFO: Checking comment style
INFO: Populating OME metadata
INFO: No memoization file generated for /home/joelrv/Downloads/RK_HE.ptif
ERROR: QuPath exception
    at java.desktop/sun.awt.image.IntegerInterleavedRaster.getDataElements(IntegerInterleavedRaster.java:267)
    at qupath.lib.display.ChannelDisplayInfo$RGBDirectChannelInfo.getRGBIntBuffer(ChannelDisplayInfo.java:540)
    at qupath.lib.display.ChannelDisplayInfo$RBGColorTransformInfo.getValues(ChannelDisplayInfo.java:708)
    at qupath.lib.display.ImageDisplay$HistogramManager.ensureChannels(ImageDisplay.java:819)
    at qupath.lib.display.ImageDisplay.updateHistogramMap(ImageDisplay.java:554)
    at qupath.lib.display.ImageDisplay.setImageData(ImageDisplay.java:144)
    at qupath.lib.gui.viewer.QuPathViewer.setImageData(QuPathViewer.java:1385)
    at qupath.lib.gui.QuPathGUI.openImage(QuPathGUI.java:2459)
    at qupath.lib.gui.QuPathGUI.openImage(QuPathGUI.java:2368)
    at qupath.lib.gui.commands.OpenCommand.run(OpenCommand.java:51)
    at qupath.lib.gui.QuPathGUI.lambda$createCommandAction$50(QuPathGUI.java:3409)
    at qupath.lib.gui.QuPathGUI$$Lambda$144/0x00000008401ef440.accept(Unknown Source)
    at org.controlsfx.control.action.Action.handle(Action.java:419)
    at org.controlsfx.control.action.Action.handle(Action.java:64)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.control.MenuItem.fire(MenuItem.java:465)
    at com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1380)
    at com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.lambda$createChildren$12(ContextMenuContent.java:1333)
    at com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer$$Lambda$1392/0x0000000840654440.handle(Unknown Source)
    at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
ERROR: QuPath exception
    at qupath.lib.gui.viewer.QuPathViewer.updateSuggestedOverlayColorFromThumbnail(QuPathViewer.java:996)
    at qupath.lib.gui.viewer.QuPathViewer.getSuggestedOverlayColor(QuPathViewer.java:1005)
    at qupath.lib.gui.viewer.QuPathViewer.paintViewer(QuPathViewer.java:1665)
    at qupath.lib.gui.viewer.QuPathViewer.paintCanvas(QuPathViewer.java:413)
    at qupath.lib.gui.viewer.QuPathViewerPlus.paintCanvas(QuPathViewerPlus.java:249)
    at qupath.lib.gui.viewer.QuPathViewer.lambda$repaint$4(QuPathViewer.java:501)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
    at java.base/java.lang.Thread.run(Thread.java:834)
ERROR: QuPath exception
    at qupath.lib.gui.viewer.QuPathViewer.updateSuggestedOverlayColorFromThumbnail(QuPathViewer.java:996)
    at qupath.lib.gui.viewer.QuPathViewer.getSuggestedOverlayColor(QuPathViewer.java:1005)
    at qupath.lib.gui.viewer.QuPathViewer.paintViewer(QuPathViewer.java:1665)
    at qupath.lib.gui.viewer.QuPathViewer.paintCanvas(QuPathViewer.java:413)
    at qupath.lib.gui.viewer.QuPathViewerPlus.paintCanvas(QuPathViewerPlus.java:249)
    at qupath.lib.gui.viewer.QuPathViewer.lambda$repaint$4(QuPathViewer.java:501)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
    at java.base/java.lang.Thread.run(Thread.java:834)
INFO: TiffDelegateReader initializing /home/joelrv/Downloads/test_pyramid.tif
INFO: Reading IFDs
INFO: Populating metadata
INFO: Checking comment style
INFO: Populating OME metadata
INFO: No memoization file generated for /home/joelrv/Downloads/test_pyramid.tif
INFO: Returning server: Bio-Formats for /home/joelrv/Downloads/test_pyramid.tif
ERROR: QuPath exception
ERROR: java.lang.OutOfMemoryError: Java heap space
WARN: Fallback to requesting thumbnail directly...
ERROR: QuPath exception
WARN: Tile request exception
ERROR: QuPath exception
    at qupath.lib.gui.viewer.QuPathViewer.updateSuggestedOverlayColorFromThumbnail(QuPathViewer.java:996)
    at qupath.lib.gui.viewer.QuPathViewer.getSuggestedOverlayColor(QuPathViewer.java:1005)
    at qupath.lib.gui.viewer.QuPathViewer.paintViewer(QuPathViewer.java:1665)
    at qupath.lib.gui.viewer.QuPathViewer.paintCanvas(QuPathViewer.java:413)
    at qupath.lib.gui.viewer.QuPathViewerPlus.paintCanvas(QuPathViewerPlus.java:249)
    at qupath.lib.gui.viewer.QuPathViewer.lambda$repaint$4(QuPathViewer.java:501)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
    at java.base/java.lang.Thread.run(Thread.java:834)
INFO: TiffDelegateReader initializing /home/joelrv/Downloads/test_pyramid.tif
INFO: Reading IFDs
INFO: Populating metadata
INFO: Checking comment style
INFO: Populating OME metadata
INFO: No memoization file generated for /home/joelrv/Downloads/test_pyramid.tif
ERROR: QuPath exception
    at qupath.lib.gui.viewer.QuPathViewer.updateSuggestedOverlayColorFromThumbnail(QuPathViewer.java:996)
    at qupath.lib.gui.viewer.QuPathViewer.getSuggestedOverlayColor(QuPathViewer.java:1005)
    at qupath.lib.gui.viewer.QuPathViewer.paintViewer(QuPathViewer.java:1665)
    at qupath.lib.gui.viewer.QuPathViewer.paintCanvas(QuPathViewer.java:413)
    at qupath.lib.gui.viewer.QuPathViewerPlus.paintCanvas(QuPathViewerPlus.java:249)
    at qupath.lib.gui.viewer.QuPathViewer.lambda$repaint$4(QuPathViewer.java:501)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
    at com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:277)
    at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by petebankhead** [comment]
Thanks @NHPatterson and @JoelRV 

In both cases, Bio-Formats appears not to see the pyramidal levels and instead tries to open everything - and that is the reason for any attempting to open being very slow and requiring a lot (or too much) memory.

It might be worth following up on this with the Bio-Formats team on GitHub or https://forum.image.sc/
Since Bio-Formats writes OME-TIFF, which now supports pyramidal images, you could also use `bfconvert` to create a more Bio-Formats friendly image in the first place.

Therefore success only comes if OpenSlide opens the image instead.  This was failing because of too harsh a check that the pixel sizes are available and valid, and my recent commit should fix this.  I'm now able to open both images - _but without pixel size information_. I'm not sure if it should be there or not, but it's progress.

@JoelRV the reason it's still failing for you seems to be because OpenSlide is not being loaded correctly on Ubuntu... which is a problem I've never quite solved, and success seems largely dependent on whether enough other stuff happens to be installed already.  Could you try installing OpenSlide through your package manager and see if that helps ensure the dependencies are all available?

Ultimately, QuPath + OpenSlide on Linux has issues.... OpenSlide has some sub-dependencies (e.g. libtiff) and these aren't searched for in the place that I hoped they would be (i.e. the QuPath directory) but rather elsewhere on the system. So either a new, more portable way of packaging up OpenSlide needs to be found, or else is should be installed separately, or else Linux users would have to rely more on Bio-Formats. But that of course requires Bio-Formats to work for your file formats...

**Comment by NHPatterson** [comment]
Looks like the bio-formats issue is being addressed. See issue below.
openmicroscopy/bioformats#3300

**Comment by JoelRV** [comment]
Thanks @NHPatterson.

@petebankhead I tried recompiling the java-11 branch on my main machine, but it keeps failing with the same error.
For my cursiosity, did you try loading the same files with the published 0.1.2 or 0.1.3-SNAPSHOT versions. For example using the later I have the following log after opening everything without issues:

```
./QuPath 
12:25:42.077 [main] [INFO ] qupath.QuPath - Launching QuPath with args: 
12:25:42.710 [JavaFX Application Thread] [INFO ] qupath.lib.gui.prefs.PathPrefs - Locale FORMAT set to fr_BE
12:25:42.714 [JavaFX Application Thread] [INFO ] qupath.lib.gui.prefs.PathPrefs - Locale DISPLAY set to en_US
12:25:42.742 [JavaFX Application Thread] [INFO ] qupath.lib.gui.prefs.PathPrefs - Tile cache size: 4096,00 MB
12:25:43.922 [JavaFX Application Thread] [INFO ] qupath.lib.gui.QuPathGUI - Refreshing extensions in /home/joelrv/QuPath/extensions
12:25:43.923 [JavaFX Application Thread] [INFO ] qupath.lib.gui.QuPathGUI - Added extension: /home/joelrv/QuPath/extensions/qupath-extension-bioformats.jar
12:25:43.923 [JavaFX Application Thread] [INFO ] qupath.lib.gui.QuPathGUI - Added extension: /home/joelrv/QuPath/extensions/bioformats_package.jar
12:25:43.943 [JavaFX Application Thread] [INFO ] q.l.i.s.BioFormatsOptionsExtension - Bio-Formats version 5.9.2
12:25:44.261 [JavaFX Application Thread] [INFO ] qupath.lib.gui.QuPathGUI - Selected style: Modena Light
12:25:44.262 [JavaFX Application Thread] [INFO ] qupath.lib.gui.QuPathGUI - Performing update check...
12:25:44.262 [JavaFX Application Thread] [INFO ] qupath.lib.gui.QuPathApp - Starting QuPath with parameters: []
12:25:55.878 [JavaFX Application Thread] [ERROR] q.l.i.servers.OpenslideImageServer - Openslide: Property not available: openslide.mpp-x
12:25:55.879 [JavaFX Application Thread] [ERROR] q.l.i.servers.OpenslideImageServer - Openslide: Property not available: openslide.mpp-y
12:25:55.879 [JavaFX Application Thread] [ERROR] q.l.i.servers.OpenslideImageServer - Openslide: Property not available: openslide.objective-power
12:25:55.895 [JavaFX Application Thread] [INFO ] q.l.i.servers.OpenslideImageServer - Test reading thumbnail with openslide: passed (BufferedImage@58da6639: type = 1 DirectColorModel: rmask=ff0000 gmask=ff00 bmask=ff amask=0 IntegerInterleavedRaster: width = 194 height = 200 #Bands = 3 xOff = 0 yOff = 0 dataOffset[0] 0)
12:25:55.896 [JavaFX Application Thread] [INFO ] q.l.i.servers.ImageServerProvider - Returning server: OpenSlide for /home/joelrv/Downloads/bftools/test_pyramid_fullsize.tif
12:25:56.155 [JavaFX Application Thread] [INFO ] q.lib.gui.helpers.DisplayHelpers - Estimating H-DAB staining
12:25:56.537 [JavaFX Application Thread] [INFO ] qupath.lib.gui.viewer.QuPathViewer - Image data set to ImageData: Brightfield (H-DAB), test_pyramid_fullsize
```
I not familiar enough with the code to understand what's happening, it's just so strange that it used to work before...

In any case thanks for trying to adress the issue!

**Comment by petebankhead** [comment]
@JoelRV It's not too strange, much of the image-reading code has been completely rewritten and I can see the change where the problem occurs.

Building v0.2.0 with JDK 11 isn't documented anywhere yet, but it is more involved than v0.1.3 (mostly because OpenJDK 11 is needed along a pre-release version of jpackage, downloaded separately, with paths set accordingly). If 'the same error' means a build error, then I'd guess that's why.

**Comment by petebankhead** [comment]
I haven't checked with v0.1.2 or v0.1.3 but as far as I can tell the problem is solved... and the earlier versions will not be maintained.

**Comment by JoelRV** [comment]
Finally, after source building openslide and openslide-java manually, and syslinking `/usr/lib/openslide.jar` and '/usr/lib/libopenslide-jni.so', JAVAFX was able to build the Openslide imageserver.

So I confirm, that the Bug seems fixed under the condition that Openslide is loaded correctly.

Thanks again!
