### ISSUE TITLE
Is there a command to get the version of QuPath?

### ISSUE THREAD

**Issue by rmd06** [qupath/qupath#282]
To deal with different version in scripting, sometimes we need to switch between different code.
Is there a simple way to get the version at the beginning?

version = ...
if (version,equals(...)){
...
} else if  (version,equals(...)){
...
}

Thanks.

**Comment by Svidro** [comment]
Haven't really tested it on all versions, but I did have this snippet in a script when I needed to check version for functionality:
```
    if (!getQuPath().getClass().getPackage()?.getImplementationVersion()){
        params.getParameters().get('getOverlayAs').setValue('Annotations')
    }
```
I think it failed for version 0.1.3

**Comment by petebankhead** [comment]
This should give some useful info...
```groovy
print getQuPath().getBuildString()
```

**Comment by Svidro** [comment]
Nice!
Slight modification:
`print getQuPath().getBuildString().split()[1]`
Output: INFO: 0.2.0-m1

**Comment by rmd06** [comment]
When I run in QuPath 0.1.2,error appeared:

print(getQuPath().getBuildString())

ERROR: Error at line 15: No signature of method: org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.getQuPath() is applicable for argument types: () values: []
Possible solutions: getAt(java.lang.String), getClass()

ERROR: Script error
    at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.callGlobal(GroovyScriptEngineImpl.java:415)
    at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.access$000(GroovyScriptEngineImpl.java:97)
    at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl$2.invokeMethod(GroovyScriptEngineImpl.java:329)
    at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:69)
    at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:158)
    at Script7.run(Script7.groovy:15)
    at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:343)
    at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:152)
    at qupath.lib.scripting.DefaultScriptEditor.executeScript(DefaultScriptEditor.java:765)
    at qupath.lib.scripting.DefaultScriptEditor.executeScript(DefaultScriptEditor.java:695)
    at qupath.lib.scripting.DefaultScriptEditor.executeScript(DefaultScriptEditor.java:677)
    at qupath.lib.scripting.DefaultScriptEditor.access$400(DefaultScriptEditor.java:136)
    at qupath.lib.scripting.DefaultScriptEditor$2.run(DefaultScriptEditor.java:1029)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

**Comment by rmd06** [comment]
I solve the import error by this way:
```
def IJTools,ImagePlusServer,ImagePlusServerBuilder
try {
//import qupath.imagej.helpers.IJTools
IJTools = "qupath.imagej.helpers.IJTools" as Class
} catch(Exception ex) {
//import qupath.imagej.images.servers.ImagePlusServer
//import qupath.imagej.images.servers.ImagePlusServerBuilder
ImagePlusServer = "qupath.imagej.images.servers.ImagePlusServer"  as Class
ImagePlusServerBuilder = "qupath.imagej.images.servers.ImagePlusServerBuilder"  as Class
}

```
