### ISSUE TITLE
script compile error: runs via GUI OK, but failed via command line

### ISSUE THREAD

**Issue by rmd06** [qupath/qupath#286]
I have a script that runs via QuPath GUI without problem.
However, if I run this via GUI, a weird compilation error appeared inside the code:
double PixelHeightMicrons,PixelWidthMicrons,PixelZSpacingMicrons
```
if (HasPixelSizeMicrons){
    PixelHeightMicrons = server.getPixelHeightMicrons()
    print("PixelHeightMicrons:" + PixelHeightMicrons)
    PixelWidthMicrons = server.getPixelWidthMicrons()
    print("PixelWidthMicrons:" + PixelWidthMicrons)
    PixelZSpacingMicrons = server.getZSpacingMicrons()
    print("PixelZSpacingMicrons:" + PixelZSpacingMicrons)
}else{
    PixelHeightMicrons = 1.0
    print("PixelHeightMicrons:" + PixelHeightMicrons)
    PixelWidthMicrons = 1.0
    print("PixelWidthMicrons:" + PixelWidthMicrons)
    PixelZSpacingMicrons = 1.0
    print("PixelZSpacingMicrons:" + PixelZSpacingMicrons)
}
```
The weird error take place at the line,which is a very common line:
`PixelWidthMicrons = server.getPixelWidthMicrons()
`
```
15:23:36.355 [main] [INFO ] qupath.QuPath - Launching QuPath with args: -image, D:\\QMDownload\\5\\~!@#$%^&( )_+=-0987654321`{}[%23];',\\single_neur~!@#$%^&( )_+=-0987654321`{}[%23];',on_40X_3.mrxs, -script, D:\\QMDownload\\5\\~!@#$%^&( )_+=-0987654321`{}[%23];',\\tpce66e23b_cda9_4090_b04a_b5603607aba8.groovy 
15:23:36.512 [main] [INFO ] q.l.i.s.o.OpenslideServerBuilder - OpenSlide version 3.4.1 
15:23:36.562 [main] [WARN ] q.l.i.s.o.OpenslideImageServer - Openslide: Property 'openslide.level[0].tile-width' not available, will return default value 256.0 
15:23:36.562 [main] [WARN ] q.l.i.s.o.OpenslideImageServer - Openslide: Property 'openslide.level[0].tile-height' not available, will return default value 256.0 
15:23:36.812 [main] [INFO ] q.l.i.s.o.OpenslideImageServer - Test reading thumbnail with openslide: passed (BufferedImage@2f953efd: type = 1 DirectColorModel: rmask=ff0000 gmask=ff00 bmask=ff amask=0 IntegerInterleavedRaster: width = 200 height = 87 #Bands = 3 xOff = 0 yOff = 0 dataOffset[0] 0) 
15:23:36.812 [main] [INFO ] q.l.i.servers.ImageServerProvider - Returning server: OpenSlide for D:\\QMDownload\\5\\~!@#$%^&( )_+=-0987654321`{}[%23];',\\single_neur~!@#$%^&( )_+=-0987654321`{}[%23];',on_40X_3.mrxs 
WARNING: An illegal reflective access operation has occurred 
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (file:/C:/Program%20Files/QuPath-0.2.0-m1/app/groovy-2.5.6.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int) 
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.vmplugin.v7.Java7$1 
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations 
WARNING: All illegal access operations will be denied in a future release 
15:23:37.065 [main] [ERROR] qupath.QuPath - Error running script! 
javax.script.ScriptException: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed: 
Script1.groovy: 102: expecting '}', found '' @ line 102, column 18. 
       PixelWidthMic 
                    ^ 
 
1 error 
 
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:158) 
	at qupath.QuPath.main(QuPath.java:161) 
Caused by: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed: 
Script1.groovy: 102: expecting '}', found '' @ line 102, column 18. 
       PixelWidthMic 
                    ^ 
 
1 error 
 
	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:311) 
	at org.codehaus.groovy.control.ErrorCollector.addFatalError(ErrorCollector.java:151) 
	at org.codehaus.groovy.control.ErrorCollector.addError(ErrorCollector.java:121) 
	at org.codehaus.groovy.control.ErrorCollector.addError(ErrorCollector.java:133) 
	at org.codehaus.groovy.control.SourceUnit.addError(SourceUnit.java:325) 
	at org.codehaus.groovy.antlr.AntlrParserPlugin.transformCSTIntoAST(AntlrParserPlugin.java:224) 
	at org.codehaus.groovy.antlr.AntlrParserPlugin.parseCST(AntlrParserPlugin.java:190) 
	at org.codehaus.groovy.control.SourceUnit.parse(SourceUnit.java:226) 
	at org.codehaus.groovy.control.CompilationUnit$1.call(CompilationUnit.java:196) 
	at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:965) 
	at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:647) 
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:623) 
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:600) 
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:390) 
	at groovy.lang.GroovyClassLoader.access$300(GroovyClassLoader.java:89) 
	at groovy.lang.GroovyClassLoader$5.provide(GroovyClassLoader.java:330) 
	at groovy.lang.GroovyClassLoader$5.provide(GroovyClassLoader.java:327) 
	at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:147) 
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:325) 
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:309) 
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:251) 
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.getScriptClass(GroovyScriptEngineImpl.java:331) 
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:153) 
	... 1 common frames omitted 

```

**Comment by rmd06** [comment]
Somehow it's OK now, but I'm not sure what cause the problem and how to solve it. 
I just edit the script and remove all the indent, delete several unicode char, switch from UTF8 to ANSI or reverse it in notepad++, then it runs OK.

**Comment by yonechian** [comment]
Hi, can we use the indent in command line? If yes, it would be much easier to edit some parameters.

**Comment by rmd06** [comment]
Does QuPath has a command line? I'm not sure. But you can run script from the script window.
