### ISSUE TITLE
Bug: temp file *.bfmemo  does not delete itself after using QuPath

### ISSUE THREAD

**Issue by rmd06** [qupath/qupath#287]
Every time when I run a script, a temp file was generated in QuPath 0.2.0 but not 0.1.2.

From the echo, Bioformats tries to delete the temp file, but the file path has one additional dot before the filename, so the deletion failed:

`6:23:09.798 [main] [WARN ] loci.formats.Memoizer - file deletion failed D:\QMDownload\5\os\.OS-3.vsi.bfmemo `

The file was 
`D:\QMDownload\5\os\OS-3.vsi.bfmemo 
`

After a successful running, all the output was:
```
16:23:06.071 [main] [INFO ] qupath.QuPath - Launching QuPath with args: -image, D:\\QMDownload\\5\\os\\OS-3.vsi, -script, C:\\Users\\rmd\\AppData\\Local\\Temp\\tpd56d11ce_e4ba_481c_a046_3d19297b763a.groovy 
16:23:06.151 [main] [WARN ] q.lib.images.servers.FileFormatInfo - Strange 'bits per sample' of 0 
16:23:06.211 [main] [INFO ] q.l.i.s.o.OpenslideServerBuilder - OpenSlide version 3.4.1 
WARNING: An illegal reflective access operation has occurred 
WARNING: Illegal reflective access by com.esotericsoftware.kryo.util.UnsafeUtil (file:/C:/Program%20Files/QuPath-0.2.0-m1/app/kryo-2.24.0.jar) to constructor java.nio.DirectByteBuffer(long,int,java.lang.Object) 
WARNING: Please consider reporting this to the maintainers of com.esotericsoftware.kryo.util.UnsafeUtil 
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations 
WARNING: All illegal access operations will be denied in a future release 
16:23:07.141 [main] [WARN ] loci.formats.Memoizer - deleting invalid memo file: D:\QMDownload\5\os\.OS-3.vsi.bfmemo 
com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 429
Serialization trace:
service (loci.formats.in.OperettaReader)
readers (loci.formats.ImageReader)
reader (loci.formats.DimensionSwapper)
reader (loci.formats.FileStitcher)
helper (loci.formats.in.FilePatternReader)
readers (loci.formats.ImageReader) 
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:119) 
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:641) 
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.read(DefaultArraySerializers.java:375) 
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.read(DefaultArraySerializers.java:289) 
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:679) 
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:106) 
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:528) 
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:679) 
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.read(DefaultArraySerializers.java:378) 
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.read(DefaultArraySerializers.java:289) 
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:679) 
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:106) 
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:528) 
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:679) 
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:106) 
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:528) 
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:679) 
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:106) 
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:528) 
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:679) 
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:106) 
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:528) 
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:679) 
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.read(DefaultArraySerializers.java:378) 
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.read(DefaultArraySerializers.java:289) 
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:679) 
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:106) 
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:528) 
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:657) 
	at loci.formats.Memoizer$KryoDeser.loadReader(Memoizer.java:163) 
	at loci.formats.Memoizer.loadMemo(Memoizer.java:888) 
	at loci.formats.Memoizer.setId(Memoizer.java:666) 
	at qupath.lib.images.servers.bioformats.BioFormatsImageServer$BioFormatsReaderManager.createReader(BioFormatsImageServer.java:1141) 
	at qupath.lib.images.servers.bioformats.BioFormatsImageServer$BioFormatsReaderManager.createReader(BioFormatsImageServer.java:1083) 
	at qupath.lib.images.servers.bioformats.BioFormatsImageServer$BioFormatsReaderManager.getPrimaryReader(BioFormatsImageServer.java:997) 
	at qupath.lib.images.servers.bioformats.BioFormatsImageServer.<init>(BioFormatsImageServer.java:216) 
	at qupath.lib.images.servers.bioformats.BioFormatsImageServer.<init>(BioFormatsImageServer.java:179) 
	at qupath.lib.images.servers.bioformats.BioFormatsServerBuilder.buildServer(BioFormatsServerBuilder.java:53) 
	at qupath.lib.images.servers.ImageServerProvider.buildServer(ImageServerProvider.java:166) 
	at qupath.QuPath.main(QuPath.java:150) 
16:23:07.721 [main] [WARN ] loci.formats.Memoizer - file deletion failed D:\QMDownload\5\os\.OS-3.vsi.bfmemo 
16:23:07.761 [main] [INFO ] loci.formats.ImageReader - CellSensReader initializing D:\QMDownload\5\os\OS-3.vsi 
16:23:08.111 [main] [INFO ] q.l.i.servers.ImageServerProvider - Returning server: Bio-Formats for D:\\QMDownload\\5\\os\\OS-3.vsi 
Height:79322 
Width:47938 
ZSlices:1 
nChannels:3 
nTimepoints:1 
TimeUnit:SECONDS 
Magnification:20 
HasPixelSizeMicrons:true 
PixelHeightMicrons:0.34605476573810834 
PixelWidthMicrons:0.34605192018927855 
PixelZSpacingMicrons:NaN 
imgpathURL = file:/D:/QMDownload/5/os/OS-3.vsi#1 
imgpathURLdeal = file:/D:/QMDownload/5/os/OS-3.vsi#1 
imgpathStr = file:/D:/QMDownload/5/os/OS-3.vsi#1 
imgpathStrTrimL = D:/QMDownload/5/os/OS-3.vsi#1 
imgpathStrTrimLR = D:/QMDownload/5/os/OS-3.vsi 
dirOutput = D:/QMDownload/5/os/OS-3_tif 
txtPath=D:/QMDownload/5/os/OS-3.txt 
txtfile exists, but will be overwrite 
16:23:09.758 [main] [WARN ] loci.formats.Memoizer - deleting invalid memo file: D:\QMDownload\5\os\.OS-3.vsi.bfmemo 
com.esotericsoftware.kryo.KryoException: Encountered unregistered class ID: 429
Serialization trace:
service (loci.formats.in.OperettaReader)
readers (loci.formats.ImageReader)
reader (loci.formats.DimensionSwapper)
reader (loci.formats.FileStitcher)
helper (loci.formats.in.FilePatternReader)
readers (loci.formats.ImageReader) 
	at com.esotericsoftware.kryo.util.DefaultClassResolver.readClass(DefaultClassResolver.java:119) 
	at com.esotericsoftware.kryo.Kryo.readClass(Kryo.java:641) 
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.read(DefaultArraySerializers.java:375) 
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.read(DefaultArraySerializers.java:289) 
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:679) 
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:106) 
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:528) 
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:679) 
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.read(DefaultArraySerializers.java:378) 
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.read(DefaultArraySerializers.java:289) 
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:679) 
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:106) 
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:528) 
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:679) 
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:106) 
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:528) 
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:679) 
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:106) 
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:528) 
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:679) 
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:106) 
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:528) 
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:679) 
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.read(DefaultArraySerializers.java:378) 
	at com.esotericsoftware.kryo.serializers.DefaultArraySerializers$ObjectArraySerializer.read(DefaultArraySerializers.java:289) 
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:679) 
	at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:106) 
	at com.esotericsoftware.kryo.serializers.FieldSerializer.read(FieldSerializer.java:528) 
	at com.esotericsoftware.kryo.Kryo.readObject(Kryo.java:657) 
	at loci.formats.Memoizer$KryoDeser.loadReader(Memoizer.java:163) 
	at loci.formats.Memoizer.loadMemo(Memoizer.java:888) 
	at loci.formats.Memoizer.setId(Memoizer.java:666) 
	at qupath.lib.images.servers.bioformats.BioFormatsImageServer$BioFormatsReaderManager.createReader(BioFormatsImageServer.java:1141) 
	at qupath.lib.images.servers.bioformats.BioFormatsImageServer$BioFormatsReaderManager.createReader(BioFormatsImageServer.java:1083) 
	at qupath.lib.images.servers.bioformats.BioFormatsImageServer$BioFormatsReaderManager.getReaderForThread(BioFormatsImageServer.java:966) 
	at qupath.lib.images.servers.bioformats.BioFormatsImageServer.getBufferedImageReader(BioFormatsImageServer.java:548) 
	at qupath.lib.images.servers.bioformats.BioFormatsImageServer.readTile(BioFormatsImageServer.java:579) 
	at qupath.lib.images.servers.AbstractTileableImageServer.getTile(AbstractTileableImageServer.java:61) 
	at qupath.lib.images.servers.AbstractTileableImageServer.readBufferedImage(AbstractTileableImageServer.java:131) 
	at qupath.lib.images.servers.AbstractTileableImageServer.readBufferedImage(AbstractTileableImageServer.java:19) 
	at qupath.imagej.helpers.IJTools.convertToImagePlus(IJTools.java:536) 
	at qupath.imagej.helpers.IJTools.convertToImagePlus(IJTools.java:573) 
	at qupath.imagej.helpers.IJTools$convertToImagePlus.call(Unknown Source) 
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) 
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115) 
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:135) 
	at Script1.run(Script1.groovy:240) 
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:317) 
	at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:155) 
	at qupath.QuPath.main(QuPath.java:161) 
16:23:09.798 [main] [WARN ] loci.formats.Memoizer - file deletion failed D:\QMDownload\5\os\.OS-3.vsi.bfmemo 
16:23:09.838 [main] [INFO ] loci.formats.ImageReader - CellSensReader initializing D:\QMDownload\5\os\OS-3.vsi 
a Top break at idx from:[0+=1] 
a Top break at idx from:[0+=1] 
a Top break at idx from:[0+=1] 
a Top break at idx from:[0+=1] 
............bTop is:0 
a Bottom break at idx from:[0+=1] 
a Bottom break at idx from:[0+=1] 
a Bottom break at idx from:[0+=1] 
a Bottom break at idx from:[0+=1] 
............bBottom is:79321 
a Left break at idx from:[0+=1] 
a Left break at idx from:[0+=1] 
a Left break at idx from:[0+=1] 
a Left break at idx from:[0+=1] 
............bLeft is:0 
a Right break at idx from:[0+=1] 
a Right break at idx from:[0+=1] 
a Right break at idx from:[0+=1] 
a Right break at idx from:[0+=1] 
............bRight is:47937 
Written tile 1 to D:\QMDownload\5\os\OS-3_tif\OS-3.vsi (d=1.00, x=0, y=0, w=2000, h=1500, z=0).tif 
Written tile 2 to D:\QMDownload\5\os\OS-3_tif\OS-3.vsi (d=1.00, x=2000, y=0, w=2000, h=1500, z=0).tif 
Written tile 3 to D:\QMDownload\5\os\OS-3_tif\OS-3.vsi (d=1.00, x=4000, y=0, w=2000, h=1500, z=0).tif 
Written tile 4 to D:\QMDownload\5\os\OS-3_tif\OS-3.vsi (d=1.00, x=6000, y=0, w=2000, h=1500, z=0).tif 
...
```

**Comment by petebankhead** [comment]
Aside from the messages in the log, is this causing any problems? As you describe, Bio-Formats tries to delete the file - in which case it isn't really a fixable QuPath bug if this fails.

bfmemo files are not expected to be deleted after closing QuPath, but rather retained so that the image can be opened more quickly later. You can turn of the use of memoization in the QuPath preferences.

There is further info at https://github.com/qupath/qupath-bioformats-extension - but _don't install this extension with v0.2.0!_ It doesn't work, isn't necessary and can cause conflicts.

**Comment by rmd06** [comment]
This works very well and does not have any problems.
