### ISSUE TITLE
IF channel names generated by Add Intensity Features

### ISSUE THREAD

**Issue by Svidro** [qupath/qupath#301]
QP 0.2.0m2
![image](https://user-images.githubusercontent.com/23145209/55431995-a375f880-5546-11e9-8ebd-a9f9aa4d29d9.png)

Channel name disconnect between what is listed in the Compute Intensity Features dialog (channel names), channels listed for cell detection (here Channel 1,2 and 3), and channels listed after the Compute (here, Channel 0, 1 and 2). If channel names are going to be used in addition to the channel counts, it might be useful to add the channel counts to the dialog box as well [so the first line would read "DAPI (Channel 1)"].

Minor: Menu says "Add intensity features" while dialog title is "Compute intensity features"

**Comment by Svidro** [comment]
Additionally, I am not sure if this feature could be parallelized?

**Comment by petebankhead** [comment]
Thanks, this definitely needs changed. My guess is it happened while I was trying to lift the limit of measured channels (previously it was fixed at 8).

Now that channel names can be stored, do you think this should be used in the measurements, e.g. 'DAPI (C1)' rather than the number alone? If so, I'd say this should be consistent between intensity measurements & cell detection and both ought to be updated. Any classifiers that use older names would break, but that may not be so bad... inasmuch as it's not a good idea to reuse classifiers across versions (at least where there has been major changes in between).

It _does_ mean that channel names must be correct from the start.  So they should be more easily fix-able than they currently are.

One concern I had about doing this was that channel names could be weird, or wrong, or duplicated, or empty... but perhaps appending 'C1', 'C2' etc. is enough to mitigate this potential issue.  Or 'Channel 1' etc. but the names risk becoming even more long and unwieldy.

> Additionally, I am not sure if this feature could be parallelized?
It already is... should should see a difference if you reduce the number of parallel threads to 1. Or is there something I've missed?

**Comment by petebankhead** [comment]
Regarding parallelization, I suspect you're rather suffering a performance issue that emerges when requesting many small regions from a multichannel fluorescence image. Cropping the requested region is... not fast.  I'll investigate that too.

**Comment by Svidro** [comment]
I can very easily see the concerns regarding included channel names, and that was one of my concerns! I think the ability to edit the names, and, potentially, copy measurement names out of the measurements list in the interface would go some ways to helping mitigate that. For dialog boxes and convenience sake, I was thinking that it might help to keep Channel1/2/3 etc, but also include a little square showing each channel's display color, which should help with defining the dimensions and not having text run all over the place. That would probably stop working well around 10+ channels though.

Oh, or maybe for the dialog boxes, restrict the length of the text for the channel name, and use a separate column for the Channel 1/C1/Ch1, or whatever, so regardless of what gets chopped off for the name, that part is always visible? Kind of early morning stream of consciousness here.

**Comment by Svidro** [comment]
And if you wanted to unify all of the dialogs and measurements to include the (C1), maybe tokenize it off the end (beginning may be better?) into another column for the dialogs, so that it always shows.

**Comment by Svidro** [comment]
Update. This still exists in 0.2.0m3, and with the additional problem that some multichannel images generate the following error.

ERROR: Error running plugin: java.lang.IllegalArgumentException: No boolean parameter with key 'doMedian'
    at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
    at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
    at qupath.lib.plugins.AbstractPluginRunner.awaitCompletion(AbstractPluginRunner.java:193)
    at qupath.lib.plugins.AbstractPluginRunner.runTasks(AbstractPluginRunner.java:157)
    at qupath.lib.gui.plugins.PluginRunnerFX.runTasks(PluginRunnerFX.java:94)
    at qupath.lib.plugins.AbstractPlugin.runPlugin(AbstractPlugin.java:156)
    at qupath.lib.algorithms.IntensityFeaturesPlugin.runPlugin(IntensityFeaturesPlugin.java:336)
    at qupath.lib.gui.plugins.ParameterDialogWrapper$1.run(ParameterDialogWrapper.java:185)
    at java.base/java.lang.Thread.run(Unknown Source)
  Caused by No boolean parameter with key 'doMedian'        at qupath.lib.plugins.parameters.ParameterList.getBooleanParameterValue(ParameterList.java:379)
        at qupath.lib.plugins.parameters.ParameterList.getBooleanParameterValue(ParameterList.java:417)
        at qupath.lib.algorithms.IntensityFeaturesPlugin$MedianFeatureComputer.addMeasurements(IntensityFeaturesPlugin.java:945)
        at qupath.lib.algorithms.IntensityFeaturesPlugin.processObject(IntensityFeaturesPlugin.java:594)
        at qupath.lib.algorithms.IntensityFeaturesPlugin$IntensityFeatureRunnable.run(IntensityFeaturesPlugin.java:429)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

**Comment by petebankhead** [comment]
When is the error generated?

**Comment by Svidro** [comment]
Any time I click Run for Add Intensity Features and have a one channel
selected and am running at least the mean. But so far only in the LuCa
image (of the few I have tested). Fairly regular cell generation parameters.

**Comment by petebankhead** [comment]
Forgot to reference if in the commit message, but this deals with the problem by using the stored channel names instead: https://github.com/petebankhead/qupath/commit/0caf3c68a766035a9c77a64c6a6d8b65464fd2b2

And here the channel names are applied within the cell detection command, rather than 'Channel 1', 'Channel 2' etc.:
https://github.com/petebankhead/qupath/commit/79228883d06e4cf36ed6477cc0e226522c3de1d8
