### ISSUE TITLE
ImagePlusServer alterations

### ISSUE THREAD

**Issue by nicholasjmorriss** [qupath/qupath#309]
Hi All, I am using code from v1.02 and having trouble switching from the ImagePlusServer that I was using. I am not sure how to change the following code to adapt to v2. The function is to export .tif files of various sizes into the project folder. 

The code is here: 
```groovy
//Exporting Image as .tif files
import ij.IJ
import ij.ImagePlus
import qupath.lib.gui.ImageWriterTools
import qupath.imagej.helpers.IJTools

def imp = IJTools.convertToImagePlus(server, request).getImage()

import qupath.lib.images.servers.ImageServer
import qupath.lib.regions.RegionRequest
import qupath.lib.scripting.QP

import java.awt.image.BufferedImage

/*
 * Adjustable parameters
 */
int tileWidthPixels =1500  // Width of (final) output tile in pixels
int tileHeightPixels = tileWidthPixels // Width of (final) output tile in pixels
double downsample = 70      // Downsampling used when extracting tiles
String format = "tif"       // Format of the output image - TIFF or ZIP is best for ImageJ to preserve pixel sizes
String dirOutput =('D:/QUPATH 2 - AT8/Exported Images' )     // BE SURE TO ADD AN OUTPUT DIRECTORY HERE!!!

int maxErrors = 20          // Maximum number of errors... to avoid trying something doomed forever
int minImageDimension = 16  // If a tile will have a width or height < minImageDimension, it will be skipped
                            // This is needed to avoid trying to read/write images that are too tiny to be useful (and may even cause errors)

//-------------------------------------------------------

/*
 * Processing
 */

// Check we have an output directory
if (dirOutput == null) {
    println("Be sure to set the 'dirOutput' variable!")
    return
}

// Initialize error counter
int nErrors = 0

// Get the image server
ImageServer<BufferedImage> serverOriginal = QP.getCurrentImageData().getServer()

// Get an ImagePlus server
ImagePlusServer server = ImagePlusServerBuilder.ensureImagePlusWholeSlideServer(serverOriginal)

// Ensure convert the format to a file extension
String ext
if (format.startsWith("."))
    ext = format.substring(1).toLowerCase()
else
    ext = format.toLowerCase()

// Extract useful variables
String path = server.getPath()
String serverName = serverOriginal.getShortServerName()
double tileWidth = tileWidthPixels * downsample
double tileHeight = tileHeightPixels * downsample

// Loop through the image - including z-slices (even though there's normally only one...)
int counter = 0;
for (int z = 0; z < server.nZSlices(); z++) {
    for (double y = 0; y < server.getHeight(); y += tileHeight) {

        // Compute integer y coordinates
        int yi = (int)(y + 0.5)
        int y2i = (int)Math.min((int)(y + tileHeight + 0.5), server.getHeight());
        int hi = y2i - yi

        // Check if we requesting a region that is too small
        if (hi / downsample < minImageDimension) {
            println("Image dimension < " + minImageDimension + " - skipping row")
            continue
        }

        for (double x = 0; x < server.getWidth(); x += tileWidth) {

            // Compute integer x coordinates
            int xi = (int)(x + 0.5)
            int x2i = (int)Math.min((int)(x + tileWidth + 0.5), server.getWidth());
            int wi = x2i - xi

            // Create request
            RegionRequest request = RegionRequest.createInstance(path, downsample, xi, yi, wi, hi, z, 0)

            // Check if we requesting a region that is too small
            if (wi / downsample < minImageDimension) {
                // Only print warning if we've not skipped this before
                if (y > 0)
                    println("Image dimension < " + minImageDimension + " - skipping column")
                continue
            }

            // Surround with try/catch in case the server gives us trouble
            try {
                // Put at top of file for neater code...
                ext = ".jpg"
                imageData = getCurrentImageData()
                overlayOptions = getCurrentViewer().getOverlayOptions()
                
                // Write out the region with overlay
                String name = String.format("%s (d=%.2f, x=%d, y=%d, w=%d, h=%d, z=%d).%s", serverName, downsample, xi, yi, wi, hi, z, ext)
                File file = new File(dirOutput, name)
                ImageWriterTools.writeImageRegionWithOverlay(imageData, overlayOptions, request, file.getAbsolutePath())

                // Print progress
                counter++
                println("Written tile " + counter + " to " + file.getAbsolutePath())
            }
             catch (Exception e) {
                // Check if we have had a sufficient number of errors to just give up
                nErrors++;
                if (nErrors > maxErrors) {
                    println("Maximum number of errors exceeded - aborting...")
                    return
                }
                e.printStackTrace()
            }
        }
    }
}

```

The error is on line 91 when I try to access the ImagePlusServer server, which obviously doesn't exist anymore. 

```
ERROR: Error at line 7: No such property: server for class: Script48

ERROR: Script error
    at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:65)
    at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:51)
    at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:309)
    at Script48.run(Script48.groovy:8)
    at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:317)
    at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:155)
    at qupath.lib.gui.scripting.DefaultScriptEditor.executeScript(DefaultScriptEditor.java:767)
    at qupath.lib.gui.scripting.DefaultScriptEditor.executeScript(DefaultScriptEditor.java:697)
    at qupath.lib.gui.scripting.DefaultScriptEditor.executeScript(DefaultScriptEditor.java:677)
    at qupath.lib.gui.scripting.DefaultScriptEditor$2.run(DefaultScriptEditor.java:1034)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)
```

Thanks!

**Comment by petebankhead** [comment]
(I edited the post to make the code easier to read)

The problem is that
```groovy
def imp = IJTools.convertToImagePlus(server, request).getImage()
```
occurs too early. You need to run it after this line
```groovy
ImagePlusServer server = ImagePlusServerBuilder.ensureImagePlusWholeSlideServer(serverOriginal)
```

> In order to make it easier to find answers in the future, please post future questions at https://forum.image.sc/tags/qupath and only use GitHub Issues to report QuPath bugs.

**Comment by nicholasjmorriss** [comment]
I edited the code to try that but I still got the following error: 

`ERROR: Error: startup failed:
Script53.groovy: 45: unable to resolve class ImagePlusServer 
 @ line 45, column 17.
   ImagePlusServer server = ImagePlusServerBuilder.ensureImagePlusWholeSlideServer(serverOriginal)
                   ^

1 error


ERROR: Script error
    at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:311)
    at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:980)
    at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:647)
    at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:596)
    at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:390)
    at groovy.lang.GroovyClassLoader.access$300(GroovyClassLoader.java:89)
    at groovy.lang.GroovyClassLoader$5.provide(GroovyClassLoader.java:330)
    at groovy.lang.GroovyClassLoader$5.provide(GroovyClassLoader.java:327)
    at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:147)
    at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:325)
    at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:309)
    at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:251)
    at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.getScriptClass(GroovyScriptEngineImpl.java:331)
    at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:153)
    at qupath.lib.gui.scripting.DefaultScriptEditor.executeScript(DefaultScriptEditor.java:767)
    at qupath.lib.gui.scripting.DefaultScriptEditor.executeScript(DefaultScriptEditor.java:697)
    at qupath.lib.gui.scripting.DefaultScriptEditor.executeScript(DefaultScriptEditor.java:677)
    at qupath.lib.gui.scripting.DefaultScriptEditor$2.run(DefaultScriptEditor.java:1034)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by petebankhead** [comment]
Sorry, I didn't read closely enough.
```groovy
ImagePlusServer server = ImagePlusServerBuilder.ensureImagePlusWholeSlideServer(serverOriginal)
```
should be removed entirely. Then you can try this
```groovy
// Get the image server
ImageServer<BufferedImage> serverOriginal = QP.getCurrentImageData().getServer()

// Get an ImagePlus
def imp = IJTools.convertToImagePlus(serverOriginal, request).getImage()
```
The previous error was because you were using `server` before it was defined. But actually with the update in v0.2.0 you don't need to define `server` separately from `serverOriginal` at all.

Note that v0.2.0 is a work in progress and will change further in various ways.  I wouldn't really recommending switching to it and spending much time updating scripts yet.

**Comment by nicholasjmorriss** [comment]
Hi Pete, thanks for all your help so far! I am getting a somewhat different error now. 

Here are the relevant lines of code: 
`// Get the image server
ImageServer<BufferedImage> serverOriginal = QP.getCurrentImageData().getServer()

// Get an ImagePlus
def imp = IJTools.convertToImagePlus(serverOriginal, request).getImage()

`

And here is the error message I am getting. 
`ERROR: Error at line 71: No such property: request for class: Script1

ERROR: Script error` 

With a long following, which I can attach if you want. 

Sorry if this is a silly question, I appreciate the help!

**Comment by Svidro** [comment]
I often have trouble with new code without a working example, so while I am not sure exactly what you have in your script, I just partially finished my first script (for version 0.2.0) that uses ImageServers. Maybe it will help. 
https://gist.githubusercontent.com/Svidro/68dd668af64ad91b2f76022015dd8a45/raw/91cd2277003d613cf96f85e48a89c326f9f80b81/Colocalization%2520test.groovy

**Comment by petebankhead** [comment]
Sorry, I again answered too quickly without time to test the code.  This script at least runs, although I'm not sure if it's what you want or not:
```groovy
//Exporting Image as .tif files
import qupath.lib.gui.ImageWriterTools

import qupath.lib.images.servers.ImageServer
import qupath.lib.regions.RegionRequest
import qupath.lib.scripting.QP

import java.awt.image.BufferedImage

/*
 * Adjustable parameters
 */
int tileWidthPixels =1500  // Width of (final) output tile in pixels
int tileHeightPixels = tileWidthPixels // Width of (final) output tile in pixels
double downsample = 70      // Downsampling used when extracting tiles
String format = "tif"       // Format of the output image - TIFF or ZIP is best for ImageJ to preserve pixel sizes
String dirOutput = buildFilePath(PROJECT_BASE_DIR, 'something else')     // BE SURE TO ADD AN OUTPUT DIRECTORY HERE!!!
mkdirs(dirOutput)

int maxErrors = 20          // Maximum number of errors... to avoid trying something doomed forever
int minImageDimension = 16  // If a tile will have a width or height < minImageDimension, it will be skipped
                            // This is needed to avoid trying to read/write images that are too tiny to be useful (and may even cause errors)

//-------------------------------------------------------

/*
 * Processing
 */

// Check we have an output directory
if (dirOutput == null) {
    println("Be sure to set the 'dirOutput' variable!")
    return
}

// Initialize error counter
int nErrors = 0

// Get the image server
ImageServer<BufferedImage> server = QP.getCurrentImageData().getServer()

// Ensure convert the format to a file extension
String ext
if (format.startsWith("."))
    ext = format.substring(1).toLowerCase()
else
    ext = format.toLowerCase()

// Extract useful variables
String path = server.getPath()
String serverName = server.getShortServerName()
double tileWidth = tileWidthPixels * downsample
double tileHeight = tileHeightPixels * downsample

// Loop through the image - including z-slices (even though there's normally only one...)
int counter = 0;
for (int z = 0; z < server.nZSlices(); z++) {
    for (double y = 0; y < server.getHeight(); y += tileHeight) {

        // Compute integer y coordinates
        int yi = (int)(y + 0.5)
        int y2i = (int)Math.min((int)(y + tileHeight + 0.5), server.getHeight());
        int hi = y2i - yi

        // Check if we requesting a region that is too small
        if (hi / downsample < minImageDimension) {
            println("Image dimension < " + minImageDimension + " - skipping row")
            continue
        }

        for (double x = 0; x < server.getWidth(); x += tileWidth) {

            // Compute integer x coordinates
            int xi = (int)(x + 0.5)
            int x2i = (int)Math.min((int)(x + tileWidth + 0.5), server.getWidth());
            int wi = x2i - xi

            // Create request
            RegionRequest request = RegionRequest.createInstance(path, downsample, xi, yi, wi, hi, z, 0)

            // Check if we requesting a region that is too small
            if (wi / downsample < minImageDimension) {
                // Only print warning if we've not skipped this before
                if (y > 0)
                    println("Image dimension < " + minImageDimension + " - skipping column")
                continue
            }

            // Surround with try/catch in case the server gives us trouble
            try {
                // Put at top of file for neater code...
                ext = ".jpg"
                imageData = getCurrentImageData()
                overlayOptions = getCurrentViewer().getOverlayOptions()
                
                // Write out the region with overlay
                String name = String.format("%s (d=%.2f, x=%d, y=%d, w=%d, h=%d, z=%d).%s", serverName, downsample, xi, yi, wi, hi, z, ext)
                File file = new File(dirOutput, name)
                ImageWriterTools.writeImageRegionWithOverlay(imageData, overlayOptions, request, file.getAbsolutePath())

                // Print progress
                counter++
                println("Written tile " + counter + " to " + file.getAbsolutePath())
            }
             catch (Exception e) {
                // Check if we have had a sufficient number of errors to just give up
                nErrors++;
                if (nErrors > maxErrors) {
                    println("Maximum number of errors exceeded - aborting...")
                    return
                }
                e.printStackTrace()
            }
        }
    }
}
```
The original version contained quite a bit of ImageJ-related stuff but on closer inspection I'm not sure why since it actually writes JPEGs instead of ImageJ TIFFs.

If the above script doesn't work, I think it would be best to start a new discussion at https://forum.image.sc/tags/qupath  describing what it should do and perhaps there is an easier way to get there.

**Comment by nicholasjmorriss** [comment]
This is perfect. Thanks a ton.
