### ISSUE TITLE
Problem with opening files

### ISSUE THREAD

**Issue by souzavet** [qupath/qupath#312]
I'm learning about Qupath (v0.2.0-m2) and can not open any image (.ZVI or .TFI). The error log is as follows:
----
INFO: Refreshing extensions in C:\Users\souza\QuPath\extensions
INFO: Added extension: C:\Users\souza\QuPath\extensions\bioformats_package.jar
INFO: Added extension: C:\Users\souza\QuPath\extensions\qupath-bioformats-extension.jar
INFO: Added extension: C:\Users\souza\QuPath\extensions\qupath-extension-bioformats.jar
INFO: Bio-Formats version 6.0.1
INFO: OpenSlide version 3.4.1
INFO: Selected style: null
INFO: Performing update check...
INFO: Starting QuPath with parameters: []
ERROR: QuPath exception
    at qupath.lib.images.servers.ImageServerProvider.lambda$buildServer$0(ImageServerProvider.java:147)
    at java.base/java.util.TimSort.binarySort(TimSort.java:296)
    at java.base/java.util.TimSort.sort(TimSort.java:221)
    at java.base/java.util.Arrays.sort(Arrays.java:1515)
    at java.base/java.util.ArrayList.sort(ArrayList.java:1749)
    at java.base/java.util.Collections.sort(Collections.java:177)
    at qupath.lib.images.servers.ImageServerProvider.buildServer(ImageServerProvider.java:146)
    at qupath.lib.gui.QuPathGUI.openImage(QuPathGUI.java:2450)
    at qupath.lib.gui.QuPathGUI.openImage(QuPathGUI.java:2369)
    at qupath.lib.gui.commands.OpenCommand.run(OpenCommand.java:51)
    at qupath.lib.gui.QuPathGUI.lambda$createCommandAction$50(QuPathGUI.java:3412)
    at org.controlsfx.control.action.Action.handle(Action.java:419)
    at org.controlsfx.control.action.Action.handle(Action.java:64)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.control.MenuItem.fire(MenuItem.java:465)
    at com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1380)
    at com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.lambda$createChildren$12(ContextMenuContent.java:1333)
    at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene$MouseHandler.process(Scene.java:3851)
    at javafx.scene.Scene$MouseHandler.access$1200(Scene.java:3579)
    at javafx.scene.Scene.processMouseEvent(Scene.java:1849)
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2588)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:397)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:434)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:390)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:433)
    at com.sun.glass.ui.View.handleMouseEvent(View.java:556)
    at com.sun.glass.ui.View.notifyMouse(View.java:942)
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
    at java.base/java.lang.Thread.run(Thread.java:834)

******Desktop (please complete the following information)**
 - OS: Windows 10 (home) - 64 bits - Hardware: Intel I5, CPU 250 Ghz, Memória RAM (8gb)     
 - QuPath Version [(v0.2.0-m2)]

           I imagine the answer is simple but I can not solve this problem.
Best Regards
Marcos Souza

**Comment by petebankhead** [comment]
It looks like the problem is QuPath is finding three different Bio-Formats extensions and getting horribly confused. As the [important text that appears when you start v0.2.0-m2 says](https://github.com/qupath/qupath/blob/da83ef9e809e18e4a99bf8510c03f42217bc1579/STARTUP.md)
```
* Bio-Formats is included now by default - the old separate extension isn't needed (and isn't compatible).
```
There are two options to fix it:
* delete the three files with 'bioformats' in the name from `C:\Users\souza\QuPath\extensions\` 
* go to _Edit &rarr; Reset preferences_ in v0.2.0-m2 to cause that version of QuPath to forget the location of the directory containing the extensions

The second suggestion should allow the old extensions to still work with v0.1.2 but not confuse v0.2.0-m2.

> Either way, you should probably remove `C:\Users\souza\QuPath\extensions\qupath-bioformats-extension.jar`... which is a result of me misnaming the file once (it should always have been `qupath-extension-bioformats.jar`).

**Comment by souzavet** [comment]
Hi, I tried the first option and solved the problem. Thank you
Marcos
