### ISSUE TITLE
Error with opening image

### ISSUE THREAD

**Issue by AnesthesiaNeurotoxicity** [qupath/qupath#330]
Hello,

I installed QuPath and the bioformats plugin on a new computer.  When I try to open a .czi image, I get the error below and the image cannot be opened.

What can be the problem and the solution?

Thanks in advance!

INFO: Refreshing extensions in C:\Users\u0127462\QuPath\extensions
INFO: Added extension: C:\Users\u0127462\QuPath\extensions\bioformats_package.jar
INFO: Added extension: C:\Users\u0127462\QuPath\extensions\qupath-extension-bioformats.jar
INFO: Bio-Formats version 6.1.1
INFO: Selected style: Modena Light
INFO: Performing update check...
INFO: Starting QuPath with parameters: []
INFO: ZeissCZIReader initializing E:\Konijnen\Histologie\5\6.czi
INFO: Generating memoization file E:\Konijnen\Histologie\5\.6.czi.bfmemo (9.23 MB)
INFO: Returning server: Bio-Formats for E:\Konijnen\Histologie\5\6.czi
ERROR: java.lang.UnsatisfiedLinkError: ome.jxrlib.JXRJNI.new_DecodeContext()J
ERROR: QuPath exception
    at ome.jxrlib.JXRJNI.new_DecodeContext(Native Method)
    at ome.jxrlib.DecodeContext.<init>(DecodeContext.java:43)
    at ome.jxrlib.AbstractDecode.decodeFirstFrame(AbstractDecode.java:101)
    at ome.jxrlib.Decode.decodeFirstFrame(Decode.java:51)
    at loci.formats.services.JPEGXRServiceImpl.decompress(JPEGXRServiceImpl.java:54)
    at loci.formats.codec.JPEGXRCodec.decompress(JPEGXRCodec.java:84)
    at loci.formats.in.ZeissCZIReader$SubBlock.readPixelData(ZeissCZIReader.java:3820)
    at loci.formats.in.ZeissCZIReader$SubBlock.readPixelData(ZeissCZIReader.java:3776)
    at loci.formats.in.ZeissCZIReader$SubBlock.readPixelData(ZeissCZIReader.java:3771)
    at loci.formats.in.ZeissCZIReader.openBytes(ZeissCZIReader.java:394)
    at loci.formats.FormatReader.openBytes(FormatReader.java:878)
    at loci.formats.ImageReader.openBytes(ImageReader.java:445)
    at loci.formats.ReaderWrapper.openBytes(ReaderWrapper.java:334)
    at loci.formats.ReaderWrapper.openBytes(ReaderWrapper.java:334)
    at loci.formats.gui.BufferedImageReader.openImage(BufferedImageReader.java:86)
    at qupath.lib.images.servers.BioFormatsImageServer.readBufferedImage(BioFormatsImageServer.java:683)
    at qupath.lib.images.servers.BioFormatsImageServer.readBufferedImage(BioFormatsImageServer.java:95)
    at qupath.lib.images.stores.AbstractImageRegionStore.getThumbnail(AbstractImageRegionStore.java:354)
    at qupath.lib.gui.QuPathGUI.createNewImageData(QuPathGUI.java:2269)
    at qupath.lib.gui.QuPathGUI.createNewImageData(QuPathGUI.java:2258)
    at qupath.lib.gui.QuPathGUI.openImage(QuPathGUI.java:2236)
    at qupath.lib.gui.QuPathGUI.openImage(QuPathGUI.java:2152)
    at qupath.lib.gui.commands.OpenCommand.run(OpenCommand.java:51)
    at qupath.lib.gui.QuPathGUI.lambda$createCommandAction$46(QuPathGUI.java:3122)
    at org.controlsfx.control.action.Action.handle(Action.java:419)
    at org.controlsfx.control.action.Action.handle(Action.java:64)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.control.MenuItem.fire(MenuItem.java:462)
    at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1405)
    at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.lambda$createChildren$343(ContextMenuContent.java:1358)
    at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
    at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
    at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:380)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:294)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:416)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:415)
    at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
    at com.sun.glass.ui.View.notifyMouse(View.java:937)
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
    at java.lang.Thread.run(Thread.java:745)

**Comment by Svidro** [comment]
It doesn't look like you included most of the information requested in the initial form. Without that information I could only guess, but my guess would be that you are using 0.2.0m2.

**Comment by petebankhead** [comment]
See https://github.com/qupath/qupath/wiki/Supported-image-formats#zeiss-czi

**Comment by AnesthesiaNeurotoxicity** [comment]
What do you mean with the information in the initial form?
Actually, I already followed the guideliness of that site.

**Comment by Svidro** [comment]
All of this stuff. If it isn't showing up for new bug reports on your system, that would be good to know too.
![image](https://user-images.githubusercontent.com/23145209/59469319-59807d00-8de9-11e9-8bc6-7bd600843de3.png)

**Comment by Svidro** [comment]
The most useful bits of information there are probably the version, OS, and any information on what you have attempted so far.

**Comment by petebankhead** [comment]
@AnesthesiaNeurotoxicity did you install the _Visual Studio 2015 C++ Redistributable_ as specified in the [link I posted above](https://github.com/qupath/qupath/issues/330#issuecomment-501853968)?

The Bio-Formats website mentions the need for this to handle CZI files with JPEG-XR compression: https://docs.openmicroscopy.org/bio-formats/6.1.0/formats/zeiss-czi.html

**Comment by petebankhead** [comment]
Closed issue because of lack of activity, please reopen if there is further information.
