### ISSUE TITLE
SLICs not working in m3

### ISSUE THREAD

**Issue by saramcardle** [qupath/qupath#344]
SLIC superpixel detection has stopped working in m3. It divides the large annotation into tiles, and then just stops. According to Svidro, it produces this error in the log: 

ERROR: Error running plugin: java.lang.IllegalArgumentException: No boolean parameter with key 'doMerge'
    at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
    at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
    at qupath.lib.plugins.AbstractPluginRunner.awaitCompletion(AbstractPluginRunner.java:193)
    at qupath.lib.plugins.AbstractPluginRunner.runTasks(AbstractPluginRunner.java:157)
    at qupath.lib.gui.plugins.PluginRunnerFX.runTasks(PluginRunnerFX.java:94)
    at qupath.lib.plugins.AbstractPlugin.runPlugin(AbstractPlugin.java:156)
    at qupath.lib.gui.plugins.ParameterDialogWrapper$1.run(ParameterDialogWrapper.java:185)
    at java.base/java.lang.Thread.run(Unknown Source)
  Caused by No boolean parameter with key 'doMerge'        at qupath.lib.plugins.parameters.ParameterList.getBooleanParameterValue(ParameterList.java:379)
        at qupath.lib.plugins.parameters.ParameterList.getBooleanParameterValue(ParameterList.java:417)
        at qupath.imagej.superpixels.SLICSuperpixelsPlugin$SLICSuperpixelDetector.runDetection(SLICSuperpixelsPlugin.java:281)
        at qupath.lib.plugins.DetectionPluginTools$DetectionRunnable.run(DetectionPluginTools.java:132)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)

**Comment by petebankhead** [comment]
Thanks, this should be resolved in the next milestone (v0.2.0-m4).
