### ISSUE TITLE
Qupath error when changing view on a czi slide

### ISSUE THREAD

**Issue by bpavie** [qupath/qupath#35]
Since the released of bioformat 5.3.0, we can now open czi axioscan slides, but today I got an error while changing the Scene in image list:

This problem do not occur on other computer with the same installation files.

Here is the error logs:

`
INFO: Refreshing extensions in C:\Users\xxxx\QuPath\extensions
INFO: Added extension: C:\Users\xxxx\QuPath\extensions\bioformats_package.jar
INFO: Added extension: C:\Users\xxxx\QuPath\extensions\qupath-extension-bioformats.jar
INFO: Selected style: Modena Light
INFO: Performing update check...
INFO: Starting QuPath with parameters: []
ERROR: Could not load OpenSlide native library
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
    at java.lang.Runtime.loadLibrary0(Runtime.java:870)
    at java.lang.System.loadLibrary(System.java:1122)
    at org.openslide.OpenSlideJNI.<clinit>(OpenSlideJNI.java:55)
    at org.openslide.OpenSlide.<clinit>(OpenSlide.java:53)
    at qupath.lib.images.servers.OpenslideImageServer.<init>(OpenslideImageServer.java:91)
    at qupath.lib.images.servers.OpenslideServerBuilder.buildServer(OpenslideServerBuilder.java:47)
    at qupath.lib.images.servers.ImageServerProvider.buildServer(ImageServerProvider.java:115)
    at qupath.lib.gui.QuPathGUI.openImage(QuPathGUI.java:2227)
    at qupath.lib.gui.viewer.DragDropFileImportListener.handleFileDrop(DragDropFileImportListener.java:253)
    at qupath.lib.gui.viewer.DragDropFileImportListener.handle(DragDropFileImportListener.java:115)
    at qupath.lib.gui.viewer.DragDropFileImportListener.handle(DragDropFileImportListener.java:1)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene$DnDGesture.fireEvent(Scene.java:2933)
    at javafx.scene.Scene$DnDGesture.processTargetDrop(Scene.java:3159)
    at javafx.scene.Scene$DnDGesture.access$6400(Scene.java:2909)
    at javafx.scene.Scene$DropTargetListener.drop(Scene.java:2873)
    at com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.lambda$handleDragDrop$309(GlassSceneDnDEventHandler.java:95)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.handleDragDrop(GlassSceneDnDEventHandler.java:92)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleDragDrop$363(GlassViewEventHandler.java:700)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleDragDrop(GlassViewEventHandler.java:699)
    at com.sun.glass.ui.View.handleDragDrop(View.java:712)
    at com.sun.glass.ui.View.notifyDragDrop(View.java:1037)
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
    at java.lang.Thread.run(Thread.java:745)
WARN: Error opening C:\Users\xxxx\Documents\data\2016_03_15__4457.czi with ImageJ: Could not open C:\Users\xxxx\Documents\data\2016_03_15__4457.czi with ImageJ
WARN: QuPath Bio-Formats extension is in beta!  Be watchful for bugs...
INFO: ZeissCZIReader initializing C:\Users\xxxx\Documents\data\2016_03_15__4457.czi
INFO: Returning server: Bio-Formats for C:\Users\xxxx\Documents\data\2016_03_15__4457.czi
INFO: Estimating H-DAB staining
INFO: Image data set to ImageData: Brightfield (H-DAB), 2016_03_15__4457
INFO: ZeissCZIReader initializing C:\Users\xxxx\Documents\data\2016_03_15__4457.czi
INFO: ZeissCZIReader initializing C:\Users\xxxx\Documents\data\2016_03_15__4457.czi
INFO: ZeissCZIReader initializing C:\Users\xxxx\Documents\data\2016_03_15__4457.czi
INFO: ZeissCZIReader initializing C:\Users\xxxx\Documents\data\2016_03_15__4457.czi
INFO: ZeissCZIReader initializing C:\Users\xxxx\Documents\data\2016_03_15__4457.czi
INFO: ZeissCZIReader initializing C:\Users\xxxx\Documents\data\2016_03_15__4457.czi
INFO: ZeissCZIReader initializing C:\Users\xxxx\Documents\data\2016_03_15__4457.czi
INFO: ZeissCZIReader initializing C:\Users\xxxx\Documents\data\2016_03_15__4457.czi
INFO: ZeissCZIReader initializing C:\Users\xxxx\Documents\data\2016_03_15__4457.czi
INFO: ZeissCZIReader initializing C:\Users\xxxx\Documents\data\2016_03_15__4457.czi
INFO: ZeissCZIReader initializing C:\Users\xxxx\Documents\data\2016_03_15__4457.czi
INFO: ZeissCZIReader initializing C:\Users\xxxx\Documents\data\2016_03_15__4457.czi
INFO: ZeissCZIReader initializing C:\Users\xxxx\Documents\data\2016_03_15__4457.czi
INFO: ZeissCZIReader initializing C:\Users\xxxx\Documents\data\2016_03_15__4457.czi
INFO: ZeissCZIReader initializing C:\Users\xxxx\Documents\data\2016_03_15__4457.czi
INFO: ZeissCZIReader initializing C:\Users\xxxx\Documents\data\2016_03_15__4457.czi
ERROR: QuPath exception
    at qupath.lib.images.servers.OpenslideImageServer.<init>(OpenslideImageServer.java:91)
    at qupath.lib.images.servers.OpenslideServerBuilder.buildServer(OpenslideServerBuilder.java:47)
    at qupath.lib.images.servers.ImageServerProvider.buildServer(ImageServerProvider.java:115)
    at qupath.lib.gui.QuPathGUI.openImage(QuPathGUI.java:2227)
    at qupath.lib.gui.QuPathGUI.openImage(QuPathGUI.java:2151)
    at qupath.lib.gui.panels.PathImageDetailsPanel.tryToOpenSelectedEntry(PathImageDetailsPanel.java:293)
    at qupath.lib.gui.panels.PathImageDetailsPanel.lambda$2(PathImageDetailsPanel.java:261)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3470)
    at javafx.scene.Scene$ClickGenerator.access$8100(Scene.java:3398)
    at javafx.scene.Scene$MouseHandler.process(Scene.java:3766)
    at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
    at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:380)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:294)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:416)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:415)
    at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
    at com.sun.glass.ui.View.notifyMouse(View.java:937)
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
    at java.lang.Thread.run(Thread.java:745)
ERROR: QuPath exception
    at qupath.lib.images.servers.OpenslideImageServer.<init>(OpenslideImageServer.java:91)
    at qupath.lib.images.servers.OpenslideServerBuilder.buildServer(OpenslideServerBuilder.java:47)
    at qupath.lib.images.servers.ImageServerProvider.buildServer(ImageServerProvider.java:115)
    at qupath.lib.gui.QuPathGUI.openImage(QuPathGUI.java:2227)
    at qupath.lib.gui.QuPathGUI.openImage(QuPathGUI.java:2151)
    at qupath.lib.gui.panels.PathImageDetailsPanel.tryToOpenSelectedEntry(PathImageDetailsPanel.java:293)
    at qupath.lib.gui.panels.PathImageDetailsPanel.lambda$2(PathImageDetailsPanel.java:261)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3470)
    at javafx.scene.Scene$ClickGenerator.access$8100(Scene.java:3398)
    at javafx.scene.Scene$MouseHandler.process(Scene.java:3766)
    at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
    at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:380)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:294)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:416)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:415)
    at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
    at com.sun.glass.ui.View.notifyMouse(View.java:937)
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
    at java.lang.Thread.run(Thread.java:745)
`

**Comment by petebankhead** [comment]
Thanks for reporting this.
Am I right to understand that you have tried this on two Windows computers, and one works but the other does not?

I am not at a computer right now to explore more, but my first question is does the computer that fails to work have a 32-bit version of Windows installed?

From the log, there appears to be a problem loading the OpenSlide library (for which I think only 64-bit support is included). This should not prevent Bio-Formats from opening the image, but conceivably it could since QuPath tries out all the possible libraries that it has when opening a new image.... and if it fails badly enough with its OpenSlide attempt, perhaps it does not try Bio-Formats.

You can prevent this if you find where QuPath is installed, and delete (or copy to another location) the OpenSlide component - probably called qupath-openslide-0.1.1.jar or similar. You can then restart QuPath and try again.

Could you try this and see if it makes a difference? Thanks.

**Comment by bpavie** [comment]
Thanks for your quick answer.
I renamed the file `C:\Program Files\QuPath\app\qupathqupath-extension-openslide-0.1.1.jar` to `qupath-extension-openslide-0.1.1.jar.TMP` as suggested and it solved the issue.
The program is installed with windows 10 64 bits on both computer, I don't know why on one openslide is not correctly loaded.

Many thanks anyway!

**Comment by petebankhead** [comment]
I've made an update that will be included in v0.1.2 so that QuPath can recover more gracefully if it finds that OpenSlide cannot be loaded.  Previously, it recovered only the first time... but subsequent attempts to open images were thwarted by a particularly nasty error - which caused the trouble you found.

Therefore while it still remains a mystery why OpenSlide cannot be used on one of your computers, at least there should be no need to manually disable OpenSlide through renaming from now on.

(Note: I'd recommend uninstalling QuPath before installing the update, since otherwise it is likely that the current files, renamed and not, will hang around within Windows... they shouldn't cause trouble, but uninstalling manually can help make sure.)

**Comment by bpmed12** [comment]
I have the same problem with qu path 0.2.0-m3. BUt changing the qupath-extension-openslide-0.2.0-m3.jar to qupath-extension-openslide-0.2.0-m3.jar.TMP does not work.

**Comment by petebankhead** [comment]
@bpmed12 can you be more specific regarding what exactly you have tried, what does/does not work and any error messages you see?

Note that the 'image list' (under the 'Image' tab) does not exist in m3. So your issue may be different.

Also not that the Bio-Formats extension must *not* be installed with m3 - it is included by default. You may still need to install the visual studio redistributable as specified at https://docs.openmicroscopy.org/bio-formats/6.1.1/formats/zeiss-czi.html
