### ISSUE TITLE
Can't open NDPI images or project containing them

### ISSUE THREAD

**Issue by Rivka1234** [qupath/qupath#351]
Please help!

I have been away on holiday and whilst away the university computer I use was upgraded from windows 7 to windows 10. I am now unable to open any images from my project. These were saved on a external hard drive. The project opens with the thumbnails but when I try to open an image it says 'sorry can't open file'. I copied a single image to my desktop and tried to open that but still got the error. I tried making a new project but it says unable to import file. The file types are NDPI.

I need to get this work complete for my thesis which is due in a month, so please help!!!

INFO: Selected style: Modena Light
INFO: Performing update check...
INFO: Starting QuPath with parameters: []
WARN: Strange 'bits per sample' of 0
WARN: Error opening D:\Rivka\nanozoomer\Scans RL 2\Exp 5 (LI)\A3 LI 03.ndpi with ImageJ: Could not open D:\Rivka\nanozoomer\Scans RL 2\Exp 5 (LI)\A3 LI 03.ndpi with ImageJ
ERROR: Could not load OpenSlide native library
    at java.lang.ClassLoader$NativeLibrary.load(Native Method)
    at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
    at java.lang.Runtime.loadLibrary0(Runtime.java:870)
    at java.lang.System.loadLibrary(System.java:1122)
    at org.openslide.OpenSlideJNI.<clinit>(OpenSlideJNI.java:55)
    at org.openslide.OpenSlide.<clinit>(OpenSlide.java:53)
    at qupath.lib.images.servers.OpenslideImageServer.<init>(OpenslideImageServer.java:91)
    at qupath.lib.images.servers.OpenslideServerBuilder.buildServer(OpenslideServerBuilder.java:51)
    at qupath.lib.images.servers.ImageServerProvider.buildServer(ImageServerProvider.java:115)
    at qupath.lib.gui.QuPathGUI.openImage(QuPathGUI.java:2228)
    at qupath.lib.gui.viewer.DragDropFileImportListener.handleFileDrop(DragDropFileImportListener.java:253)
    at qupath.lib.gui.viewer.DragDropFileImportListener.handle(DragDropFileImportListener.java:115)
    at qupath.lib.gui.viewer.DragDropFileImportListener.handle(DragDropFileImportListener.java:59)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene$DnDGesture.fireEvent(Scene.java:2933)
    at javafx.scene.Scene$DnDGesture.processTargetDrop(Scene.java:3159)
    at javafx.scene.Scene$DnDGesture.access$6400(Scene.java:2909)
    at javafx.scene.Scene$DropTargetListener.drop(Scene.java:2873)
    at com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.lambda$handleDragDrop$309(GlassSceneDnDEventHandler.java:95)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.handleDragDrop(GlassSceneDnDEventHandler.java:92)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleDragDrop$363(GlassViewEventHandler.java:700)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleDragDrop(GlassViewEventHandler.java:699)
    at com.sun.glass.ui.View.handleDragDrop(View.java:712)
    at com.sun.glass.ui.View.notifyDragDrop(View.java:1037)
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
    at java.lang.Thread.run(Thread.java:745)
ERROR: Unable to build whole slide server - check your classpath for a suitable library (e.g. OpenSlide, BioFormats)
	
ERROR: C:\ProgramData\App-V\46D140A1-54B6-42AA-A72A-99DBBA62CB07\6C3334CF-C8C7-49EA-9F90-47768DFB4373\Root\VFS\ProgramFilesX64\QuPath\app\QuPathApp.jar;qupath/qupath-core-0.1.2.jar;qupath/qupath-core-awt-0.1.2.jar;qupath/qupath-core-processing-0.1.2.jar;qupath/qupath-core-processing-awt-0.1.2.jar;qupath/qupath-extension-ij-0.1.2.jar;qupath/qupath-extension-input-0.1.2.jar;qupath/qupath-extension-opencv-0.1.2.jar;qupath/qupath-extension-openslide-0.1.2.jar;qupath/qupath-extension-pen-0.1.2.jar;qupath/qupath-extension-script-editor-0.1.2.jar;qupath/qupath-gui-fx-0.1.2.jar;qupath/qupath-processing-ij-0.1.2.jar;qupath/qupath-processing-opencv-0.1.2.jar;jars/commons-math3-3.6.1.jar;jars/controlsfx-8.40.12.jar;jars/flowless-0.4.5.jar;jars/groovy-2.4.7.jar;jars/groovy-jsr223-2.4.7.jar;jars/gson-2.8.0.jar;jars/ij-1.51g.jar;jars/jfxtras-common-8.0-r5.jar;jars/jfxtras-menu-8.0-r5.jar;jars/jinput-2.0.6.jar;jars/jpen-2-150301.jar;jars/jutils-1.0.0.jar;jars/logback-classic-1.1.7.jar;jars/logback-core-1.1.7.jar;jars/opencv-3.1.0.jar;jars/openslide-3.4.1_2.jar;jars/packager.jar;jars/reactfx-2.0-M4u1.jar;jars/richtextfx-0.6.10.jar;jars/slf4j-api-1.7.20.jar;jars/undofx-1.2.jar;jars/wellbehavedfx-0.1.1.jar
ERROR: Open image: Sorry, I can't open D:\Rivka\nanozoomer\Scans RL 2\Exp 5 (LI)\A3 LI 03.ndpi

**Comment by petebankhead** [comment]
It looks like the root problem is that OpenSlide can't be loaded, which I presume is somehow related to the upgrade - but I don't know how.

I would suggest trying the zipped version of QuPath v0.1.2 and running it from your desktop (or at least a folder where you definitely have full write permissions): https://github.com/qupath/qupath/releases/tag/v0.1.2
(You will need to extract all the files from the zipped file and the .exe you need to run will be among them.)

**Comment by Svidro** [comment]
I would start by using another computer temporarily and ensuring you can open your data set with another installation of QuPath on that computer. Even better if it is a Win10 computer where you had not installed QuPath before. If it is a time crunch, using another computer might be the best short term bet.

**Comment by petebankhead** [comment]
For v0.1.2 you might also try installing the Bio-Formats extension: https://github.com/qupath/qupath-bioformats-extension
This would not 'solve' the problem, but it would add another reader to QuPath that is capable of handling NDPI files - which could be enough at this stage.

Please do report back if/when this is resolved so that I can close the issue. GitHub issues should really only be used to report QuPath bugs, and this doesn't seem to be one - for other discussions the best place is https://forum.image.sc/tags/qupath
But I wanted to answer here quickly in empathy for the impending submission deadline...

**Comment by Rivka1234** [comment]
Thank you very much for your replies. I’m going to try what you have suggested tomorrow and will definitely report back. Apologies for posting in the wrong bit and thanks again for the very fast replies!

**Comment by Rivka1234** [comment]
Hi, 

I got IT to reinstall as you suggested and it solved the problem. I was looking for my post to close it but can’t find it, can you close it for me please?

Thanks for your help. 

Rivka
