### ISSUE TITLE
Add Intensity Features: JPG fluorescent images

### ISSUE THREAD

**Issue by Svidro** [qupath/qupath#365]
## Bug report

**Describe the bug**
Add intensity measurements fails with error below when run on a JPG image (set to image type fluorescence). It seems likely that this is due to the normalized OD colors channel showing up second in the list, which inserts it into the channel list prior to the Red Green and Blue channels.
![image](https://user-images.githubusercontent.com/23145209/65450506-1b382800-ddf2-11e9-82ba-681885b1897b.png)
ERROR: Error running plugin: java.lang.IllegalArgumentException: No boolean parameter with key 'colorOD'
    at java.base/java.util.concurrent.FutureTask.report(Unknown Source)
    at java.base/java.util.concurrent.FutureTask.get(Unknown Source)
    at qupath.lib.plugins.AbstractPluginRunner.awaitCompletion(AbstractPluginRunner.java:193)
    at qupath.lib.plugins.AbstractPluginRunner.runTasks(AbstractPluginRunner.java:157)
    at qupath.lib.gui.plugins.PluginRunnerFX.runTasks(PluginRunnerFX.java:94)
    at qupath.lib.plugins.AbstractPlugin.runPlugin(AbstractPlugin.java:156)
    at qupath.lib.algorithms.IntensityFeaturesPlugin.runPlugin(IntensityFeaturesPlugin.java:355)
    at qupath.lib.gui.plugins.ParameterDialogWrapper$1.run(ParameterDialogWrapper.java:185)
    at java.base/java.lang.Thread.run(Unknown Source)
**To Reproduce**
Load a 3 color fluorescent image that has been converted into a JPG (Wince. Yes.) Generate cells, try to run Add Intensity Features. Adding fails with a message that is only reported in the log.

In multichannel images there is no Normalized OD colors channel that expects or generates OD measurements. In previous versions 1.2/1.3 this also did not occur. I haven't exhaustively checked which M# versions are affected.

**Desktop (please complete the following information):**
 - OS: Win10
 - QuPath Version 0.2.0m4

**Additional context**
Referencing: https://forum.image.sc/t/saving-cell-detection-locations-and-loading-them-in-another-image/29746/12

**Comment by Svidro** [comment]
Attempting to swap image servers from BioFormats to ImageJ, or to use Green/Blue/Hue (or even just Green/Blue in an effort to circumvent the Normalized OD channel) were not successful as work arounds.

**Comment by petebankhead** [comment]
Thanks, this should be resolved with the latest commit.

In the meantime, you can temporarily set the image type to Brightfield as a workaround when calculating intensity features in RGB images (assuming you use measurements that don't involve color deconvolution).
