### ISSUE TITLE
java.lang.NullPointerException   "Automate"  

### ISSUE THREAD

**Issue by GeorgiaLiapi** [qupath/qupath#373]
Dear Dr Peter,

I was having a project opened, with drawn annotations on a few H&E images. The following message popped-up when I clicked on **"Automate"**. It didn't open the regular choices shown when inserting a script; I instantly had:

_ERROR:_
INFO: Bio-Formats version 6.3.0
INFO: Loaded extension Bio-Formats server options (Bio-Formats 6.3.0) (29 ms)
INFO: Loaded extension Experimental commands (16 ms)
INFO: Loaded extension ImageJ extension (35 ms)
INFO: Loaded extension JPen extension (16 ms)
INFO: Loaded extension OpenCV extensions (5 ms)
INFO: Loaded extension Rich script editor extension (213 ms)
INFO: OpenSlide version 3.4.1
INFO: Selected style: null
INFO: Performing update check...
INFO: Starting QuPath with parameters: []
INFO: Project set to Project: _Name_
INFO: Image data set to ImageData: Brightfield (H&E), _ImageName_
ERROR: QuPath exception
    at qupath.lib.gui.ScriptMenuLoader.addMenuItemsForPath(ScriptMenuLoader.java:149)
    at qupath.lib.gui.ScriptMenuLoader.updateMenu(ScriptMenuLoader.java:130)
    at qupath.lib.gui.QuPathGUI.lambda$new$9(QuPathGUI.java:776)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.control.Menu.setShowing(Menu.java:198)
    at javafx.scene.control.Menu.show(Menu.java:412)
    at javafx.scene.control.skin.MenuBarSkin.showMenu(MenuBarSkin.java:472)
    at javafx.scene.control.skin.MenuBarSkin.showMenu(MenuBarSkin.java:451)
    at javafx.scene.control.skin.MenuBarSkin.lambda$rebuildUI$27(MenuBarSkin.java:983)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene$MouseHandler.process(Scene.java:3862)
    at javafx.scene.Scene.processMouseEvent(Scene.java:1849)
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2590)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:409)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:299)
    at java.base/java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:447)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:446)
    at com.sun.glass.ui.View.handleMouseEvent(View.java:556)
    at com.sun.glass.ui.View.notifyMouse(View.java:942)
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
    at java.base/java.lang.Thread.run(Unknown Source)

**Expected behavior**
In the past, I had no issues. I was able to use scripts and they were running succesfully.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - QuPath Version [e.g. 0.2.0(m4 or m5)]

**Additional context**
I closed and re-started QuPath. The error remains. I went from m4 to m5, still the same. 
Sometimes the error appears even when dragging the mouse cursor on "Automate" without clicking on it.
I cannot understand the error.

Any help would be appreciated.

Kind Regards,
Georgia

**Comment by petebankhead** [comment]
Hi Georgia,
Could you try using _Edit &earr; Reset Preferences_?
If that resolves the issue then I think the QuPath isn't able to find some path to scripts. I'm not sure why (maybe a directory is missing or located on a server that isn't accessible?) and it shouldn't cause an error like this so I'll investigate anyway on the QuPath side.
If the doesn't resolve it then I'm not sure what the problem could be.... does it happen with all projects or just one?

**Comment by GeorgiaLiapi** [comment]
Dear Dr Peter,

Resetting the Preferences **solved** the problem.
It is working.
The issue was probably based on the path as you said. 

Thank you very much for your help!

**Comment by petebankhead** [comment]
I wasn't able to replicate this, but a change in v0.2.0-m7 means that hopefully it should not happen again. If it does, please reopen this issue.
