### ISSUE TITLE
Failed to open tif file

### ISSUE THREAD

**Issue by Daniel-01** [qupath/qupath#382]
quPath 0.2.0-m7 fail to open some pyramid tif files that could be open with 0.1.2.
Unfortunately, I am not allowed to share the files.

I dont think the problem is out of memory, since I have tif images that are twice as big that can be opened without problem. 

I have tested both on Windows 10 and Ubuntu 18.

Here is the log from a Windows machine:
INFO: Bio-Formats version 6.3.0
INFO: Loaded extension Bio-Formats server options (Bio-Formats 6.3.0) (22 ms)
INFO: Loaded extension Experimental commands (18 ms)
INFO: Loaded extension ImageJ extension (58 ms)
INFO: Loaded extension JPen extension (22 ms)
INFO: Loaded extension OpenCV extensions (3 ms)
INFO: Loaded extension Rich script editor extension (373 ms)
INFO: OpenSlide version 3.4.1
INFO: Selected style: null
INFO: Performing update check...
WARN: No changelog found - will not check for updates
INFO: Starting QuPath with parameters: []
WARN: Unable to obtain full image format info for file:/D:/pDST/eHE-PDS18-015016-leica.tif (class java.util.NoSuchElementException)
WARN: Temp memoization directory created at C:\Users\DanielH\AppData\Local\Temp\qupath-memo-13737650391880953912
WARN: If you want to avoid this warning, either disable Bio-Formats memoization in the preferences or specify a directory to use
ERROR:  *** One or more readers is misbehaving. See the debug output for more information. e.g.:
     loci.formats.in.APLReader@578b4451 -> java.lang.NullPointerException('null') ***
WARN: Removing alpha channel
WARN: Removing alpha channel
ERROR: QuPath exception: Java heap space
    at java.desktop/sun.awt.image.IntegerInterleavedRaster.getDataElements(Unknown Source)
    at qupath.lib.display.ChannelDisplayInfo$RGBDirectChannelInfo.getRGBIntBuffer(ChannelDisplayInfo.java:539)
    at qupath.lib.display.ChannelDisplayInfo$RBGColorTransformInfo.getValues(ChannelDisplayInfo.java:707)
    at qupath.lib.display.ImageDisplay$HistogramManager.ensureChannels(ImageDisplay.java:902)
    at qupath.lib.display.ImageDisplay.updateHistogramMap(ImageDisplay.java:573)
    at qupath.lib.display.ImageDisplay.setImageData(ImageDisplay.java:144)
    at qupath.lib.gui.viewer.QuPathViewer.setImageData(QuPathViewer.java:1475)
    at qupath.lib.gui.QuPathGUI.openImage(QuPathGUI.java:2547)
    at qupath.lib.gui.QuPathGUI.openImage(QuPathGUI.java:2425)
    at qupath.lib.gui.commands.OpenCommand.run(OpenCommand.java:51)
    at qupath.lib.gui.QuPathGUI.lambda$createCommandAction$53(QuPathGUI.java:3528)
    at qupath.lib.gui.QuPathGUI$$Lambda$155/0x000000080024c040.accept(Unknown Source)
    at org.controlsfx.control.action.Action.handle(Action.java:419)
    at org.controlsfx.control.action.Action.handle(Action.java:64)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.control.MenuItem.fire(MenuItem.java:459)
    at com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1380)
    at com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.lambda$createChildren$12(ContextMenuContent.java:1333)
    at com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer$$Lambda$1427/0x00000008006c1040.handle(Unknown Source)
    at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)

**Comment by petebankhead** [comment]
It may work if you open the image within a project and specify that OpenSlide should be the image server. This could have been the default in v0.1.2 and the underlying issue is that Bio-Formats does not support this particular sort of tiff fully.

Parts of the error message also bring back memories. You may also reduce problems using Bio-Formats by putting the image inside another (sub)folder: https://github.com/ome/bioformats/issues/3343

**Comment by Daniel-01** [comment]
Yes, the project + openslide trick works.
Thanks!
