### ISSUE TITLE
Example script does not work in QuPath version 0.2.0-m9 (but in 0.1.2)

### ISSUE THREAD

**Issue by saanasum** [qupath/qupath#404]
## Bug report

**Describe the bug**
An example Script does not work in QuPath version 0.2.0-m9 (but in 0.1.2).
The script can be found here: https://github.com/qupath/qupath/wiki/Scripting-examples --> _Tiling a whole slide image_

**To Reproduce**
Use this script in v.0.1.2 and v.0.2.0-m9

**Expected behavior**
works in v.0.1.2 but not in v.0.2.0-m9

**Desktop (please complete the following information):**
 - Ubuntu 18.04 LTS
 - QuPath Version  v.0.1.2 and v.0.2.0-m9

**Additional context**
Error massage is:

```
> ERROR: It looks like you have tried to import a class 'qupath.imagej.images.servers.ImagePlusServerBuilder' that doesn't exist!
> You should probably remove the broken import statement in your script (around line 17).
> Then you may want to check 'Run -> Include default imports' is selected, or alternatively add 
>     import qupath.imagej.tools.IJTools
> at the start of the script. Full error message below.
> 
> ERROR: MultipleCompilationErrorsException at line 16: startup failed:
> Script1.groovy: 17: unable to resolve class qupath.imagej.images.servers.ImagePlusServerBuilder
>  @ line 17, column 1.
>    import qupath.imagej.images.servers.ImagePlusServerBuilder
>    ^
> 
> Script1.groovy: 16: unable to resolve class qupath.imagej.images.servers.ImagePlusServer
>  @ line 16, column 1.
>    import qupath.imagej.images.servers.ImagePlusServer
>    ^
> 
> 2 errors
> 
> 
> ERROR: Script error (MultipleCompilationErrorsException)
>     at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:311)
>     at org.codehaus.groovy.control.CompilationUnit.applyToSourceUnits(CompilationUnit.java:975)
>     at org.codehaus.groovy.control.CompilationUnit.doPhaseOperation(CompilationUnit.java:637)
>     at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:586)
>     at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:401)
>     at groovy.lang.GroovyClassLoader.access$300(GroovyClassLoader.java:89)
>     at groovy.lang.GroovyClassLoader$5.provide(GroovyClassLoader.java:341)
>     at groovy.lang.GroovyClassLoader$5.provide(GroovyClassLoader.java:338)
>     at org.codehaus.groovy.runtime.memoize.ConcurrentCommonCache.getAndPut(ConcurrentCommonCache.java:147)
>     at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:336)
>     at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:320)
>     at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:262)
>     at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.getScriptClass(GroovyScriptEngineImpl.java:331)
>     at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:153)
>     at qupath.lib.gui.scripting.DefaultScriptEditor.executeScript(DefaultScriptEditor.java:800)
>     at qupath.lib.gui.scripting.DefaultScriptEditor.executeScript(DefaultScriptEditor.java:734)
>     at qupath.lib.gui.scripting.DefaultScriptEditor.executeScript(DefaultScriptEditor.java:714)
>     at qupath.lib.gui.scripting.DefaultScriptEditor$2.run(DefaultScriptEditor.java:1130)
>     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
>     at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
>     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
>     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
>     at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by petebankhead** [comment]
This is not a bug, but rather there are many changes in v0.2.0 that are not compatible with v0.1.2. The documentation for v0.2.0 is at https://qupath.readthedocs.io and does not contain this example.

For more information see https://petebankhead.github.io/qupath/2019/08/21/scripting-in-v020.html

**Comment by saanasum** [comment]
Ok. Thank you.
