### ISSUE TITLE
Click on "Automate" Button gives "QuPath exception" every time even after new installation

### ISSUE THREAD

**Issue by DavidMHaumann** [qupath/qupath#422]
**Description of the bug**
Left-click on the Automate-Button to open the drop down menue that incorporates the "script editor" causes opening of log window with the qupath-exception text (see below). 

Even not after reinstallation of QuPath and Java. 
Even to run QuPath inside a ZIP downloaded version does not solve the probem. 

**To Reproduce**
1. run the lock script: 
selectAnnotations()
getSelectedObjects().each {
   it.setLocked(true)
}
fireHierarchyUpdate()

There were large annotations with hierarchy. But only 170kb vertex points. One of them was a simple tissue detection. 

 
**Desktop (please complete the following information):**
 - 64 bit Windows10  
 - QuPath Version 0.1.2

**Exception text in log file**
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.control.Menu.setShowing(Menu.java:199)
    at javafx.scene.control.Menu.show(Menu.java:408)
    at com.sun.javafx.scene.control.skin.MenuBarSkin.lambda$rebuildUI$401(MenuBarSkin.java:677)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
    at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
    at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:380)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:294)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:416)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:415)
    at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
    at com.sun.glass.ui.View.notifyMouse(View.java:937)
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
    at java.lang.Thread.run(Thread.java:745)

**Comment by petebankhead** [comment]
*Edit &rarr; Reset preferences* should fix it (preferences aren't impacted by a new installation).
I notice you're using v0.1.2 - I think this bug should already have been fixed since then.

**Comment by petebankhead** [comment]
See also
* https://github.com/qupath/qupath/issues/373
* https://github.com/qupath/qupath/issues/349

**Comment by DavidMHaumann** [comment]
Hi Pete, 
thank you for your answer. Indeed reset preferences enables the automate menu. 
We can reopen the scirpt editor. But loading the script causes the bug again and again. 
It happens directly with opening the script, before the first run. 
Is there anything else we can try to avoid it?

best
David

**Comment by petebankhead** [comment]
I don't know; to better understand what has gone wrong I'd need to know more information about what might be different in this case from previous times when you loaded scripts and didn't have a problem (e.g. anything appearing in the log, where QuPath is installed / where the script is located, if other scripts have the same effect).

Since I can't replicate the problem myself, I'm afraid I can't really help much- also since the underlying issue should already be fixed in v0.2.0.

**Comment by DavidMHaumann** [comment]
ok, we try to switch to  a newer version. Do you directly recommend m9? Or better v.0.2.0?
I figured out, that the extension was missing. Maybe that was the reason. Within the last hour, we did not have the bug anymore.

**Comment by petebankhead** [comment]
I'd personally go with the most recent milestone, or wait for the stable version of v0.2.0 (hopefully within the next few weeks). I'll close this issue now.
