### ISSUE TITLE
Files in project are not accessible anymore after software has an abnormal shutdown

### ISSUE THREAD

**Issue by svanhalAIMM** [qupath/qupath#512]
## Bug report

**Describe the bug**
When working in a project and the computer or software crashes, you can later not access the file anymore that you were working on in the project. Meaning you loose all annotations and such. 

**To Reproduce**
1. Use your project with multiple files
2. turn off your pc without saving or something error related
3. Open the project again
4. Try to open the image you were working in
5. See error

![image](https://user-images.githubusercontent.com/66477655/83880620-b46c5c00-a73f-11ea-9f5e-5c9c0ce802d0.png)

**Expected behavior**
That the image is still accesible from an old version of the project.

**Screenshots**

![image](https://user-images.githubusercontent.com/66477655/83880655-c0f0b480-a73f-11ea-94ce-c4b19533e37d.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - QuPath Version 0.2.0

**Comment by petebankhead** [comment]
We'd need more information to be able to help, including:

* what errors do you see under *View -> Show log*?
* how precisely did the abnormal shutdown occur?
* can you give precise steps to replicate the issue?
* do the other images in the project work?

QuPath tries to offer the user some protection by creating a backup data file while writing the new one, in case this does not succeed - see https://github.com/qupath/qupath/blob/85700bbb026e1e72425e266ee3105b2f39c4f4fd/qupath-core/src/main/java/qupath/lib/projects/DefaultProject.java#L730-L779

Therefore I think that this bug report is not correct in general (i.e. any abnormal termination will cause data to be lost) - rather, the specific steps are essential to understand the problem.

Note that you can right-click on the image under the 'Project' tab and go to the directory that contains the problematic `.qpdata` file. If your see a file ended with `.bkp` you could try renaming it to replace the corrupt/incomplete `.qpdata` and see if that restores the last saved data for you.

**Comment by svanhalAIMM** [comment]
Hi Pete, thanks for your reply. I agree that every abnormal termination will cause data to be lost, but I do have the strong feeling it should not brake the file ;) I hope you can agree on that. 

I tried your approach and that indeed made the sample available again! Thanks! 

To answer your questions:

1. what errors do you see under View -> Show log?

INFO: Bio-Formats version 6.5.0
INFO: Loaded extension Bio-Formats server options (Bio-Formats 6.5.0) (13 ms)
INFO: Loaded extension Experimental commands (1 ms)
INFO: Loaded extension Experimental commands (35 ms)
INFO: Loaded extension ImageJ extension (41 ms)
INFO: Loaded extension JPen extension (14 ms)
INFO: Loaded extension Rich script editor extension (244 ms)
INFO: Loaded extension SVG export commands (0 ms)
INFO: OpenSlide version 3.4.1
INFO: Starting QuPath with parameters: []
INFO: Project set to Project: CD3 analysis-project
WARN: Openslide: Property 'openslide.objective-power' not available, will return default value NaN
ERROR: Reached end of file...
ERROR: Load ImageData: QuPath has encountered a problem, sorry.
If you can replicate it, please report it with 'Help -> Report bug (web)'.

java.lang.NullPointerException
ERROR: Load ImageData
    at qupath.lib.objects.hierarchy.PathObjectHierarchy.setHierarchy(PathObjectHierarchy.java:731)
    at qupath.lib.io.PathIO.readImageDataSerialized(PathIO.java:203)
    at qupath.lib.io.PathIO.readImageData(PathIO.java:278)
    at qupath.lib.projects.DefaultProject$DefaultProjectImageEntry.readImageData(DefaultProject.java:716)
    at qupath.lib.gui.QuPathGUI.openImageEntry(QuPathGUI.java:2634)
    at qupath.lib.gui.panes.ProjectBrowser.lambda$new$3(ProjectBrowser.java:190)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene$ClickGenerator.postProcess(Scene.java:3597)
    at javafx.scene.Scene$MouseHandler.process(Scene.java:3899)
    at javafx.scene.Scene.processMouseEvent(Scene.java:1885)
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2618)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:409)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:299)
    at java.base/java.security.AccessController.doPrivileged(Unknown Source)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:447)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:446)
    at com.sun.glass.ui.View.handleMouseEvent(View.java:556)
    at com.sun.glass.ui.View.notifyMouse(View.java:942)
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
    at java.base/java.lang.Thread.run(Unknown Source)


2. how precisely did the abnormal shutdown occur?

I had a VPN connection with my pc in the office and then somebody else logged in to the machine and I got logged out. The VPN connection is via a .rdp file where I can just use my home screen/pc as a window to my office pc (is this clear?)

3. can you give precise steps to replicate the issue? -> Yes I can for this one but it happened to me before and I can not replicate that anymore. 

In this particular case, have VPN connection with a PC. 
Open the software
Open a project
Work on a picture in the project
Let somebody else login without login you out
Wait until this person is finished working
login yourself again
Try to continue working -> not possible, software will crash
Close software via the Task Manager
Open software and open same project
Particular picture you were working on is now no longer available. 

4. do the other images in the project work?
Yes the other images work. 

Thanks! For now your quick fix has saved me a lot of time :)

**Comment by petebankhead** [comment]
Thanks for the extra details. How many data files did you lose this way?

I ask because it sounds like it should *only* happen when the timing is particularly unfortunate and the connection is lost when writing... but I'm not exactly sure. I don't have a similar VPN setup that I can use to test it.

It sounds to me like the best fix QuPath can offer would be to automatically discover and use the .bkp file (rather than you needing to find it yourself) -- logging a warning to the console to state that it has done this.

Does that sound right to you?

**Comment by svanhalAIMM** [comment]
For now it was 2 times and luckily only 2 images (unfortunate within the same project). I think, it always happens when you use the Task manager to shut down the software, maybe that is something to be tested? I remember last time I also had to close the software with the Task manager because after half an hour it still did not respond.. 

It would be awesome if indeed QuPath can discover the .bkp file and ask if this needs to be saved as the new data file, maybe indicating the date and time of the last back up to ask if you want to go back to this file or start from scratch to say so. But in general, this sounds like a good possible solution! Thanks!

**Comment by petebankhead** [comment]
I've made some changes in the recent commits that should help. This should automatically result in the .bkp file being used if the 'proper' data file cannot be found.

I was unable to find any general problem with closing from the task manager, but it would make sense if the software hangs because of a problem writing the data file and it is force quit for that reason. In this case, restoring from the backup is probably the best QuPath can offer anyway.

I'll close this issue, v0.2.1 should be available next week containing this and some other minor fixes.
