### ISSUE TITLE
Loading saved project/data

### ISSUE THREAD

**Issue by hartlandj** [qupath/qupath#58]
I have saved a project in which I had identified single cells throughout a single TMA image. Upon closing and reloading the project I can see all images, but cannot load any information from any preprocessing or cell analysis.
Log and Error below.
Thanks for your help,
Hart

INFO: Reading data from HER2.qpdata...
ERROR: Reached end of file...
ERROR: QuPath exception
    at qupath.lib.objects.hierarchy.PathObjectHierarchy.setHierarchy(PathObjectHierarchy.java:627)
    at qupath.lib.io.PathIO.readImageDataSerialized(PathIO.java:239)
    at qupath.lib.io.PathIO.readImageData(PathIO.java:334)
    at qupath.lib.gui.QuPathGUI.openSavedData(QuPathGUI.java:2399)
    at qupath.lib.gui.QuPathGUI.openImage(QuPathGUI.java:2208)
    at qupath.lib.gui.QuPathGUI.openImage(QuPathGUI.java:2152)
    at qupath.lib.gui.commands.OpenCommand.run(OpenCommand.java:51)
    at qupath.lib.gui.QuPathGUI.lambda$createCommandAction$46(QuPathGUI.java:3122)
    at org.controlsfx.control.action.Action.handle(Action.java:419)
    at org.controlsfx.control.action.Action.handle(Action.java:64)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.control.MenuItem.fire(MenuItem.java:462)
    at com.sun.javafx.scene.control.GlobalMenuAdapter.lambda$bindMenuItemProperties$20(GlobalMenuAdapter.java:153)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.control.MenuItem.fire(MenuItem.java:462)
    at com.sun.javafx.tk.quantum.GlassSystemMenu$1.action(GlassSystemMenu.java:238)

**Comment by petebankhead** [comment]
I'm afraid it looks like the ```.qpdata``` file is incomplete for some reason, effectively making the data corrupt/unreadable for QuPath.

See [this thread](https://groups.google.com/forum/#!topic/qupath-users/sYzchFq-Y60) for some more information - and for some details about ```.backup``` files, which might (possibly) be able to help.

This appears to happen very rarely, and I don't know why (since I don't recall the last time it happened to me).  Do you happen to remember did anything strange happen / did QuPath crash when saving the data the first time around?  Or can you figure out any way to reproduce the problem?

It's particularly hard to debug, since I presume that the problem happens when saving but the error log only shows what happens when trying to reload the data.  I haven't found a way to reproduce it myself, so any insights you could have on what could have caused it would be very welcome.
