### ISSUE TITLE
Set ImageJ plugins directory - failing

### ISSUE THREAD

**Issue by JoaoSantinha** [qupath/qupath#91]
Hi,
I am trying to set the ImageJ plugins directory and I am getting the following error:

INFO: Selected style: Modena Light
INFO: Performing update check...
INFO: Starting QuPath with parameters: []
ERROR: QuPath exception
    at java.io.File.<init>(File.java:277)
    at qupath.imagej.gui.IJExtension.lambda$1(IJExtension.java:468)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.control.MenuItem.fire(MenuItem.java:462)
    at com.sun.javafx.scene.control.GlobalMenuAdapter.lambda$bindMenuItemProperties$20(GlobalMenuAdapter.java:153)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.control.MenuItem.fire(MenuItem.java:462)
    at com.sun.javafx.tk.quantum.GlassSystemMenu$1.action(GlassSystemMenu.java:238)

Thanks in advance for the help

**Comment by petebankhead** [comment]
Ah.... so am I.  It seems to be a bug if the directory isn't set.

However, you can also set the plugins directory through *Edit &rarr; Preferences...* - type ImageJ into the search box, and the option should appear.  Double-click on the text entry box to be able to choose the directory.

Once you do that, *Edit &rarr; ImageJ &rarr; Set ImageJ plugins directory* should work again.

That appears to work for me, and avoids the bug.

**Comment by JoaoSantinha** [comment]
Thank you very much for the suggestion! I didn't even though of having a look at the Preferences. 

It worked!

**Comment by petebankhead** [comment]
This should be fixed in the latest milestone versions thanks to the commit above; if not, please reopen the issue.
