### ISSUE TITLE
"Duplicate Image(s)" attempts to parse regex expression in project entry name

### ISSUE THREAD

**Issue by MarkZaidi** [qupath/qupath#942]
**Describe the bug**
Attempting to duplicate a project entry containing an unclosed parenthesis (e.g. a left parenthesis `(` with no right parenthesis to follow) will throw an error, preventing the entry from being duplicated without renaming. Relatively minor issue, as a fix would be to simply rename the original entry before duplication.

**To Reproduce**
1. Create a project, loading an image named `OS-2.ndpi`
2. Duplicate the project entry (via right click > Duplicate Image(s). No error will occur, duplicate image will be named `OS-2.ndpi (1)`
3. Rename this duplicated image by removing the last parenthesis, to `OS-2.ndpi (1`
4. Attempt to duplicate this image. Note the following error:
![image](https://user-images.githubusercontent.com/52012166/161337956-5eabd4e7-0b3e-4a29-8b1b-914e3484cda7.png)
See full log at the end.

**Expected behavior**
Regex patterns should not be evaluated for when duplicating image names. I'd imagine there are a lot of other character combinations that can trigger regex-related errors during duplication, or perhaps other operations too. I wonder if there's any cool things that can be done with this, such as programmatically creating image names during image duplication...

**Desktop (please complete the following information):**
 - OS: Windows 10
 - QuPath Version: 0.4.0-SNAPSHOT

**Additional context**
Full error log:
```
ERROR: QuPath exception: Unclosed group near index 24
OS-2.ndpi (1 \(([\d]+)\)
java.util.regex.PatternSyntaxException: Unclosed group near index 24
OS-2.ndpi (1 \(([\d]+)\)
    at java.base/java.util.regex.Pattern.error(Unknown Source)
    at java.base/java.util.regex.Pattern.accept(Unknown Source)
    at java.base/java.util.regex.Pattern.group0(Unknown Source)
    at java.base/java.util.regex.Pattern.sequence(Unknown Source)
    at java.base/java.util.regex.Pattern.expr(Unknown Source)
    at java.base/java.util.regex.Pattern.compile(Unknown Source)
    at java.base/java.util.regex.Pattern.<init>(Unknown Source)
    at java.base/java.util.regex.Pattern.compile(Unknown Source)
    at qupath.lib.common.GeneralTools.generateDistinctName(GeneralTools.java:774)
    at qupath.lib.gui.panes.ProjectBrowser.lambda$getPopup$14(ProjectBrowser.java:456)
    at org.controlsfx.control.action.Action.handle(Action.java:423)
    at org.controlsfx.control.action.Action.handle(Action.java:64)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.control.MenuItem.fire(MenuItem.java:459)
    at com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1385)
    at com.sun.javafx.scene.control.ContextMenuContent$MenuItemContainer.lambda$createChildren$12(ContextMenuContent.java:1338)
    at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:247)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:234)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene$MouseHandler.process(Scene.java:3897)
    at javafx.scene.Scene.processMouseEvent(Scene.java:1878)
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2623)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:411)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:301)
    at java.base/java.security.AccessController.doPrivileged(Unknown Source)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:450)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:424)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:449)
    at com.sun.glass.ui.View.handleMouseEvent(View.java:557)
    at com.sun.glass.ui.View.notifyMouse(View.java:943)
    at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:184)
    at java.base/java.lang.Thread.run(Unknown Source)
WARN: Cannot set image name to OS-2.ndpi (1 - will ignore
```

**Comment by petebankhead** [comment]
Thanks for the clear bug report again, it should be fixed now.
